tuskyapp/Tusky

app/src/main/res/values/donottranslate.xml
hi,
Android Studio does not recognize not-translatables correctly without the translattable=false parameter and marks them as missing translation (however, the automatic linting on build seems to ignore them correctly).
Have nice day :)
=> add translatable=false accordingly

app/src/main/res/values-fr/strings.xml
hey,
i just added a missing backspace to fix the 'Apostrophe not proceeded by' error in the french translation.
:)
=> fix unescaped apostrophe

app/src/main/res/layout/activity_account.xml, app/src/main/res/layout/activity_main.xml
Adds a shadow below the TabLayout. This makes it easier to distinguish UI elements as before both the tabs and list below had identical background colors
=> Adjust light theme tab bar area

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java, app/src/main/java/com/keylesspalace/tusky/SFragment.java
hi,
Mastodon-Web automatically adds the content-warnings from the toot one is replying to.
I added a few lines that check if a new toot is a reply and if so, it inherits the content notes from its predecessor.
=> inherit content warnings in replies

app/src/main/java/com/keylesspalace/tusky/SFragment.java, app/src/main/res/menu/status_more.xml, app/src/main/res/values/strings.xml
changed the share button menu to allow for sharing either the link, or the actual content of the post
added values into @string file to accommodate for the change
added the new share submenu into the status_more layout xml
=> Share menu now allows for sharing of link/actual post

app/src/main/java/com/keylesspalace/tusky/FooterViewHolder.java, app/src/main/java/com/keylesspalace/tusky/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/TimelineAdapter.java, app/src/main/java/com/keylesspalace/tusky/TimelineFragment.java, app/src/main/res/layout/item_footer_empty.xml, app/src/main/res/layout/item_footer_end.xml, app/src/main/res/values/strings.xml
The current implementation of endless scrolling has a few user interface issues, for example that the loading animation is shown even if nothing is loaded in the background (see eg. #62).
This pull request is not perfect in all situations, but improves the overall situation, especially for new users.
Before:
After:
=> Timeline footer improvements

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
Currently, if you for example press "TOOT" whithout having entered any text (empty toots are not allowed), you will end up in a state where you cannot do anything any more. This change re-enables the buttons after a failure and allows you to retry.
=> Re-enable controls after failed toot

app/src/main/res/values-tr/strings.xml
I've started the process of localizing all the strings to Turkish. If anybody wants to help please let me know. Also if anybody has ideas for localizing Mastodon specific terminology or links to good discussions on other languages that would be great. For example
* What languages are importing "toot" as a noun or verb? What languages have picked a substitute for this? The literal verb would be "ötmek" in Turkish but that doesn't seem quite right. It doesn't have as light hearted a connotation an the English.
* A direct translation of "instance" as used in programming such as an instance of a class would be "oluşum", however this can also mean version or composition or any number of other things. The English is confusing enough here, I don't want the  confusion to be even worse in …
=> Turkish translation

app/src/main/AndroidManifest.xml, app/src/main/java/com/keylesspalace/tusky/MainActivity.java, app/src/main/java/com/keylesspalace/tusky/ViewMediaFragment.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml
hi,
I implemented downloading images by tap-and-hold on a fullscreen image. 📷 
The download itself is handled by androids DownloadManager, images are stored in Pictures/$app_name on the internal storage.
The filename is generated from the url, pictures appear in the systems gallery.
Runtime permissions are supported, but the error handling if it's not granted (like done with the media upload) is not yet working (see comments in the code).
~~Known issues: When the permission is granted at runtime, the download button has to be pressed again~~
Tested on: Android 7.0
Todos: ~~fix the issue,~~ preferences for storage location (internal or sd), translation
I will try to implement the preferences later ~~, but I think i'm not experienced enough for the permission-not-granted-thing.~~
Happy …
=> [fixed] add support for downloading images

app/src/main/java/com/keylesspalace/tusky/StatusViewHolder.java
fixes https://github.com/Vavassor/Tusky/issues/179
ideally, one would use some placeholder image that symbolizes broken media. But this will do for now.
Also, there is probably a bug on the server as I dont think empty urls are intended.
=> fixes crash when media url of status is empty

app/src/main/res/values-ja/strings.xml
Improved and added new translation.
In string name="dialog_whats_an_instance", fixed link of List-of-Mastodon-instances.md from [old URL](https://github.com/tootsuite/mastodon/blob/master/docs/Using-Mastodon/List-of-Mastodon-instances.md) to [new URL](https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/List-of-Mastodon-instances.md) that has moved.
=> Improves Japanese translation

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
When entering text in the compose field default to capitalizing the first letter of the sentence. Eg instead of `foo` have it be `Foo` 
(uses [TYPE_TEXT_FLAG_CAP_SENTENCES](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_CAP_SENTENCES))
=> Make compose EditText TYPE_TEXT_FLAG_CAP_SENTENCES

app/src/main/res/drawable/ic_local_24dp.xml
fits much better with the other material design icons
before:
after:
=> use material design icon for local timeline tab

app/src/main/res/values-ar/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-tr/strings.xml
Since most of the translations were initially started new features have been added requiring new strings. Also the strings were re-arranged a bit.
I went through all the existing translations and made sure the keys match the original. For ones that were missing, I added the current English strings. Where applicable I also organized them to be in the same order for easy comparison.
Note this highlights what translators need to catch up on for new strings, but it doesn't show off where strings have been edited. In particular they should review the `visibility_*` strings and `dialog_whats_an_instance` as those seem to be the most significant  changes.
I brought the TR strings up to date, but after this merges we should ping other translators to review their languages.
=> Normalize strings

app/src/main/java/com/keylesspalace/tusky/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/TimelineFragment.java
- fixes bug where fab hiding on scroll would not work in NotificationsFragment
- fixes bug where fab would be hidden completely until app restart when the option was toggled while fab was invisible
- also SharedPreferences.getBoolean is not called in the ScrollListener anymore as it is quite an expensive operation and a ScrollListener is called very often
@theZacAttacks
=> fix bugs with fab showing/hiding on scroll

app/src/main/res/layout/activity_main.xml
before
after
(also, I ran "reformat code" on the file, makes it more readable imho)
=> make tabs fill whole space in landscape mode

app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java
Although for now it makes no difference calling super.onCreate or not
(the method Application.onCreate() is empty), it is denoted with
@CallSuper and might cause errors in some IDE if it is not called.
=> TuskyApplication: call super.onCreate()

app/src/main/AndroidManifest.xml, app/src/main/java/com/keylesspalace/tusky/MainActivity.java
I added an onConfigurationChanged() listener to MainActivity class so that when you change the orientation of the screen the Activity doesn't get destroyed. This fixes issues 190 & 259 that both relate to changing screen orientation while running Tusky.
The diffs look worse than they should due I think to the difference in line end characters, between my version of the files and the original version.
=> Fixed issues #190 & #259 screen orientation in MainActivity

app/src/main/java/com/keylesspalace/tusky/MainActivity.java
=> fixed light theme header background when no header image is set

app/src/main/res/layout/activity_edit_profile.xml, app/src/main/res/layout/activity_login.xml
TextInputLayout is intended to be used with TextInputEditText
https://developer.android.com/reference/android/support/design/widget/TextInputLayout.html
=> use TextInputEditText instead of EditText inside TextInputLayout

app/src/main/java/com/keylesspalace/tusky/entity/Status.java
fixes https://github.com/Vavassor/Tusky/issues/265
While this specific crash could be fixed with  `@SerializedName("unknown")`, I decided to go with a custom JsonDeserializer to make sure the MediaAttachment.TYPE is always set to UNKNOWN if the json could not be mapped to the enum.
=> fixed crash when MediaAttachment.Type is unknown

app/src/main/java/com/keylesspalace/tusky/LoginActivity.java, app/src/main/res/layout/activity_login.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
When coming from the chrome tab, the app was still showing the domain input for ~1 second before switching to the main activity. Now, the app shows a progress bar during this period.
I am not really aware of the naming convention, so don't hesitate to request some changes.
=> Add loading on login activity while fetching tokens

app/src/main/java/com/keylesspalace/tusky/AccountActivity.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/util/TimelineReceiver.java
Implements removing statuses of a user from home timeline when unfollowing, and from all timelines when muting/blocking.
There is still work to be done in order to sync favourite and reblog.
I don't know if it should have the same behavior when muting and blocking. I did not get the difference.
Also, I don't if it is relevent to put `TimelineReceiver` in the `util` package, maybe it should be in `adapter`.
=> Allow broadcasting event across activities, closes #280

app/src/main/java/com/keylesspalace/tusky/AccountActivity.java
To reproduce the bug, go to AccountActivity, scroll up so the toolbar collapses.
Look at the console output, it gets spammed with 
```
05-25 18:57:56.857 18678-18678/com.keylesspalace.tusky W/View: requestLayout() improperly called by android.support.v7.widget.AppCompatTextView{25ba0001 V.ED.... ........ 108,47-417,78} during second layout pass: posting in next frame
05-25 18:57:56.865 18678-18678/com.keylesspalace.tusky W/View: requestLayout() improperly called by android.support.design.widget.CollapsingToolbarLayout{25482f0b V.ED.... ......ID 0,0-540,379 #7f0e009e app:id/collapsing_toolbar} during layout: running second layout pass
```
or take a look at the cpu usage - 😳
this PR fixes the problem
@raphaelm I think you implemented this initially
=> fix bug in CollapsingToolbarLayout / OnOffsetChangedListener / AccountActivity

app/src/main/res/values-ja/strings.xml
New translations added for Japanese.
I did not translate strings used in "About" page because I'm worried that users may expect that we can understand Japanese, especially with bug reports & feature requests.
Showing "About" page in English would be better than discouraging them when they see the project site wrote in English.
=> Adds Japanese translations.

app/src/main/java/com/keylesspalace/tusky/adapter/AccountViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/java/com/keylesspalace/tusky/interfaces/StatusActionListener.java
Since tapping on a status opens original (not boosted) status, it is impossible to jump to the user who booster the status. So, now clicking on a boost line opens account.
I also renamed "id" in AccountViewHolder because it confused me at first. Hope you don't mind that I left it in this commit.
=> Add boost click handling

app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java, app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/ThreadAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/TimelineAdapter.java, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/java/com/keylesspalace/tusky/interfaces/StatusActionListener.java, app/src/main/java/com/keylesspalace/tusky/util/PairedList.java, app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.java, app/src/main/java/com/keylesspalace/tusky/viewdata/NotificationViewData.java, app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.java, app/src/main/res/layout/item_status.xml
Some things were pulled out of adapters to fragments. New classes were introduced - StatusViewData and NotificationViewData. They not only have view state in them but also help decoupling.
Because introducing parallel model list requires a lot of synchronization PairedList was added.
Also synchronization between fragments and adapters is quiet tedious and error-prone and should be replaces with better solution.
Oh, I also couldn’t resist and fixed bug with buttons animation in the same commit.
I checked it and seems like everything works but there may be some corner cases so I think it should be double-checked at least.
I understand that this may be quite a lot for one PR but it's quiet hard to fix separately. Thanks for your time.
=> Preserve status states on updates. UI layer refactoring.

app/src/main/java/com/keylesspalace/tusky/util/PairedList.java
This bug led to incorrect refreshing of the timeline.
=> Fix bug with paired list incorrectly adding to the specified position.

app/src/main/AndroidManifest.xml, app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.java
fixes https://github.com/Vavassor/Tusky/issues/347
tested on my Android 5 & Android 7 devices
**ATTENTION this introduces a new permission in the manifest**
I just wonder... why did nobody check if the download code actually works? You can't request a permission that does not exist in the manifest...
=> fix permission problem when downloading image

app/src/main/java/com/keylesspalace/tusky/AccountListActivity.java, app/src/main/java/com/keylesspalace/tusky/FavouritesActivity.java, app/src/main/java/com/keylesspalace/tusky/ViewTagActivity.java, app/src/main/java/com/keylesspalace/tusky/ViewThreadActivity.java
The duplicated interface will no appeared anymore. The problem is with the "stack memory" who do weird thing with his fragments.
no more duplicated stuff after that ;)
=> (fragment) quick changed

app/build.gradle, app/proguard-rules.pro
In https://github.com/Vavassor/Tusky/pull/365 I upgraded libraries but did not check if the production build still works, sorry.
I have no idea, why the production logging was enabled in this commit https://github.com/Vavassor/Tusky/commit/bb0ea876fa9844d620cdf25bf45582f3d5d1ee58 so I disabled it again. (Please explain if it wasnt a mistake)
Also, I had a look at the files contained in the apk and noticed some unnecessary metadata files bundled.
Yes, I do like my apks really small xD
=> optimize build files

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/res/drawable/ic_remove_red_eye_black_24dp.xml, app/src/main/res/layout/item_status.xml, app/src/main/res/layout/item_status_detailed.xml, app/src/main/res/values/dimens.xml
-The web client overlays a small eye button over sensitive images after they've been shown that re-hides them
=> (#377) hide sensitive images after showing them

app/src/main/java/com/keylesspalace/tusky/util/MentionTokenizer.java
The problem was that Tusky kept sending requests for autocompletion while writing toots even when the user wasn't typing a username anymore. As it happened very often we would exceed the API request limit and user wouldn't be able to send the toot.
This happened because Tokenizer is not used as expected. In fact, during testing, findTokenEnd() and terminateToken() were never called. I've tried setting a Validator but it wasn't used either. I'm not sure what is the reason.
I am afraid it still may work incorrectly for the full nicknames (ones with the instance name, like@name@isntance) because the search may happen for the instance name but it's not as critical.
=> Fix extra autocompletion requests

app/src/main/res/values-pt-rBR/strings.xml
- European Portuguese and Brazilian Portuguese have fundamental differences between them, so it's reasonable to distinguish them. That's why the folder is named values-pt-rBR rather than values-pt.
- I tried to keep it similar to translations on Mastodon and other apps.
=> i18n: PT-BR translation added

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java, app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java, app/src/main/java/com/keylesspalace/tusky/network/ProgressRequestBody.java, app/src/main/java/com/keylesspalace/tusky/view/ProgressImageView.java
There's an upload progress shown on the media now.
Had some fun with merging with myself, I hope everything is okay (also couldn't help myself but formatted ComposeActivity).
=> Add media upload progress. Closes #412

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/ThreadAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/TimelineAdapter.java, app/src/main/java/com/keylesspalace/tusky/entity/Notification.java, app/src/main/java/com/keylesspalace/tusky/entity/Status.java, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/java/com/keylesspalace/tusky/util/CollectionUtil.java, app/src/main/java/com/keylesspalace/tusky/util/Either.java, app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.java, app/src/main/java/com/keylesspalace/tusky/view/ConversationLineItemDecoration.java, app/src/main/java/com/keylesspalace/tusky/viewdata/NotificationViewData.java, app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.java
Okay, this may seem as an overkill but I've made it as clean as I could and it may save us some future headaches - programmer error will crash the app, not fail silently (which I would prefer in most cases).
I did this only for notifications but I would like to do the same for statuses, I just don't have time right now.
I modeled placeholder data using Either because Notification itself shouldn't be concerned about presentation so I think adding Placeholder as a notification type is not the best practice. ```Either``` shouldn't be huge overhead.
```NotificationVIewData``` is modeled using class hierarchy because it is okay for it to know that it may be a placeholder and it is cheaper.
I could implement ```Either``` using class hierarchy too but I just wrote it out of my mind. I am a …
=> Make placeholder abstraction cleaner

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/res/layout/item_status_notification.xml
I'm sorry, I'm doing non-planned things again but this was *so annoying*.
So, in summary:
* Notifications now work like boosts in timelines - clicking on a status opens the status, clicking on the message on the top opens account of the person who caused the notification.
* CWs now work like they do in the web version. Firstly, they're hidden in the notifications by default and user can trigger them. Secondly, when content is hidden mentions are still visible (when should do the same for timelines, code will stay pretty much the same).
Please, review!
(closes #322, partly #292)
=> Status notifications behavior (closes #322, partly #292)

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java, app/src/main/java/com/keylesspalace/tusky/LoginActivity.java, app/src/main/java/com/keylesspalace/tusky/MainActivity.java, app/src/main/java/com/keylesspalace/tusky/NotificationPullJobCreator.java, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/PreferencesFragment.java, app/src/main/java/com/keylesspalace/tusky/util/NotificationManager.java
=> Cancel notifications on opening notifications tab

app/src/main/res/values-ru/strings.xml
• Added missing translations to timestamps (1s, 2m, 3h etc);
• Renamed "bio" section (now it's translated as "about me" since "biography" means something large and detailed);
• Renamed "thread" sections (now it uses more native word "Discussion", rather than transliterated "Thread" word);
• Changed notification string about new notifications. This change may look a bit ugly, but it solves a problem with declension of numeric values.
=> Tweaks to Russian translation

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java, app/src/main/java/com/keylesspalace/tusky/SavedTootActivity.java, app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java, app/src/main/java/com/keylesspalace/tusky/adapter/MentionAutoCompleteAdapter.java, app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java, app/src/main/java/com/keylesspalace/tusky/db/TootDao.java, app/src/main/java/com/keylesspalace/tusky/db/TootEntity.java, app/src/main/java/com/keylesspalace/tusky/entity/Status.java, app/src/main/java/com/keylesspalace/tusky/fragment/ComposeOptionsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/java/com/keylesspalace/tusky/util/MediaUtils.java, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml
This fixes #417 and closes #440 and there's also a little bit of refactoring.
I actually did much more than I should have done first. I've tried saving ```Mention```s but turns out I didn't need them for this. It would be a good idea to save the toot we're replying to but the DB is not ready yet for such thing. So I've just added some fields and that's it.
I didn't understand the visibility logic first. I hope I didn't break anything.
I've tried to remove as much as possible from ```ComposeActivity``` because it's huge.
Sorry that it's all smashed together but it's mostly related things.
=> Save reply info in draft, refactor

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java, app/src/main/java/com/keylesspalace/tusky/LoginActivity.java, app/src/main/java/com/keylesspalace/tusky/NotificationPullJobCreator.java, app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java, app/src/main/java/com/keylesspalace/tusky/fragment/PreferencesFragment.java, app/src/main/java/com/keylesspalace/tusky/util/OkHttpUtils.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/http_proxy_preferences.xml, app/src/main/res/xml/preferences.xml
This change allows the user to manually enter an unauthenticated proxy
configuration to be used for all API connections. This is mainly
intended for using Tusky with Tor (via Orbot or a local proxy).
=> implement support for HTTP proxy

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java, app/src/main/java/com/keylesspalace/tusky/MainActivity.java, app/src/main/java/com/keylesspalace/tusky/NotificationPullJobCreator.java, app/src/main/java/com/keylesspalace/tusky/SplashActivity.java, app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt, app/src/main/java/com/keylesspalace/tusky/receiver/NotificationClearBroadcastReceiver.kt, app/src/main/java/com/keylesspalace/tusky/util/NotificationHelper.java
I started this because of https://github.com/Vavassor/Tusky/issues/518
Now notification polling is disabled correctly on Android O when notifications are disabled.
I think it would be even better to implement [NotificationListenerService](https://developer.android.com/reference/android/service/notification/NotificationListenerService.html) so the Pull jobs get correctly enabled/disabled when the settings change even if the user does not open the app afterwards. 
Some other changes: 
- I renamed `NotificationManager` because I think it is confusing to use the same name as a system service.
- I deleted the list update in `AccountManager.saveAccount`, because the saved objects are in the list in all cases anyway and it was causing a crash, probably due to concurrency.
=> notification improvements

app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rMO/strings.xml, app/src/main/res/values-zh-rSG/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
Although I tried by best to translate the strings manually to keep the readability, these translations still need to be improved, since I cannot test the translations on my phone and some terms in TW/HK may be not authentic...
It would be convenient for localization if Tusky has a functionality to load an external translation file to preview the result and switch between different languages. As far as I know, Telegram Android have this functionality. 😂 
Well it may be off the topic, but I did feel unnatural when I search in Tusky every time. It would be nice if Tusky could add a shortcut to [mastodonsearch](http://mastodonsearch.jp) in search menu... 😭
=> Add Chinese Translations

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java, app/src/main/res/layout/activity_compose.xml
Here are two smol fixes for the 'compose' screen.
* If you press the close or back button it checks if something is not empty and asks you in a dialog if you want to really close everything
* Focusing on the text field by default - because if you reply to a toot with a CW it focuses on a CW field by default.
I've also refactored one dialog listener and formatted things a little.
=> Compose close dialog + focus fix

app/src/main/java/com/keylesspalace/tusky/fragment/PreferencesFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/timeline_filter_preferences.xml
Mimics Mastodon web's functionality, but in a simpler form; a single regular expression is shared across the home, local and federated feeds. Even uses the exact same labels.
Strings are currently only provided in English and will need to be translated. Not sure what the current state of testing within the app is either, as the unit tests seem to fail for me, so I've included none here for now.
Fixes #555.
=> Add regular expression feed filtering

CONTRIBUTING.md, README.md
java becomes Java
english becomes English
Github becomes GitHub
Muti fixed to Multi
`- completely Open-source` changed to `- Completely open-source`
=> README and CONTRIBUTING capitalization and typo

app/src/main/res/values-de/strings.xml
Fixes #566.
Renames words with an inconsistent translation to the words used in the [Mastodon repo](https://github.com/tootsuite/mastodon/blob/master/config/locales/de.yml)
=> Make German translation more consistent

app/src/main/res/values-es/strings.xml
I kept more or less the same length as the original english translations so everything should fit, although I'm unable to test them at the moment.
For every string I wasn't sure how to translate I checked it against the web interface equivalent from mastodon.social
For every alert or information provided by the app I used a polite verb form, while keeping casual ones for interactions between users.
=> strings: Add spanish translations

app/src/main/java/com/keylesspalace/tusky/service/SendTootService.kt
would be good if somebody could test this before I merge it
fixes #589 
edit: here is the link to the apk download https://www.bitrise.io/artifact/5486423/p/bed75ffb8168425de2cd9d3d071d6af4
=> fix sending notifications (this time for reals)

app/src/main/AndroidManifest.xml, app/src/main/res/drawable-night/background_dialog_activity.xml, app/src/main/res/drawable/background_dialog_activity.xml, app/src/main/res/layout-w640dp/fragment_timeline.xml, app/src/main/res/layout-w640dp/fragment_view_thread.xml, app/src/main/res/layout/activity_compose.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/values-large/dimens.xml, app/src/main/res/values-large/styles.xml, app/src/main/res/values-night-v27/styles.xml, app/src/main/res/values-night/styles.xml, app/src/main/res/values-v27/styles.xml, app/src/main/res/values-w640dp/dimens.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml
resolves #421 
Step one: Show ComposeActivity as a dialog on tablets!
=> some Optimizations for tablets

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/util/NotificationHelper.java
Fixes notification display when display name contains RTL text, redux :duck: 
Before
After
=> Isolate usernames when formatting, to improve interaction of RTL usernames with LTR locales (and vice versa)

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
As per this stack trace
https://gist.github.com/connyduck/fec040ac63c3615f9ee8e6c0758686bc
it seems like we're trying to handle event after `onCreate` but before `onCreateView` and we don't have a kind at that moment of time yet. So it's hard to reproduce (and I didn't really but I had this crash I think) but I see no other reason.
=> Fix crash on receiving event in timeline

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java, app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt, app/src/main/java/com/keylesspalace/tusky/util/DownsizeImageTask.java, app/src/main/java/com/keylesspalace/tusky/util/MediaUtils.java, app/src/main/res/values/dimens.xml
This should fix OOMs when uploading images: Only sampled bitmaps are loaded into memory when creating thumbnails, so OOMs should be far less likely, and it will no longer crash in case there is still not enough memory.
Also fixes the problem where thumbnails were super blurry.
=> Improve media resizing

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
if we dont send the number of toots we want to get to the api, the check if we actually got that number does not work.
(Im pretty sure the timeline logic has some other problems as well, but this fixes this annoying problem at least most of the time)
=> fix bug where home timeline was never showing "load more" button

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
Seeing this crash in Play Store logs & getting it reported by multiple people. 
to reproduce, paste the following text into the compose TextEditor while custom emoji style is active, then add somemthing between the second emoji and the c -> 💥
> now Im sure that it's true 🎶
🎵cause think you're so good
and I'm nothing like you ✨
Its a platform bug, tracked by Google here: https://issuetracker.google.com/issues/67102093
Only crashes in production apk.
It does not crash anymore with this fix, I hope it doesnt have any side effects >_<
=> work around crash on Android 8

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/MainActivity.java, app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java, app/src/main/java/com/keylesspalace/tusky/db/AccountEntity.kt, app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt, app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java, app/src/main/java/com/keylesspalace/tusky/db/Converters.kt, app/src/main/java/com/keylesspalace/tusky/util/CustomEmojiHelper.java
closes #631
- this is now possible since my PR was merged https://github.com/mikepenz/MaterialDrawer/pull/2333
- I did not want to mess with the internals of the drawer, so I invalidate the whole header, as @C1710 suggested, works like a charm
- while measuring the perf impact this has, I found it is not much worse than before (some additional time spent in json de/serializing)
- but I found updating profile drawer info is quite expensive, so I made sure it is only updated once and not (2*number of profiles) times.
=> Custom emojis in drawer

app/build.gradle, app/proguard-rules.pro
This is a more aggressive proguard config than the default optimizing Android config. 
Specifically, it turns on the `code/simplification/arithmetic` optimization and makes one more pass.
Shrinks the apk about 15kb. I could not find any problems with this config, and I bet it feels a tad faster than before.
I will be deploying this to nightly and merge it if no problems occur.
=> add more aggressive proguard config

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
(I think the dialog needs some rework so the layout does not jump after the image is loaded.)
This fixes the crash and reduces the memory usage so its at least a first step. I think using the display size is the best option because it automatically takes all resolutions into account.
=> fix OOM crash when trying to caption large image

app/src/main/res/values-es/strings.xml
I made the original spanish translation months ago so there was plenty of new strings to translate. I added those.
I also changed a bit some others because the translated sentences ended being too large in spanish due to words being bigger and had to be cut down.
Per example:
"user favourited your toot"
was translated into:
"user marcó como favorito tu estado"
and didn't fit on the screen so I now changed it into:
"user marcó favorito"
Also I've seen a rise in the usage of other software server like Pleroma so I tried to avoid branding as much as possible and use "shared/repost" or "status/post" rather than "boosts" and "toots"
=> values-es: Update translations

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/PlaceholderViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/TimelineAdapter.java, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
There where two progressbars showing when the notification tab did its initial load.
I removed the progressbar of the footer.
Still missing - loading bar at the bottom when scrolling completely down
=> notification tab - fix progressbars of footer and fragment overlapping

app/src/main/java/com/keylesspalace/tusky/MainActivity.java
better fix than #778 
Theoretically it could still be possible that the network callback is faster than the EmojiCompat initialization, but I dont think thats gonna happen for real
=> wait for EmojiCompat to be initialized before using it

app/src/main/java/com/keylesspalace/tusky/MainActivity.java
closes #829 
not sure why this is happening, it may be a bug in the MaterialDrawer library. Now it works, although it is a small perf hit because of the additional `headerResult.clear();`
=> fix account switching when offline/error

app/src/main/java/com/keylesspalace/tusky/PreferencesActivity.java, app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/SearchResultsAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/ThreadAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/TimelineAdapter.java, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/SearchFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Add an option in the settings to show the absolute time of every user’s post on timeline instead of relative time, as there frequently happens time delay if we use current system depending on refresh time of the timeline. This PR is made for those users who want to know the time by the default time stamp.
Same as for now, we can use relative time displaying by disable this settings. See the attached image:
=> Show absolute time on timelines

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java, app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt, app/src/main/java/com/keylesspalace/tusky/network/ProgressRequestBody.java, app/src/main/java/com/keylesspalace/tusky/util/DownsizeImageTask.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-oc/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-ta/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rMO/strings.xml, app/src/main/res/values-zh-rSG/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Header images are now 1500x500 and video files can have up to 40MB.
TODO: We are loading the whole file into the memory when uploading, this needs to be fixed because otherwise a 40mb upload will throw out of memory most of the time.
=> update media limits for Mastodon 2.5

app/src/main/AndroidManifest.xml
regression from #842 - foreground services now require permission
=> fix crash when tooting on Android 9

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt, app/src/main/res/values-night/styles.xml
Just a minor fix to give the dialogs the theme color and not the default Android color. Looks way better imho.
=> style dark dialogs

app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.java
Works around #563 
Tested with known offenders
- https://cybre.space/@em/100805088534019375
- https://cybre.space/@chr/99821978136424081
The implementation isn't too elegant in reading-the-code terms, but I was pretty conscious about _every_ status going through this codepath, so I tried to keep iteration and allocation to an absolute minimum.
=> On android 6.0, filter 0x00ad (unicode soft hyphen) from statuses

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
https://github.com/tuskyapp/Tusky/blob/6cad8feea2f7c1abcb68ff0944c2571fa50c8627/app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java#L381-L384
onActivityCreated is called every time when switching tabs.
Since subscribe is called every time when switching tab, it gets timeline unnecessarily many times after toot.
=> Prevent multiple regist to eventHub on same TimelineFlagment

app/src/main/java/com/keylesspalace/tusky/entity/Status.kt, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
`status.getPinned()` generates NullPointerException when show menu of direct toot.
So I made a new method which returns only true or false.
https://github.com/accelforce/Tusky/blob/7e4798e2e37923afd90065cf186c397aa931c489/app/src/main/java/com/keylesspalace/tusky/entity/Status.kt#L105-L107
And changed not to show "Pin" option in direct toot's menu.
https://github.com/accelforce/Tusky/blob/7e4798e2e37923afd90065cf186c397aa931c489/app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java#L156-L163
=> Do not show "Pin" in "more" menu of direct status.

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.java
=> fix link's too large hitbox

app/src/main/java/com/keylesspalace/tusky/adapter/AccountFieldAdapter.kt, app/src/main/java/com/keylesspalace/tusky/entity/Account.kt, app/src/main/res/drawable/ic_check_circle.xml, app/src/main/res/layout/item_account_field.xml
=> add checkmark to verified links and better constraints to account fields

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.java
Fix #292 
The core of the functionality is here but there is still some bugs:
- Toots aren’t hidden by default even if they should be
- On timelines (it works on notifications mentions and threaded view), toots with clickable elements don’t hide (but somehow make a hide animation)
So it definitely looks like what I do in `StatusBaseViewHolder` is overridden under some conditions.
=> Display mentions toot hidden

app/src/main/res/layout/activity_about.xml, app/src/main/res/layout/activity_account.xml, app/src/main/res/layout/activity_license.xml
By making these changes, texts in relevant pages will appear currectly
in RTL layout.
=> Improve RTL support

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java
Closes #974 
Fixes a regression (probably from #954)
The `InputFilter` have to be set before any text or they don't work.
I also moved the code from `StatusBaseViewHolder` to `StatusViewHolder` as it is not used for detailed statuses which are always expanded.
=> fix long toots not collapsing correctly in timelines

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
When a user logs in, the `AccountEntity` object does not have a username or id when creating fragments because the network request has not returned yet -> the wrong more menu will be shown & replies will contain the own username. Fixed by deferring the loading of the username and id in `SFragment`.
Annoys me as hell, but real users probably don't log in as often as i do :)
=> fix mentions and more menu after a fresh login

app/src/main/java/com/keylesspalace/tusky/MainActivity.java, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java, app/src/main/res/menu/status_more.xml, app/src/main/res/menu/status_more_for_user.xml, app/src/main/res/values/strings.xml
Adds a context action to open statuses as a different account.
if the user only has one account registered, the action is hidden.
If the user has exactly two accounts, the action is presented as "Open as @You@YourOtherInstance".
If the user has more than two accounts, the action is presented as "Open as …", and the user gets a list popup.
=> Implement "Open status as (another account)" #958

app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt
closes #990 
Note that the `(autoGenerate = true)` could now be removed from `AccountEntity.id`, but I am leaving it so we don't have to do another database migration.
=> Never use 0 account ids to prevent caching problems

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/db/TimelineDao.kt, app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt, app/src/main/java/com/keylesspalace/tusky/di/RepositoryModule.kt, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/repository/TimelineRepository.kt, app/src/main/java/com/keylesspalace/tusky/util/HtmlConverter.kt, app/src/main/java/com/keylesspalace/tusky/util/StringUtils.kt, app/src/test/java/android/text/FakeSpannableString.kt, app/src/test/java/com/keylesspalace/tusky/StringUtilsTest.kt, app/src/test/java/com/keylesspalace/tusky/fragment/TimelineRepositoryTest.kt
Fix #1022 
It *seems* to be working but I've made so many stupid errors before and while fixing it now that I'm not sure about anything anymore. I want to write some tests for that but I'm not sure when I'll do it. I would appreciate if someone else tried it out before merging.
=> Fix incorrectly incrementing IDs before sending to server.

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/fragment/AccountMediaFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt, app/src/main/res/values/integers.xml
this is a fix for the following error on oneplus one with lineageos, viewing large photos uploaded to Pleroma
```
W OpenGLRenderer: Bitmap too large to be uploaded into a texture (4160x3120, max=4096x4096)
W OpenGLRenderer: Shape too large to be rendered into a texture (4172x3132, max=4096x4096)
W OpenGLRenderer: Bitmap too large to be uploaded into a texture (4160x3120, max=4096x4096)
```
there are still some errors in the log, but the images show OK.
- `E/BufferItemConsumer: [unnamed-4641-1] Failed to release buffer: Unknown error -1 (1)`
- `W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE`
this *might* break true animated gifs (i.e. not mastodon video gifs). I'm not at all sure if they worked before, but they certainly don't now.
the size is 1920 because 1920x1080 …
=> Fix large image attachments not showing

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
Steps to reproduce: see a reblog in the timeline, open it. Click "open in browser" in the menu -> crash
=> fix crash when opening a thread in the browser

app/src/main/java/com/keylesspalace/tusky/fragment/AccountListFragment.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.java
Steps to reproduce: Go on a slow internet connection. Open and close one of the `AccountListFragment`s very fast. If the network request returns after the Fragment was closed, it crashed.
```
java.lang.NullPointerException: 
at com.keylesspalace.tusky.util.ViewExtensionsKt.show (ViewExtensionsKt.java:6)
at com.keylesspalace.tusky.fragment.AccountListFragment.onFetchAccountsFailure (AccountListFragment.java:327)
```
I moved the api requests to `Single`s, because if they get cancelled the callback is not invoked so it does not crash anymore. With the `callList` the error callback was invoked when cancelled.
This is the only crash I could find in Google Play for Tusky 5.0 beta 1.
=> fix crash in AccountListFragment

app/src/main/java/com/keylesspalace/tusky/ReportActivity.java, app/src/main/java/com/keylesspalace/tusky/SavedTootActivity.java, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/AccountListFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/res/drawable/report_status_divider_dark.xml, app/src/main/res/drawable/report_status_divider_light.xml, app/src/main/res/layout/item_status_detailed.xml, app/src/main/res/values-night/styles.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
Turns out `DividerItemDecoration` has built in support for theming, no need to roll our own :D 
I also deleted the special handling for `ReportActivity`, since it will be redesigned for Tusky 6 anyway #971
=> remove unnecessary divider styling

app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt
FIxes a missing `centerInside()` in `ViewImageFragment`. Because of that some images were not resized correctly. @mal0ki send me an example but it's non-shareable so I've managed to make another one (it was trickier than I expected): https://birb.site/@charlag/101648643731741697
cc @MightyPork
=> Fix resizing image uniformly when opening an image

app/src/main/res/values-de/strings.xml
The German version of the web UI has a new placeholder since a couple of versions of Mastodon.
=> Made compose field on par with web UI

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
Steps to reproduce: Go to a profile where the user has pinned tabs. Mute the user. Crash because `removeAllByAccountId` got called in a timeline where all posts are from one user.
=> fix crash in TimelineFragment

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
A try to fix this mysterious crash I keep seeing in Google Play crash reports. 
https://gist.github.com/connyduck/bdf1c765fbdd526e590c4ef390948f23
Its only on Android 8 and the approach is to just not override this method anymore.
=> fix crash in account activity

app/src/main/java/com/keylesspalace/tusky/receiver/SendStatusBroadcastReceiver.kt
`android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag.`
=> Fix crash on Android 9 when replying from notification

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt
#1012 hardcoded visibility level when answering from a toot displayed in the DM column to `private` but direct messages have the visibility level `direct`, so this PR corrects the value.
Also, since people can post by mistake to their followers instead of directly, I think you should consider releasing a minor version of Tusky containing this fix.
=> Fix visibility of answer from DM column, from private to direct

app/src/main/java/com/keylesspalace/tusky/MainActivity.java
Steps to reproduce: Be not logged into Tusky. Share something to Tusky. Crash.
Expected behavior: After sharing user sees the login screen.
=> Fix crash when sharing to Tusky while not logged in

build.gradle
Supporting the latest stable version of Android Studio
https://androidstudio.googleblog.com/2019/03/android-studio-332-available.html
=> Update Android Gradle plugin to 3.3.2

app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt
- Open media view for an image
- Click share button in the toolbar
Behavior before PR: NPE
Behavior after PR: Share sheet opens as expected
=> Fix unhandled NPE when sharing an image from ViewMediaActivity

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java, app/src/main/java/com/keylesspalace/tusky/PreferencesActivity.kt, app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java, app/src/main/java/com/keylesspalace/tusky/fragment/preference/PreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/util/LocaleManager.kt, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Fix #644 
I mostly followed [this tutorial](https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758), adapting it to Tusky.
* Use default system language or any language added to Tusky (language list is static and needs to be updated when a new translation is added, but it is the simpler way)
* Language change immediately, similarly to theme change but with a bit more code here and there to correctly update locale.
* Works with locales that are more than two letters (e.g. `pt-rBR` or `zh-rTW`).
Possible changes, based on your feedback:
* I hardcoded the current locales in `donottranslate.xml`, because it is the simplest yet clean solution. See [here](https://stackoverflow.com/questions/11611065/get-the-applications-resources-languages) for other ways …
=> Add support for language switching

app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
Have the default tab setup. Go to Account Settings -> Tabs. Go back. After a short time, crash.
<details>
```
java.lang.ArrayIndexOutOfBoundsException: length=33; index=-1
at java.util.ArrayList.get(ArrayList.java:439)
at com.keylesspalace.tusky.util.PairedList.get(PairedList.java:53)
at com.keylesspalace.tusky.fragment.NotificationsFragment.addItems(NotificationsFragment.java:818)
at com.keylesspalace.tusky.fragment.NotificationsFragment.onFetchNotificationsSuccess(NotificationsFragment.java:705)
at com.keylesspalace.tusky.fragment.NotificationsFragment.access$400(NotificationsFragment.java:93)
at com.keylesspalace.tusky.fragment.NotificationsFragment$4.onResponse(NotificationsFragment.java:665)
at …
```
=> fix crash in NotificationsFragment

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/entity/Notification.kt, app/src/main/java/com/keylesspalace/tusky/json/NotificationTypeAdapter.kt, app/src/main/java/com/keylesspalace/tusky/viewdata/NotificationViewData.java
Fix part of #1102 .
If there's "Your poll has ended." notification in user's notification list, app crashes.
This is a fatal problem because once app started to crash, we can't even switch account.
So I fixed not to crash app for now.
=> Fix crash with unknown notification type

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/TimelineAdapter.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
tuskyapp/Tusky#452
This pull request doesn't add the "update a timestamp" on refresh, but it adds "update timestamp" every minute.
The main idea is to send the notifyItemRangeChanged to the adapter with a payload.
Viewholder checks if payload exists and if so - it updates only the fields specified at the payload (creation timestamp for now). If payloads are empty - adapter works just like before.
=> Refresh message timestamp every minute

app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt
Thats what I meant, sorry for not explaining it better @charlag 
It should be slightly more efficient
=> ListsActivity: create IconicsDrawable with right color instead of tinting it later

app/src/main/java/com/keylesspalace/tusky/TabData.kt, app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt, app/src/main/java/com/keylesspalace/tusky/adapter/TabAdapter.kt, app/src/main/java/com/keylesspalace/tusky/db/Converters.kt, app/src/main/java/com/keylesspalace/tusky/pager/MainPagerAdapter.kt, app/src/main/java/com/keylesspalace/tusky/util/ViewExtensions.kt, app/src/main/res/drawable-v26/ic_edit_chip.xml, app/src/main/res/drawable/ic_edit_chip.xml, app/src/main/res/drawable/ic_hashtag.xml, app/src/main/res/layout/item_tab_preference.xml, app/src/main/res/values/strings.xml
- For now, supporting only one hashtag. But datastructure and layout is ready for multiple hashtags. I think we need to use the search endpoint with pagination for multiple hashtags.
- there can be multiple hashtag tabs, as opposed to the other tab types
=> add hashtag tabs

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
Issue #452 
Refresh items timestamp at the Notification fragment with 1 minute interval.
Implemented the same logic as at the pull request #1113
=> Update Notification Adapter to support status created timestamp refresh

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
happens, for example, when the instance is on a mastodon version that does not support filters yet
cc @Tak
=> fix crash when filter request returns an error

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
It was failing for "whole-word" filters where the beginning or end of the filter was a non-word character, e.g. `#meh`, because the word-boundary class doesn't match for two adjacent non-word characters.
I thought this was too straightforward to warrant test coverage; looks like the joke's on me. I'll add some in a followup PR.
=> Fix word boundary detection in filters

app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt
I was sure I checked this when I wrote it, but apparently not ¯\\\_(ツ)_/¯
=> prevent empty hashtag in TabPreferenceActivity

app/build.gradle
The dynamic language switching is not working with apks downloaded from Google Play because Play does not deliver all languages in the split apks. 
There are 2 ways of fixing that: https://stackoverflow.com/questions/52731670/android-app-bundle-with-in-app-locale-change
I don't want to use this PlayCore API as it seems to be proprietary, so lets go with this.
=> disable language splitting for app bundle builds

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
bug report: https://github.com/tuskyapp/Tusky/pull/1130#issuecomment-477482909 thx @kyori19 
Im not sure it is actually caused by #1130, it probably just made the bug appear more often.
Removing the `fit()` fixes the problem. The weird thing was that only the notification icon was wrong - so it had to have something to do with Picasso. If it was a recycling issue more stuff would have been wrong.
=> Fix wrong notification avatar being displayed sometimes

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java, app/src/main/res/drawable/ic_cw_24dp.xml, app/src/main/res/layout/activity_compose.xml
> **Disclaimer**: this needs to be tested, since I haven't touched Android development (with all its things) for years.
In short: I don't like "CW" text in toot compose screen, since it _has_ to be translated and there's no space for 3+ characters. I went to https://ionicons.com, grabbed "Warning" icon (AFAIK they are under MIT Licence, so I can do that) and placed instead of "CW" text.
Screenshot:
=> Added "Warning" icon instead of "CW" text.

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/java/com/keylesspalace/tusky/util/PairedList.java
seeing these crashes a lot in the Play Console. No idea how to reproduce yet.
https://gist.github.com/connyduck/d82782aa502bbd997782ad3db4c9d3b0
https://gist.github.com/connyduck/eb4359c867760fe0244530027e6204f0
But seems the `ListStatusAccessibilityDelegate` actually expects nullable `StatusViewData`, so lets just give it what it wants.
=> fix IndexOutOfBoundException caused by ListStatusAccessibilityDelegate

app/src/main/java/com/keylesspalace/tusky/PreferencesActivity.kt, app/src/main/java/com/keylesspalace/tusky/adapter/AccountViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java, app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.java, app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.java, app/src/main/res/drawable/ic_bot_24dp.xml, app/src/main/res/layout/item_account.xml, app/src/main/res/layout/item_conversation.xml, app/src/main/res/layout/item_status.xml, app/src/main/res/layout/item_status_detailed.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
I saw this suggestion fly past on the federated timeline and already lost it. :grinning: 
The best "bot" icon I found is the android logo, but I guess that's not ok for trademark reasons...
=> Add bot indicator overlay to avatars

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
I'd like to fix #1192 myself. 
I'm not sure though whether my approach is the best one. 
There's a dedicated `calculateTextLength()` function, maybe I should change it to:
```java
int calculateTextLength() {
String composeText = textEditor.getText().toString();  // NEW
if (composeText.trim().length() <= 0)                  // NEW
return 0;                                          // NEW
int offset = 0;
URLSpan[] urlSpans = textEditor.getUrls();
if (urlSpans != null) {
for (URLSpan span : urlSpans) {
offset += Math.max(0, span.getURL().length() - MAXIMUM_URL_LENGTH);
}
}
int length = textEditor.length() - offset;
if (statusHideText) {
length += contentWarningEditor.length();
}
return length;
}
```
=> Added check if text in compose toot field has only whitespaces

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
According to Google Play logs Tusky sometimes crashes with a `IllegalStateException` when sending a toot, this should fix it.
https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten
=> fix issue with foreground service on Oreo+

app/src/main/java/com/keylesspalace/tusky/util/ListStatusAccessibilityDelegate.kt
and accessibility service is active
Pleroma allows attaching more than 4 images -> `IndexOutOfBoundsException`
=> fix crash when status has more than 4 images

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java, app/src/main/java/com/keylesspalace/tusky/SavedTootActivity.java, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt, app/src/main/java/com/keylesspalace/tusky/db/Converters.kt, app/src/main/java/com/keylesspalace/tusky/entity/Status.kt, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java, app/src/main/java/com/keylesspalace/tusky/repository/TimelineRepository.kt, app/src/main/res/menu/status_more_for_user.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/fragment/TimelineRepositoryTest.kt
Close #705 
Cherry-picked some changes to ComposeActivity from #1004 because it's needed for uploaded media support.
As I mentioned at #1171, this PR contains supports for uploaded medias and mentions to remote instances.
=> Implement redraft feature.

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
similar to #1199, but not as obvious (the background of the bot overlay is shown behind the small avatar)
cc @Tak
=> fix another issue with avatar background recycling

app/src/main/java/com/keylesspalace/tusky/MainActivity.java, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.java, app/src/main/java/com/keylesspalace/tusky/viewmodel/EditProfileViewModel.kt
Steps to reproduce: Switch between accounts quickly on a slow internet connection -> crash
Apparently glide does not like to be called on a destroyed activity, whereas Picasso did not care. Lets dispose the network calls correctly so this does no longer happen.
=> fix Glide crash in MainActivity

app/build.gradle, app/src/androidTest/java/com/keylesspalace/tusky/MigrationsTest.kt, app/src/androidTest/java/com/keylesspalace/tusky/TimelineDAOTest.kt, app/src/main/java/com/keylesspalace/tusky/db/TimelineDao.kt, app/src/main/java/com/keylesspalace/tusky/repository/TimelineRepository.kt, app/src/test/java/com/keylesspalace/tusky/fragment/TimelineRepositoryTest.kt
Steps to reproduce: Have a deleted status as the second status in you timeline. Switch accounts (or restart Tusky), notice how it disappears when the timeline is reloaded. Switch again, the toot appears and disappears again.
This PR fixes the problem by deleting the whole range of loaded status instead of only relying on `onConflict = REPLACE`
Not 100% sure this is the correct approach, but it seems to work. Will do more testing tomorrow.
this is part 1/x of fixes to the timeline glitches
=> fix deleted status reappearing in the timeline

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/res/layout/item_conversation.xml, app/src/main/res/layout/item_status.xml, app/src/main/res/layout/item_status_detailed.xml
This is missing for the polls. I won't include it in Tusky 7 though, because I want to make sure `EmojiCompat.get()` works as expected on the nightly first.
=> support custom emoji fonts in poll options

app/src/main/java/com/keylesspalace/tusky/view/MediaPreviewImageView.kt
Apparently Glide calls the `RequestListener` before it sets the image (Picasso did it the other way), so the first calculation of the matrix gets the wrong size of the drawable and nothing is displayed. This should fix the problem.
Closes #1255
=> fix images with focal point not shown in timeline

app/src/main/java/com/keylesspalace/tusky/adapter/SearchResultsAdapter.java, app/src/main/java/com/keylesspalace/tusky/fragment/SearchFragment.kt
this fixes the crash you reported @BoFFire @nailyk-fr 
Steps to reproduce: have a status with content warning in search results, toggle the button twice.
Or have a search that finds a status with long content that would be collapsible, immediate crash when search results return
<details>
<summary>stacktrace</summary>
```
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{3eefc66b VFED.... ......ID 0,0-540,766 #7f09020d app:id/searchRecyclerView}, adapter:com.keylesspalace.tusky.adapter.SearchResultsAdapter@3c4e45c8, layout:androidx.recyclerview.widget.LinearLayoutManager@746d661, context:com.keylesspalace.tusky.SearchActivity@23e90b8
at …
```
=> fix crash in SearchFragment

app/src/main/res/drawable/background_main_toolbar.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/values-night/styles.xml, app/src/main/res/values/styles.xml
In #1263 I removed the `colorSurface` because it made the main toolbar look ugly. Turns out it is needed for the color of drop downs. 
here is the code change that causes the problem: https://github.com/material-components/material-components-android/commit/6d4ffa29e3b9476352273b42dbdd16077eb88dc9
So my workaround is using a shape drawable instead of a color drawable. Once the materialcomponents are stable I will do a proper refactoring.
=> fix upgrade of material lib

app/src/main/java/com/keylesspalace/tusky/di/NetworkModule.kt, app/src/main/res/layout-sw640dp/fragment_timeline_notifications.xml, app/src/main/res/layout/fragment_timeline_notifications.xml
- Remove two layouts to make it more efficient
- The button bar is slightly smaller now. A lot of users requested that, but I would not make it too small so the buttons are still easy to touch.
cc @pandasoft0
=> improve notification fragment layout

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-eo/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-no-rNB/strings.xml, app/src/main/res/values-oc/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rMO/strings.xml, app/src/main/res/values-zh-rSG/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml
This is a minimal fix for #1287. Notifications are still not announced correctly and I didn't add any special actions for polls so one may have to scroll through them manually. I think they're rare enough that it's not a big problem yet.
I checked `description_status` in all languages and it's either left as-is (even in Asian languages) or not translated at all. So I've made it non-translatable.
=> Minimal screen reader support for polls

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java, app/src/main/java/com/keylesspalace/tusky/MainActivity.java
https://twingyeo.kr/@cheesekun/102184993516052526
sorry for my bad english > <);
=> improve usability: add shortcuts for compose/send new toot [#505]

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
Filters were not applied to boosted statuses in timelines. This fixes the problem.
cc @Tak
=> apply filters to boosted statuses

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt, app/src/main/java/com/keylesspalace/tusky/entity/Attachment.kt, app/src/main/java/com/keylesspalace/tusky/entity/MastoList.kt, app/src/main/java/com/keylesspalace/tusky/entity/Status.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.java, app/src/main/java/com/keylesspalace/tusky/repository/TimelineRepository.kt, app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.java, app/src/main/java/com/keylesspalace/tusky/view/ConversationLineItemDecoration.kt, app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/fragment/TimelineRepositoryTest.kt
At first, I just wanted to cleanup the entitiy classes
- `var` -> `val` where possible
- use data classes
- remove unused attributes
- fix nullability
But then I found that since Mastodon 2.6 every status has the Card already embedded so there is no need for that extra request in `ViewThreadFragment`.
Also fixes the problem that avatars where never animated in `ViewThreadFragment`
=> cleanup entity classes and ViewThreadFragment

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
The account name was not correctly emojified when scrolled up in AccountActivity
=> correctly emojify account name in AccountActivity

app/proguard-rules.pro
Seems R8 is optimizing away too much and the AsyncTask was missing methods. This also explains why it worked in a debug build.
cc @C1710
=> fix R8 rules to avoid crash when downloading Emoji Font

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
Since #1296 merged, back button is not working in `ComposeActivity`.
This PR fixes it.
=> Fix back button not working

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
Save current sensitivity state before force switch it to true and restore when switch content sensitivity to false
tuskyapp/Tusky#1217
=> Fix issue with wrong sensitive status

app/src/main/java/com/keylesspalace/tusky/LoginActivity.kt, app/src/main/java/com/keylesspalace/tusky/util/RickRoll.kt, app/src/main/res/values/donottranslate.xml, app/src/test/java/com/keylesspalace/tusky/util/RickRollTest.kt
idea shamelessly stolen from @NicolasConstant's [implementation of this for sengi](https://mastodon.social/@sengi_app/102194358508642906)
=> rick roll instead of logging in on selected domains

app/src/main/res/layout/activity_main.xml
before
after
(the `tabMaxWidth="0dp"` is doing the trick, the other changes are just cleanup)
=> fix main tabs on tablet

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java
Currently, we only remove boosted statuses when the user that boosted the status gets blocked/muted. This PR makes sure statuses will also get removed when the original author gets muted or blocked.
=> Remove boosted status when the original author was blocked or muted

app/src/main/java/com/keylesspalace/tusky/FiltersActivity.kt, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-bn-rIN/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-no-rNB/strings.xml, app/src/main/res/values-oc/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
These warnings were occuring on every build, this PR fixes them
`w: /Users/connyduck/Documents/AndroidApps/Tusky/app/src/main/java/com/keylesspalace/tusky/FiltersActivity.kt: (178, 24): Parameter 'v' is never used`
`warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?`
```
/Users/connyduck/Documents/AndroidApps/Tusky/app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java:800: warning: non-varargs call of varargs method with inexact argument type for last parameter;
return context.getString(R.string.description_poll, args);
^
cast to Object for a varargs call
cast to Object[] for a non-varargs call and to suppress this warning
```
=> Fix build warnings

app/src/main/java/com/keylesspalace/tusky/SplashActivity.kt, app/src/main/res/values-v27/styles.xml, app/src/main/res/values/styles.xml
The LoginActivity was started twice when opening the app while not being logged in because both the BaseActivity and the SplashActivity were redirecting. I only noticed because I pressed back to close the app and there was another login.
=> fix LoginActivity created twice on unauthenticated appstart

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.java
Looks like Plume(?) created statuses with broken mentions that make Tusky crash. This fixes the problem.
Here is the part of the json of the offending status, as returned by my instance chaos.social, note how the `href` part makes no sense at all
```
"content":"\u003cp\u003e\u003ca href=\"/@/0x1C3B00DA/\" rel=\"nofollow noopener\" target=\"_blank\"\u003e@0x1C3B00DA\u003c/a\u003e Blockquotes are supported, it just that they don't have a specific style (only a little margin on the left side), and your Pleroma account is available at https://baptiste.gelez.xyz/\u003ca href=\"/@//\" rel=\"nofollow noopener\" target=\"_blank\"\u003e@\u003c/a\u003e/0x1C3B00DA\u003ca href=\"/@/edolas.world/\" rel=\"nofollow noopener\" target=\"_blank\"\u003e@edolas.world\u003c/a\u003e/ the link in the article is …
```
=> fix crash caused by broken mention

app/src/main/res/values-en-rGB/strings.xml, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml
closes https://github.com/tuskyapp/Tusky/issues/1346
I first tried having british as the default and overriding with `en-rUS`, but that did not work, my device always showed American, no matter the settings, so i now did it the other way round
=> add support for american/british english translations

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
Basically this happened when the relationship call returned before the account call and the menu was updated without having the account data. Fixed by also updating the menu when the account info arrives.
cc @Tak
=> fix mute action not being correctly displayed

app/src/main/java/com/keylesspalace/tusky/view/BezelImageView.java, app/src/main/res/drawable/materialdrawer_shape_large.xml, app/src/main/res/drawable/materialdrawer_shape_small.xml, app/src/main/res/layout/material_drawer_header.xml, app/src/main/res/values/styles.xml
So we finally have our trademark rounded squares with radius 1/8 of size everywhere.
This is a little bit hacky, but definitely easier than forking the MaterialDrawer library.
I added some comments, so I hope it is clear how it works.
=> make avatar images in drawer rounded squares

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.java
We show mentions even when a CW is collapsed, but they were not always clickable
=> fix mentions outside of content warnings not being clickable

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
So when pulling-to-refresh not all timestamps are updated in the NotificationsAdapter because of a small bug that causes the change payload being ignored.
=> fix timestamp not updating in notifications

app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewMediaFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt, app/src/main/java/com/keylesspalace/tusky/pager/AvatarImagePagerAdapter.kt, app/src/main/java/com/keylesspalace/tusky/pager/ImagePagerAdapter.kt, app/src/main/java/com/keylesspalace/tusky/repository/TimelineRepository.kt
It's not really finished yet but I want to ask for feedback.
Basically when the full image is not in cache, it tried out preview from cache and then loads the complete image.
There are couple of things:
1. Maybe progress bar on top would work better then. We could even show progress but we need to play a little with OkHttp: https://learnpainless.com/android/show-progress-while-loading-images-with-glide
2. I've tried to do the same with video but... let's say it wasn't really successful
=> Use cached preview as thumbnail in ViewImageFragment, fix #1267

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
cc @Tak 
<details>
```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7753)
at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1225)
at android.view.View.requestLayout(View.java:23093)
at android.view.View.requestLayout(View.java:23093)
at android.view.View.requestLayout(View.java:23093)
at android.view.View.requestLayout(View.java:23093)
at android.view.View.requestLayout(View.java:23093)
at android.view.View.requestLayout(View.java:23093)
at android.view.View.requestLayout(View.java:23093)
at android.view.View.requestLayout(View.java:23093)
at android.widget.TextView.checkForRelayout(TextView.java:8908) …
```
=> fix CalledFromWrongThreadException in ComposeActivity

app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt, app/src/main/java/com/keylesspalace/tusky/pager/ImagePagerAdapter.kt
Follow up for #1344 
After few hours of fiddling with it, it seems to finally work now. Images transition, don't jump around when touched, avatars open and so on.
At least one of the problems was that we've been waiting for the transition when we shouldn't (for 3rd and 4th images when you open the 1st one e.g.). Another problem is that we really, really need `attacher.update()` for some reason. Third problem is that after loading Glide resets the image and it could happen when we already set thumbnail...
So, a lot of races. Hopefully it's more reliable now.
I've also noticed that exit transitions don't work for images other than the one you've opened. We could look into that in the future.
=> Fix image viewer & transitions

app/src/main/java/com/keylesspalace/tusky/adapter/AddPollOptionsAdapter.kt, app/src/main/java/com/keylesspalace/tusky/view/AddPollDialog.kt
Fixes the following bug: Fill in options -> button enabled, add empty option -> button disabled, delete empty option again -> button still disabled while it should be enabled
thx @MasterGroosha for reporting
=> fix poll validation

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/entity/DeletedStatus.kt, app/src/main/java/com/keylesspalace/tusky/entity/Status.kt, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.java, app/src/main/java/com/keylesspalace/tusky/network/TimelineCases.kt
ref https://github.com/tootsuite/mastodon/pull/10669
fixes bugs with delete&redraft where mentions are lost
=> use status source for delete and redraft

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
This happens when two requests (the initial one and another from swipe to refresh) are active + one succeeds and one fails. Fixed by disabling swipe to refresh while loading.
=> fix error and content overlapping in NotificationsFragment

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java
I have no idea where null `createdAt` is coming from, but I see it in the crashlogs of the beta. So lets revert the change.
=> Fix crash when status date is null

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
Lets not allocate a whole `ArrayList` if its this easily avoidable.
=> Use singletonList in getChangePayload

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt, app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt, app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt, app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java, app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/instancemute/fragment/InstanceListFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/AccountListFragment.kt
They renamed the extension function from `autoDisposable` to `autoDispose`
=> upgrade autodispose

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
When `TimelineFragment` is created, it makes two requests to the server: One to refresh cached statuses, one to load new ones. When the timeline is empty (e.g. when first logging in and nothing is cached) the request to refresh cached statuses is redundant, so lets remove it.
=> remove redundant request when timeline is empty

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
https://social.diskseven.com/@Jo/102847053684897266
This only happens on a few of my devices, no idea what exactly is going on here, but this one line fixes the issue.
=> fix content warning edittext not losing focus when its hidden

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
Some posts (especially cross-posted ones) are marked as sensitive but have no CW. User cannot expand them and hear the full content.
=> Fix screen reader not announcing post content in some cases

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java, app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt
Because we migrated everything where this was used to RxJava it can now be removed, yeah
=> remove callList from BaseActivity

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
Noticed this warning in logcat:
`requestLayout() improperly called by com.google.android.material.appbar.CollapsingToolbarLayout{15ddc71f V.ED.... ......ID 0,0-540,568 #7f0900e4 app:id/collapsingToolbar} during layout: running second layout pass`
this fixes it
=> fix requestLayout() improperly called warning in AccountActivity

app/src/main/java/com/keylesspalace/tusky/util/ImageLoadingHelper.kt
Apparently there can be non-square avatars and Tusky displays them like so:
=> fix avatars with non-square aspect ratio display

README.md
[Mastodon no longer supports OStatus](https://blog.joinmastodon.org/2019/10/mastodon-3.0/#goodbye-ostatus-you-ve-been-deprecated) and is thus no longer GNU Social-compatible. Also fixed a minor grammatical quirk to make it a bit easier to understand.
=> Mastodon no longer supports OStatus

app/src/main/java/com/keylesspalace/tusky/components/search/SearchActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchAccountsAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchFragment.kt
Steps to reproduce: Open search, go to hashtags. Don't search anything, refresh. Hashtags for searchterm "null" will be displayed.
=> fix null search when refreshing hashtags

app/src/main/java/com/keylesspalace/tusky/ScheduledTootActivity.kt
Added forgotten onOptionsItemSelected, so toolbar back button does work again.
However, I would rather suggest move onOptionsItemSelected to BaseActivity.java and remove copypasted code from every activity that has toolbar with back button but it's not intuitive and theoretically may break unexpectedly.
=> ScheduledTootActivity: fix toolbar back button #1586

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/adapter/AccountFieldAdapter.kt, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/java/com/keylesspalace/tusky/entity/IdentityProof.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.java, app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountViewModel.kt
I don't know if `MediatorLiveData` is the way to go here... It causes more adapter updates than necessary, but works fine.
Other possibility would be to move this to Rx and zip the two network requests, have only one `LiveData` with a `Pair<Account, List<IdentityProofs>`.
Also, instead of `Either<IdentityProof, Field>` I could map the IdentityProofs to Fields 🤔 
Thoughts?
=> Implement identity proof api

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt
`tootVisibility` is not applied to `statusVisibility`
=> Fix ComposeOptions.visibility not applied

app/src/main/java/com/keylesspalace/tusky/SavedTootActivity.java, app/src/main/res/layout/activity_saved_toot.xml, app/src/main/res/values/strings.xml
Before:
After:
Inspired by Scheduled toot activity:
=> Display Elephant with better message in Drafts screen when there are none

app/src/main/java/com/keylesspalace/tusky/components/search/SearchActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchAccountsAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchDataSource.kt, app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchDataSourceFactory.kt, app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchHashtagsAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchRepository.kt, app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchStatusesAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt
This PR
- fixes toggling media hidden state (was broken because differ received the same list again)
- fixes bookmarking in search (copy/paste mistake)
- cleans up the code a bit (actually it is already quite good compared to Java code we have in the project)
There is another bug that I did not fix because it seems to only appear on emulators: 
- when using the emulator hardware keyboard, search is triggered twice, which messes with the cache and statuses randomly appear, see https://stackoverflow.com/questions/12929590/search-widget-call-onnewintent-twice
=> Fix search bugs

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt
This seems to have regressed with the `ComposeActivity` refactor - if you reply to a post with a content warning, the CW is carried over to the reply, but the content warning toggle in the newly-created compose activity isn't activated.
The proposed fix sets `showContentWarning` in the view model when it's set up with a nonnull CW.
The `setupComplete` roundtrip is there because the event for showing the content warning is dispatched _after_ the activity creation finishes, so without it, the focus is incorrectly set to the CW field.
=> Retain content warning when replying to a CWed post

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
Pull to refresh on the notifications tab while offline. The second pull will load forever because `if(fetchEnd == FetchEnd.TOP && topLoading) { return; }` and `topLoading` is not reset in the error callback.
Closes #1637
=> fix notification refresh

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
This is a regression from e5b78f65cf61f3ded18f2ded93cd57b8c0af42c9
=> Fix setting text to CW button in fav/reblog notification. Fix #1641

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
At first I thought that there will be problems with sizing. Then I thought it's new behaviour that the dialog consumes the full height.
I think it just... works? If it works like it is, it will be probably the highest "changes to usefulness ratio" I contributed lol.
=> Enable zooming and panning in the CaptionDialog

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt
- Open empty ComposeActivity
- add a content warning
- close the activity with the x button
```
kotlin.KotlinNullPointerException: 
at com.keylesspalace.tusky.components.compose.ComposeViewModel.didChange
(ComposeViewModel.java:194)
```
=> fix crash when closing ComposeActivity

app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java
Regression from https://github.com/tuskyapp/Tusky/pull/1627
(when the buttons in the timeline where `ToggleButton`s, their callback where called when changing their state from code and the reveal button would update)
=> fix reveal button not updating in ViewThreadActivity

app/src/main/java/com/keylesspalace/tusky/pager/AccountPagerAdapter.kt, app/src/main/java/com/keylesspalace/tusky/pager/MainPagerAdapter.kt, app/src/main/java/com/keylesspalace/tusky/util/CustomFragmentStateAdapter.kt
Steps to reproduce: Enable "Don't keep activities" in the developer settings and bring the main activity in the background and foreground again (or recreate it in an other way). Jumping to the top by clicking the selected tab will no longer work.
=> fix FragmentAdapter returning null fragments when activity was recreated

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsViewModel.kt
It was crashing Tusky. Since the conversation API is annoying, the only way to properly update the DM column is to refresh it.
Note that composing a new DM or responding to one doesn’t update the DM column, it probably should?
=> Refresh DM column when removing toot there instead of removing conversation

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/res/layout/activity_compose.xml
closes #1639 
The problem is that `updateSensitiveMediaToggle()` is called way to often and that messes with the `TransitionManager`. Fixed by reducing the number of calls to `updateSensitiveMediaToggle()` and using other transition mechanism.
=> fix overlapping icons in ComposeActivity

app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchDataSource.kt
... and use named params to avoid this mistake in the future :D 
thx @dansup for finding this bug
=> fix mixup of search params in SearchDataSource.loadRange

app/src/main/res/values/styles.xml
The color got lost somewhere in the refactoring. Its now the same as in Tusky 9 again.
=> change dialog background color

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
In #1643 we allowed zooming images. Unfortunately for the relatively small dialog default zoom levels are not very efficient. As @ismirth suggested in https://github.com/tuskyapp/Tusky/issues/1316#issuecomment-576444918 it might be not enough (I just tested it with one image and I increased zoom level multiple times).
=> Allow higher zooming levels for caption dialog images

app/src/main/res/layout-sw640dp/fragment_timeline.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_timeline_notifications.xml, app/src/main/res/values/dimens.xml
This seems to fix the "sensitive swiping" problem with the main tabs.
Also make the space between the pages visible again like it was in Tusky 9.
=> [Tusky10] increase tab page margin

app/src/main/res/drawable/status_divider.xml, app/src/main/res/values-night/theme_colors.xml, app/src/main/res/values-v27/styles.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/theme_colors.xml
This is based on feedback from beta users. I split up the poll background and status divider colors so they can be set individually. 
closes https://github.com/tuskyapp/Tusky/issues/1679
=> [Tusky10] adjust poll result background, status divider & button outline color

app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java
On `develop`, clicking "Show Less" in the thread view doesn't recollapse the content
(because the adapter never gets notified that the status view data has been updated after changing the expanded state)
=> Fix recollapsing expanded sensitive content in the thread view

app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/res/layout/fragment_accounts_in_list.xml, app/src/main/res/values/styles.xml
The param goes in the body as per api definition https://docs.joinmastodon.org/methods/timelines/lists/
The question is: Why did this work before?
=> fix list editing by moving account_ids from query to form param

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
closes https://github.com/tuskyapp/Tusky/issues/1682
tl;dr: combining `Glide` and `setImageDrawable` is a bad idea
=> fix image from another status showing up instead of blurhash

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/report/ReportActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportDoneFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportNoteFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/SearchActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchFragment.kt, app/src/main/res/layout/activity_account_list.xml, app/src/main/res/layout/activity_modal_timeline.xml, app/src/main/res/layout/activity_preferences.xml, app/src/main/res/layout/activity_statuslist.xml, app/src/main/res/layout/activity_view_tag.xml, app/src/main/res/layout/activity_view_thread.xml, gradle.properties
- Its now recommeded to use `FragmentContainerView` to host fragments 
- `ViewModelProviders.of` is deprecated
- Dagger migrated to AndroidX so the flags in `build.gradle` are no longer needed
=> Upgrade deps

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/view/BackgroundMessageView.kt, app/src/main/res/layout/activity_lists.xml, app/src/main/res/layout/fragment_timeline.xml, app/src/main/res/layout/fragment_timeline_notifications.xml, app/src/main/res/layout/view_background_message.xml
I tried to fix it but not like proposed in #1618 because it would require additional layouts so I tried to just fit the Image.
The only problem is notifications screen where we have this damn bar. We need to offset top correctly and we need to fix the bar height for that but idk how it would work with text scaling.
=> Make image in BackgroundMessageView adapt to the height, fix #1618

app/src/main/java/com/keylesspalace/tusky/PreferencesActivity.kt, app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/TimelineAdapter.java, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/java/com/keylesspalace/tusky/util/CardViewMode.kt, app/src/main/java/com/keylesspalace/tusky/util/StatusDisplayOptions.kt, app/src/main/res/layout/item_status.xml, app/src/main/res/layout/item_status_detailed.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Addresses #1075
- Moved card setup to `StatusBaseViewHolder`
- Added user preference
- Added status display option for cards
- Tweaked fragments/adapters to set the status display option correctly based on the fragment purpose
=> Add option to show link previews in timelines

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/PreferencesActivity.kt, app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/TimelineAdapter.java, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/java/com/keylesspalace/tusky/util/StatusDisplayOptions.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Add an option to confirm reblogs.
Initially I wanted to put it much further the pipeline but to get animations work right I had to work around `SparkButton` a little bit. The advantage is that it's implemented in just one place now.
It tries to mimick Masto UI but not very closely.
=> Add options to confirm reblog/unreblog actions, close #460

app/src/main/java/com/keylesspalace/tusky/components/compose/view/ComposeScheduleView.java
DatePicker seems to think that it's in UTC. So setting selected time
might not work as aspect and receiving value from it might be in UTC
as well. This commit fixes the second issue by interpreting the date
as UTC date. Tested with America/New_York (GMT-5 at the moment) and
Russia/Kamchatka (GMT+12).
cc @Tak, @kyori19
=> Work around the bug in ComposeScheduleView, fix #1720

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt
Addresses the most critical part of #1725, and may also apply to #1721
=> Ensure media are marked sensitive any time there's a content warning

app/src/main/java/com/keylesspalace/tusky/adapter/PollAdapter.kt, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/entity/Poll.kt, app/src/main/java/com/keylesspalace/tusky/util/NotificationHelper.java, app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt, app/src/main/java/com/keylesspalace/tusky/viewdata/PollViewData.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/keylesspalace/tusky/FilterTest.kt
This makes a lot more sense for multiple choice polls and is how Mastodon Web handles it. Unfortunately Pleroma does not send the `voters_count` so I had to add a fallback.
=> use number of voters instead of votes to calculate poll results

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.java, app/src/main/java/com/keylesspalace/tusky/viewdata/NotificationViewData.java
closes https://github.com/tuskyapp/Tusky/issues/1753
I have no idea why `NotificationViewData` has an `expanded` attribute when its already in `StatusViewData`
=> fix content warning in notifications when alwaysShowSpoiler is on

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
closes #1648 
The problem is, that method is called twice for each keypress because we call it from a listener that listens to all events. I'm not 100% percent sure if that override would be necessary, but lets leave it in for now.
=> fix toot sending twice when using a hardware keyboard

app/src/main/res/layout/item_conversation.xml
=> fix ugly media previews in conversation tab

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/PreferencesActivity.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
close #1718
I don't like adding more knobs but I dislike having accessibility problems even more and I think it should probably be optional independent of sensitivity.
It's based on `mainactivity_kotlin` branch so I will have to rebase it later
=>  Add preference to disable swipe gesture for switching tabs

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/res/xml/preferences.xml
I think on per default makes more sense, because a accidental boost is worse than an annoying dialog.
=> fix confirmReblogs default values

app/src/main/java/com/keylesspalace/tusky/TuskyApplication.kt
So I learned that these weird crashes can not only occur because of missing error handlers (I think we caught them all), but also when using e.g. `zipWith` on network errors 🙄 ...
Lets fix them with a global error handler
https://medium.com/@bherbst/the-rxjava2-default-error-handler-e50e0cab6f9f
=> Fix RxJava UndeliverableException crashes

app/src/main/java/com/keylesspalace/tusky/util/SpanUtils.kt, app/src/test/java/com/keylesspalace/tusky/SpanUtilsTest.kt
Tag highlighting in ComposeActivity is not same as Mastodon does, so I fixed it.
I was also tried to fix mentions, but I don't know how to match to `[:word:]` by code point...
Before
After
Actual Behaviour
=> Fix tag highlighting in editor

app/src/main/res/layout/item_status.xml
Some of the lower components were vertically constrained to the toggle button and now need to be constrained to the card view
=> One more layout fix for length-collapsed posts with preview cards

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
Thus, if user accidentally will filter everything, they will be able to return to initial state.
Although, I'm wondering, does "Clear" button must be shown or greyed out as well if it's useless?
=> NotificationsFragment: show appbar if there is no notifications

app/src/main/java/com/keylesspalace/tusky/settings/SettingsDSL.kt
At some point settings DSL was refactored to first add a preference and
then run the builder. We shouldn't add a preference to the hierarchy
without setting a key for the preference first because preference gets
it's default value in `onAttachedToHierarchy()` and if the key is not set
then no default value will be set either.
This commit changes the order to execute builder (and set the key)
first and and preference to the point later.
thanks @MasterGroosha for the report
=> Fix settings default values for preferences

app/src/main/java/com/keylesspalace/tusky/util/BlurHashDecoder.kt
`Bitmap.setPixel` is rather expensive.
Thx @ignaciotcrespo for the idea.
I think we don't need to incorporate the caching from https://github.com/woltapp/blurhash/pull/66 as well.
=> speedup blurhash decoding by using a intermediate int array

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt, app/src/main/res/layout/fragment_view_image.xml
This commit does 3 things:
1. Replaces PhotoView (which is abandonware) with modern TouchImageView
2. Fixes an issue with panning images. Gesture was not intercepted
properly and pager was taking control instead of image being moved.
3. Adds feedback to dismissing of images with vertical gesture.
My other plans in this are include improve description view and making video view less wonky (eg it should not reset itself on screen rotation)
=> Improve image viewer

app/src/main/java/com/keylesspalace/tusky/adapter/BlocksAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/FollowRequestViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/adapter/MutesAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
Affects:
- New follower request and New follower notifications
- Accounts in Blocked users and Muted users pages
Action buttons, when present, still work.
=> Make account views clickable instead of avatar only

app/src/main/res/values/donottranslate.xml
We also have Ukrainian and Hindi as new languages, but they are translated <50% so I decided to not add them to the language selector
=> add Thai to the in-app language selector

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/adapter/MutesAdapter.java, app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/entity/Relationship.kt, app/src/main/java/com/keylesspalace/tusky/fragment/AccountListFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java, app/src/main/java/com/keylesspalace/tusky/interfaces/AccountActionListener.java, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/java/com/keylesspalace/tusky/network/TimelineCases.kt, app/src/main/java/com/keylesspalace/tusky/view/MuteAccountDialog.kt, app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountViewModel.kt, app/src/main/res/drawable/ic_notifications_off_24dp.xml, app/src/main/res/layout/dialog_mute_account.xml, app/src/main/res/layout/item_muted_user.xml, app/src/main/res/values/strings.xml
fix #484
Basically, what’s left to do is to find a way to retrieve the `mutingNotifications` state inside the Muted users page (`app/src/main/java/com/keylesspalace/tusky/adapter/MutesAdapter.java`). Since I don’t have a lot of experience with the Tusky codebase, I’m stuck at the moment.
=> Implement optional notifications muting for account muting

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt, app/src/main/res/layout/fragment_view_image.xml
This fixes crashes with images which were too wide (aspect ratio wise).
I've found out that there _is_ an option to prevent parent from scrolling and we have to write less brittle touch code. I left swipe gesture because I think it's nice.
Overall it's not as smooth as TouchImageView but the huge plus is that it should stop crashing (and I would be glad if anyone verified this)
=> Roll back image viewer but retain swiping fix

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledTootActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/AccountMediaFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/res/values/styles.xml
They added a new theme attribute for the background color of the progress indicator. I decided to switch to `colorSurface` as it makes it more visible. 
I don't understand why there is no attribute to set the color of the spinner inside as well.
=> upgrade SwipeRefreshLayout to 1.1.0

app/src/main/java/com/keylesspalace/tusky/fragment/preference/AccountPreferencesFragment.kt, app/src/main/res/drawable/ic_tabs.xml
I hear quite often that people do not realize that "Tabs" is clickable because it does not have an icon like the surrounding items. This icon is technically a "table row" item but I think it fits ok.
=> add icon for tabs preference

app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt, app/src/main/java/com/keylesspalace/tusky/adapter/TabAdapter.kt
There where 3 problems which led to weird glitches:
- Tabs were not saved after removing hashtags
- comparing tabs with equals is a bad idea, because they contain function types and there could be two distinct tabs with exactly the same configuration -> use the index instead
- when removing hashtag the wrong views got removed
=> fix various bugs when creating tab with multiple hashtags

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationFetcher.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationWorker.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/Notifier.kt, app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt, app/src/main/java/com/keylesspalace/tusky/entity/Marker.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
- Only fetch notifications up to the latest fetched one
- Use timeline markers to avoid showing already seen notifications
I extracted `NotificationsFetcher` to test notifications more easily: both manually (to not wait 15 minutes) and with unit tests. I didn't add unit tests yet but I extracted `Notifier` to do it more easily.
I tried out and vanilla Mastodon client updates markers for notifications on opening the client. Doesn't seem like it changes markers with websocket updates so I think it's pretty safe to skip notifications which should already have been seen.
=> Improve notifications fetching

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/res/layout/activity_compose.xml, app/src/main/res/values/colors.xml
Implements request by @Porrumentzio in #1943
The remaining character length indicator in the compose screen turns red when the message exceeds the limit.
=> Change characters left color to red when negative

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
Boosts aren't currently getting filters applied, because we're checking the content of the boost status instead of the content of the original status :facepalm:
=> Fix filtering of boosts

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/java/com/keylesspalace/tusky/entity/Card.kt
When blurhash is enabled in the user preferences:
- Adds a blurhash placeholder for card images
- Uses blurhash for card images when the user has disabled media preview download
- Uses blurhash for card images when the post is marked sensitive (mostly useful for posts originating from other fediverse software?)
=> Use blurhash for preview cards

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/entity/Card.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewMediaFragment.kt, app/src/main/java/com/keylesspalace/tusky/pager/SingleImagePagerAdapter.kt
When a preview card is of type `photo` and it has a nonempty `embed_url` entry, tapping the image portion of the card will open the embedded image in `ViewMediaActivity` instead of opening the main url in the browser. (The user can still open the main url in the browser by tapping the info portion of the preview card.)
See https://docs.joinmastodon.org/entities/card
=> Open photos embedded in preview cards in the image viewer

app/src/main/java/com/keylesspalace/tusky/SavedTootActivity.java, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledTootActivity.kt
This ensures that editing a scheduled toot will not duplicate it.
If the ID of a scheduled post is being passed to the compose activity, it will delete this scheduled post and create a new post with the same parameters.
Fixes #1924 
Deleting a toot and reposting it was the simplest way to accomplish this. There is a very slight chance of something going wrong in one of these two operations though. Alternatively, there is `PUT /scheduled_statuses/:id`, but it is not yet implemented in the app. Please let me know what you think about this, and if you need help with possibly implementing it.
=> Delete scheduled post after editing

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/test/java/com/keylesspalace/tusky/ComposeActivityTest.kt
Probably should have been part of #1744, I keep forgetting that we have a nice framework for testing `ComposeActivity` already
=> Add tests for compose activity initial state changes

app/src/main/java/com/keylesspalace/tusky/adapter/FollowRequestViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/adapter/FollowRequestsAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java, app/src/main/java/com/keylesspalace/tusky/util/StringUtils.kt, app/src/main/res/layout/item_follow_request_notification.xml
Fixes #1921 
I visually verified normal notifications and follow request notifications with the case in the issue report - I'm not sure if we have other test cases we need to verify.
Before
After
=> Perform bidirectionality isolation manually instead of relying on `BidiFormatter`

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
After finding out [here](https://social.randombits.host/web/statuses/105187994632656075) that you can get to a user profile by clicking their avatar and not their display name I felt dumb so I made this to have what I feel is the expected behavior of also going to a profile when you click the display name.
=> Adds link to account page when clicking on displayName

app/src/main/AndroidManifest.xml, app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/appstore/Events.kt, app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementsActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/di/ActivitiesModule.kt, app/src/main/java/com/keylesspalace/tusky/di/ViewModelFactory.kt, app/src/main/java/com/keylesspalace/tusky/entity/Announcement.kt, app/src/main/java/com/keylesspalace/tusky/entity/Emoji.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/java/com/keylesspalace/tusky/view/EmojiPicker.kt, app/src/main/res/drawable/ic_bullhorn_24dp.xml, app/src/main/res/layout/activity_announcements.xml, app/src/main/res/layout/activity_compose.xml, app/src/main/res/layout/item_announcement.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Closes #1693 
Drawer(with one unread announcement)
AnnouncementsActivity(with emoji picker opened)
=> [needs help] Support announcements

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
closes https://github.com/tuskyapp/Tusky/issues/1985
We cannot control when the `cancel` callback is called, and not cancelling would also be a bad idea, so I followed [this advice](https://github.com/bumptech/glide/issues/2690#issuecomment-349837873) in order to fix it.
=> fix crash when clearing glide requests

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/TuskyApplication.kt
Mostly it's disk reads/writes. I fixed those for AccountManager which
are reported at startup.
Conscrypt reads own version on startup which reads from disk multiple
times. There's no solution for it right now.
SharedPreferences which are used in BaseActivity also read from disk
and pretty early but it shouldn't be a problem.
=> Fix some of the StrictMode violations

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java
I have both Tusky nightly and regular Tusky installed on my phone and sometimes I cannot tell them apart (mostly in notifications and when the crash dialog appears while the app is in background). This should improve the situation.
=> better distinction between green and blue build flavors

app/src/main/java/com/keylesspalace/tusky/TuskyApplication.kt
Stacktrace
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.keylesspalace.tusky.test/com.keylesspalace.tusky.MainActivity}: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at …
```
=> fix workmanager crashing because of async initialization

app/src/main/java/com/keylesspalace/tusky/fragment/AccountListFragment.kt
The adapter was notified on the wrong thread, making it ignore the new data. The bug would not always occur, because if something else triggered a rebinding of the viewholder, it would fix itself.
closes #2005
=> fix the notification buttons on the muted users page

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
This gets rid of the "name shadowed" Kotlin warning.
Also something I messed up while adding the avatar to the toolbar 🙄
=> cleanup accountManager.activeAccount usages in MainActivity

app/src/main/res/values/theme_colors.xml
Small suggested tweak - exchanging the values of colorSurface and colorBackground in the light theme radically improves text contrast/readability and uses Tusky's blue tinted colour as an accent to define the tab area instead.
Should fix #1687, #1831 and #1971
=> Exchange colorSurface and colorBackground to improve text contrast

app/src/main/java/com/keylesspalace/tusky/LoginActivity.kt, app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.java
Seems like I have missed that when upgrading the library
=> use CustomTabColorSchemeParams instead of deprecated methods

app/proguard-rules.pro
Otherwise Gson fails to deserialize draft attachments
closes #2053
=> add proguard rule to keep DraftAttachment.Type

app/src/main/java/com/keylesspalace/tusky/util/SpanUtils.kt
While it's not allowed to create such accounts on Mastodon, it federates fine with servers that allow dashes.
=> SpanUtils: highlight nicknames with dashes

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
This is an attempt to fix the problem we have reported.
Basically it goes like this:
1. TalkBack is disabled
2. You open the app
3. You enable TalkBack
4. You try to use accessibility actions (swipe up-and-right)
5. It does not work on rows which were already displayed, only on those which are added later with scrolling
It seems like it should be fixed in libraries but I would try to bandaid it on our own. I think if we make it re-initialize all views it should work but I don't know how do it. `invalidate()` doesn't cut it.
=> Fix TalkBack not initializing old views

app/src/main/java/com/keylesspalace/tusky/components/drafts/DraftHelper.kt
This is so that when removing the old drafts feature we can savely delete the attachment files as well. When the old & new feature use the same directory, one file could belong to two drafts.
=> change draft attachment directory

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
As mentioned in the Matrix devroom, the *navigation icon* avatar acted strangely in some devices. The use of `FixedSizeDrawable` fixes it.
=> NavIcon Avatar fix

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
Steps to reproduce: Go to a user profile & change the relationshio (e.g mute). Note the "saved" message appearing below the profile note. The app even makes a network request.
This PR changes the behavior so the note is only saved on actual user changes.
=> fix profile note "Saved" message appearing on other account changes

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt, app/src/main/res/menu/account_toolbar.xml
I got a complaint that there is no confirmation dialog when unfollowing somebody via the menu. Instead of adding the dialog there, I think it is better to remove the option alltogether since it is redundant anyway and there are already a lot of options in that menu.
=> remove redundant options from account toolbar

app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesActivity.kt
<details>
```
java.lang.IllegalStateException: Target fragment must implement TargetFragment interface
at androidx.preference.PreferenceDialogFragmentCompat.onCreate(PreferenceDialogFragmentCompat.java:80)
at androidx.preference.ListPreferenceDialogFragmentCompat.onCreate(ListPreferenceDialogFragmentCompat.java:48)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:2685)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
at …
```
=> fix crash when rotating screen in a preference dialog twice

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt, app/src/main/java/com/keylesspalace/tusky/repository/TimelineRepository.kt, app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.java
Sometimes `displayName` was used for displaying username purposes.
(before)
(after)
I fixed them in first commit.
Second commit is my proposal. Make `displayName` private to prevent such mistakes.
If you don't like this, I will remove this commit.
=>  Avoid using displayName for displaying purpose

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
This fixes the following bug:
When opening the app via notification, switching tabs and then reopening the app from recents, the app switches to notifications again instead of the last used tab.
Please confirm this also fixes the issue you are having @charlag
=> fix MainActivity switching to notification tab when opened from recents

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
The caption dialog crashes when one tries to caption really large images.
Adding a size to the CustomTarget fixes the problem. I used 4096px because that is also the limit at which we downsize images before uploading them.
=> fix crash when captioning large images

app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt, app/src/main/java/com/keylesspalace/tusky/network/TimelineCases.kt, app/src/main/java/com/keylesspalace/tusky/view/MuteAccountDialog.kt, app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountViewModel.kt
The bug is fixed, but not yet released on mastodons side. https://github.com/tootsuite/mastodon/pull/15516
This workaround makes at least muting indefinitely work again with Mastodon 3.3.0
=> work around mastodon mute bug

app/src/main/res/raw/keep.xml
ic_local_24dp and ic_hashtag are only referenced in code and not in xml which seems to confuse the resource shrinker. The weird thing is, they are not shrinked everywhere, e.g. the Bitrise CI builds apks correctly but the one by @nailyk-fr shrinks the two drawables. I have no explanation for this.
This adds explicit keep directives to solve the problem.
=> fix crash because of shrinked resources

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt, app/src/main/res/layout/activity_license.xml, app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt, build.gradle
JCenter is getting turned off sometime next year https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Only two libraries we use were not available on Maven central: FileEmojiCompat, which @C1710 published there (thx again!) and the Image Cropper, which I replaced with a better fork because the original library is no longer maintained.
=> get rid of jcenter

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
In #2149 I fixed crashes with too large images, but now I'm seeing even more crashes and I think it is because smaller images get upscaled.
=> don't upscale images in caption dialog

app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsRepository.kt, app/src/main/java/com/keylesspalace/tusky/components/report/ReportViewModel.kt
There is a new lint inspection that tells you when you set `null` into non-null LiveData. This PR fixes the issues it reports.
=> fix LiveData nullability issues

app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt
No idea how this happened. It makes no sense at all.
=> fix "show notifications filter" preference opening tabs preferences

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineViewModel.kt
so it passes the `isExpectedRequestException` check
=> throw HttpException instead of generic exception in TimelineViewModel

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineViewModel.kt
In two places, we were filtering a temporary copy of the list that was never applied.
~~This maybe also fixes the infinite loading placeholder? (because placeholders were also removed from a disposable copy)~~
=> Fix filtering timelines

app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt, app/src/main/res/layout/fragment_view_video.xml, app/src/main/res/layout/item_media_preview.xml
- Descriptions for audio attachments are now shown in the media player
- Descriptions for audio and video attachments are now scrollable
- Media labels embedded in statuses are constrained to 10 lines (this doesn't affect the long-press popup)
Before:
After:
=> Audio caption improvements

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java
It was `false` in `PreferencesFragment`, but `true` everywhere else.
Apparently was overlooked when the default was changed https://github.com/tuskyapp/Tusky/pull/2245
=> fix confirmFavourites default

app/src/main/java/com/keylesspalace/tusky/network/FilterModel.kt, app/src/test/java/com/keylesspalace/tusky/FilterTest.kt
Fix #2284
I have not tried it yet, I’ll see if I can test that quickly.
=> filter messages by also looking at media descriptions

CONTRIBUTING.md
In the Kotlin section:
> This project is in the process of migrating to Kotlin, all new code must be written in Kotlin.
But then, in the Java section:
> Please don't submit new features written in Kotlin.
I changed it to:
> Please don't submit new features written in Java.
=> Fix a mistake in CONTRIBUTING.md

app/src/main/java/com/keylesspalace/tusky/BottomSheetActivity.kt, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt
There is some weird behavior in some edgecases:
1) Apparently there are statuses that contain links to themselves, so one can open the detail view in an infinite recursion. Example: https://anonsys.net/display/bf69967c-1961-efc6-22a9-867784751114
2) Pixelfed links are opened in the browser. Example: https://mastodon.social/@ConnyDuck/107684681310479962
3) Clicking on a card will always open the browser, even when the link could be opened in Tusky
This PR fixes those problems and cleans `BottomSheetActivityTests` up a bit
=> Fix some weird behavior when clicking links in statuses

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/db/TimelineDao.kt, app/src/test/java/com/keylesspalace/tusky/components/timeline/CachedTimelineRemoteMediatorTest.kt, app/src/test/java/com/keylesspalace/tusky/components/timeline/StatusMocker.kt, app/src/test/java/com/keylesspalace/tusky/db/TimelineDaoTest.kt
A disappearing placeholder could be reproduced like this on the home timeline:
Load a lot of new statuses so you get a full page (30 statuses) and a placeholder displayed.
One or more of the just loaded statuses gets deleted.
Refresh the timeline -> the deleted status disappears, but so does the placeholder
=> Fix disappearing placeholders

app/src/main/java/com/keylesspalace/tusky/util/CustomEmojiHelper.kt
After #2244, animated emojis were not rendered at all when the animation setting was turned off. This fixes that problem.
=> fix apng emojis not rendered when animation is turned off

app/src/main/java/com/keylesspalace/tusky/entity/Status.kt, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
I don't remember why equals/hashcode was overwritten in `Status` 🤔 
Anyway, _something_ in #2238 broke the diffing in NotificationsFragment, but I don't yet know what. Actually it is weird that it works in other places.
closes https://github.com/tuskyapp/Tusky/issues/2306
=> Fix comparing statuses and diffing in NotificationsFragment

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt
In #2267 I fixed this for the vertical orientation, but it can happen in horizontal as well 😅
=> fix horizontal insets of AccountActivity

app/proguard-rules.pro
Issue 1: `suspend` functions in `MastodonApi`were stripped of their type information
Issue 2: `ConversationAccountEntity` was minified so Gson failed to create instances of it
=> add additional R8 rules so conversations work again

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt
25 is old Mastodon default, it’s 50 since almost two years now:
- https://github.com/mastodon/mastodon/releases/tag/v3.1.3
- https://github.com/mastodon/mastodon/commit/37b3985bfac5ffdc8e452f92869dcdefb5c92594#diff-fe4ba091ed185315779c8bb492666772a32609b8f200134ce11542d86e1ed5cfR5
So the only problem could be very old Mastodon instances, or people decreasing their Mastodon instance poll max option chars, but it’s not very likely.
I know it’s late but I hope it could land in Tusky 16, especially because it’s such a small change and because it’s so annoying to be limited by the old limit of 25 characters on Tusky.
Related: #2338
=> increase default poll max option chars from 25 to 50

app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java
Now I know why the custom Status `equals` code was there that I removed in #2318
Note: The code in ViewThreadFragment is old and has a lot of other problems and this is only another hacky patch. I will rewrite it with Kotlin/coroutines/ViewModel as soon as possible but I don't want to delay Tusky 16 any longer.
Steps to reproduce: Open any status details, pull to refresh, the detailed status duplicates. It is kind of a race condition, sometimes one has to refresh multiple times for the duplicate to appear.
=> fix duplicate detail status

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt, app/src/main/java/com/keylesspalace/tusky/entity/MediaUploadResult.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
Why didn't we do this sooner 😲 
v2 is async and should be much faster.
Hopefully fixes stuff like #995 
I think v2 is only available since Mastodon 3.1.3
=> use POST api/v2/media to upload media

app/src/main/res/layout/item_follow_request.xml
This has been bugging me for a while 😅 
Before:
After:
=> correctly align buttons in follow requests

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/test/java/com/keylesspalace/tusky/util/LinkHelperTest.kt
~~When the post originates on another server, the span url will be `https://remote.server.tags/meh` and the url associated with the tag object will be `https://local.server/tags/meh`, so clicking a hashtag in a post originating from another server will (currently on `develop`) open the remote server's tag url in a browser :neutral_face:~~
This was even more broken than I realized - the incoming url doesn't necessarily have *any* relation to the local url associated with the tag. The only thing that makes sense is to match on the name.
=> Fix relinkifying tags in posts from remote servers

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/util/StringUtils.kt, app/src/test/java/com/keylesspalace/tusky/StringUtilsTest.kt, app/src/test/java/com/keylesspalace/tusky/db/TimelineDaoTest.kt
Problem: `String.inc()` and `String.dec()` were not inverse in all cases, so a placeholder id created by status id dec() could not be turned into the status id again with inc(), which caused the timeline to miss statuses.
Example:
`"1230".dec() = "122z"`
`"122z".inc() = "122{"`
`api/v1/timelines/home?max_id=122{` returns empty array.
This PR fixes the problem by making sure `"AnyAlphanumericString".dec().inc() == "AnyAlphanumericString"`.
(And I also improved the TimelineDaoTest while looking for the bug)
=> fix String.inc() and String.dec() not being inverse operations

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt, app/src/main/java/com/keylesspalace/tusky/viewmodel/EditProfileViewModel.kt, app/src/main/res/layout/activity_edit_profile.xml
Turns out that
- the cropping library can handle both picking & resizing for us
- no permission is necessary since the picking is done by a system app
200 lines of code less for us 😍
=> update Android Image Cropper and get rid of deprecated onActivityResult

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelinePagingAdapter.kt
On some low memory devices, when you navigate away from the MainActivity, it gets destroyed and then recreated when you return to it, with the timeline jumping to top.
(You can easily get the same behavior on any device by setting "don't keep sctivities" in the developer options of the device)
This fix only works on the home timeline, because other timelines are not cached and cannot restore any position (yet - there might be a more complicated way to get it fixed in every timeline)
=> Fix timeline jumping to top when activity is recreated

app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt
This is just another one of the tiny things that kept annoying me. Having these two similar options next to each other makes them way easier to find.
=> move "animate custom emojis" preference next to "animate avatars"

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/util/StringUtils.kt, app/src/test/java/com/keylesspalace/tusky/StringUtilsTest.kt
I found that `NetworkTimelineViewModel` has some incomplete methods so tried to fix them.
I referred `CachedTimelineViewModel` and carefully implemented for network timeline, but it might have some mistakes so please check my codes.
Mistakes I found:
* `loadMore` does not handles statuses overlaps
* `loadMore` does not inserts new placeholder after fetched statuses when the number of statuses in the gap is more than fetch limit.
* `fullReload` does not fully refresh timeline. Statuses they are already fetched are not included after refresh.
=> Fix some network timeline bugs

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
When opening the app and having the first tab set to the home timeline, sometimes the "Nothing here" elephant friend is visible for a split second before the progress bar appears. This fixes the problem.
=> fix "nothing here" flickering when starting Tusky

app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt
Apparently Android deletes all downloads that are not saved into the Downloads folder after a week. So lets use `DIRECTORY_DOWNLOADS` instead of `DIRECTORY_PICTURES`.
Note: When choosing "Download all media" on a status, we already save to Downloads.
close https://github.com/tuskyapp/Tusky/issues/2262
closes https://github.com/tuskyapp/Tusky/issues/1804
=> change media download location to Download directory

app/src/main/java/com/keylesspalace/tusky/json/SpannedTypeAdapter.kt
Finally fixing this bug that has been in Tusky since day 1
closes #786
before/after
=> correctly render whitespace in posts

app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt, app/src/main/java/com/keylesspalace/tusky/adapter/AccountAdapter.kt, app/src/main/java/com/keylesspalace/tusky/adapter/AccountViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/BlocksAdapter.kt, app/src/main/java/com/keylesspalace/tusky/adapter/FollowRequestViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/adapter/MutesAdapter.kt, app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeAutoCompleteAdapter.java, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt, app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchAccountsAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchAccountsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelinePagingAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineTypeMappers.kt, app/src/main/java/com/keylesspalace/tusky/entity/Account.kt, app/src/main/java/com/keylesspalace/tusky/entity/Conversation.kt, app/src/main/java/com/keylesspalace/tusky/entity/Notification.kt, app/src/main/java/com/keylesspalace/tusky/entity/SearchResult.kt, app/src/main/java/com/keylesspalace/tusky/entity/Status.kt, app/src/main/java/com/keylesspalace/tusky/entity/TimelineAccount.kt, app/src/main/java/com/keylesspalace/tusky/fragment/AccountListFragment.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/java/com/keylesspalace/tusky/viewdata/NotificationViewData.java, app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.kt, app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountsInListViewModel.kt, app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/StatusComparisonTest.kt, app/src/test/java/com/keylesspalace/tusky/components/timeline/StatusMocker.kt
- Fix how `Status` and `StatusViewData` are compared to get rid of unnecessary view updates
- introduce `TimelineAccount` which is the same as `Account` but with less attributes so it is way faster
- add tests to make sure it really works as intended
- comparing statuses is slower than before, but the performance gain from `TimelineAccount` and less view updates is definitely worth it.
Decoding a full page (30 statuses) from json
|    | before - full `Account` | after - `TimelineAccount`|
| ------------- | ------------- | ------------- |
| Nokia 1  | 156 216 015 ns  | 86 186 701 ns|
| Pixel 2  | 45 626 983 ns | 23 611 981 ns|
| Fairphone 4 | 17 599 792 ns | 9 814 219 ns
Measured with this https://github.com/tuskyapp/tusky-json-benchmark
Memory usage - before / after
=> Fix status diffing and improve timeline performance

app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt
`ShareCompat.IntentBuilder` handles all the subtleties involved with sharing content. With this change the share sheet will display a preview when sharing images (on Android versions that support this).
Before and after:
See https://issuetracker.google.com/issues/173137936
=> Fix image preview in share sheet

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt
While investigating #2232 I noticed that other apps, e.g. Nextcloud could open the shared image, but Tusky could not.
Fortunately Nextcloud is open source and the thing is that `file://` uris need to be handled differently (with file api), only `content://` works with ContentResolver.
(Providing `file://` uris is bad, outdated practice, but we can't control other apps so we should support them as well)
Also, not only plain text shares can contain a subject so I removed the check.
closes #2232
=> Improve handling of shared media

app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
Mastodon instances ignore the extra slash so we did not notice.
=> remove extra slash in OAuth authorize url

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/components/report/adapter/StatusViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/util/AbsoluteTimeFormatter.kt, app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt, app/src/test/java/com/keylesspalace/tusky/util/AbsoluteTimeFormatterTest.kt
- Factorize code: now everything is handled at the same place, instead of being copy-pasted.
- Change how absolute time is displayed:
- When time of the post is on the same day as today, `HH:mm` is used instead of `HH:mm:ss` (seconds are not necessary the vast majority of the time and are available in detailed view if needed anyway)
- When time of the post is on a different day but in the same month as today, `MM-dd HH:mm` is used instead of `MM/dd HH:mm:ss` (I changed from `/` to `-` to better reflect the fact the format put the month before the day, like ISO 8601 and and RFC 3339)
- When time of the post is on a different month, `yyyy-MM-dd` is used instead of `MM/dd HH:mm:ss` as above (the fact that the year is not displayed at all in this case is confusing and not practical, and I …
=> Improve time format of posts when using absolute time

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
- Added back the InitCallback
- Made extra sure that EmojiCompat.process (in the MainActivity) is only called if EmojiCompat has gotten to LOAD_STATE_SUCEEDED
=> EmojiCompat fix

app/src/main/java/com/keylesspalace/tusky/components/search/SearchActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/interfaces/StatusActionListener.java
- SearchActivity is started without slide-in, so it should also finish without slide-out (or should it be the other way around?)
- ViewThread/Account/Tag activity are finished with slide-out, so they should also be started with slide-in
=> fix SearchActivity transition animations

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
The refresh indicator was hidden a split second before the new statuses were visible, which was annoying because one thinks that there is nothing new but then the timeline jumps. The problem was the indicator was already hidden when network loading was finished. With this change it will wait until database loading is finished as well.
=> fix timeline refresh indicator finishing before updates are visible

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
another one of these 🙄 
(all these `parseAsMastodonHtml` in random places will go away once we have NotificationsFragment in Kotlin, because then we can also get rid of SFragment, and do these operations on StatusViewData instead of Status)
=> fix unparsed html when sharing status content

app/src/main/java/com/keylesspalace/tusky/components/login/LoginActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/login/LoginWebViewActivity.kt, app/src/main/res/values/strings.xml
Previously we simply closed the screen with the login WebView which
could cause confusion. Now we specify that page could not be loaded.
As a side effect it will also show the error message which the server
returns (if any).
=> Improve UX when Login WebView fails to load the page

app/build.gradle
app/build.gradle invokes git on the command line to get the current changeset. If the git invocation fails, the entire build fails.
I attempted to build Tusky on a Windows system without Git (I checked out the repo using Mercurial and the hg-git bridge, running inside WSL-- so Git would have failed even if it were installed, just like it would attempting to build from a tgz downloaded from Github). Android Studio failed. Worse, it failed with a very unhelpful 200-line error message ([build-3-expanded.txt](https://github.com/tuskyapp/Tusky/files/8665469/build-3-expanded.txt)), which did not indicate the line in build.gradle causing the git requirement, rather it appeared the git-related failure occurred inside something called "net.rubygrapefruit.platform" which is apparently Android …
=> Allow build on systems without git

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
closes #2515 
I think this already worked once but got lost in some refactoring
=> fix currently logged in profiles not being visible in main drawer when offline

app/build.gradle, app/schemas/com.keylesspalace.tusky.db.AppDatabase/36.json, app/src/main/AndroidManifest.xml, app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/SplashActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/login/LoginActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java, app/src/main/java/com/keylesspalace/tusky/components/notifications/PushNotificationHelper.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/AccountPreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/db/AccountEntity.kt, app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt, app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java, app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt, app/src/main/java/com/keylesspalace/tusky/di/BroadcastReceiverModule.kt, app/src/main/java/com/keylesspalace/tusky/entity/NotificationSubscribeResult.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/java/com/keylesspalace/tusky/receiver/NotificationBlockStateBroadcastReceiver.kt, app/src/main/java/com/keylesspalace/tusky/receiver/UnifiedPushBroadcastReceiver.kt, app/src/main/java/com/keylesspalace/tusky/util/CryptoUtil.kt, app/src/main/res/values/strings.xml
Fixes #793.
This is an implementation for push notifications based on UnifiedPush for Tusky. No push gateway (other than UP itself) is needed, since UnifiedPush is simple enough such that it can act as a catch-all endpoint for WebPush messages. When a UnifiedPush distributor is present on-device, we will by default register Tusky as a receiver; if no UnifiedPush distributor is available, then pull notifications are used as a fallback mechanism. 
Because WebPush messages are encrypted, and Mastodon does not send the keys and IV needed for decryption in the request body, for now the push handler simply acts as a trigger for the pre-existing NotificationWorker which is also used for pull notifications. Nevertheless, I have implemented proper key generation and storage, just in case we would …
=> Push notifications support via UnifiedPush

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/MediaPreviewAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt, app/src/main/res/values/strings.xml
It should be possible to crop images. There is a crop library already in place.
This is a work in progress. I have created a pull request so I can ask questions on the Matrix channel.
Current status: The menu item for the cropper is created, the local content URL is updated, but the server is not notified.
=> Ability to crop images attached to posts

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
An initial delay (0) can be specified.
Fixes https://github.com/tuskyapp/Tusky/issues/2554
=> Fire observable to update timestamps directly on resume (#2554)

app/src/main/java/com/keylesspalace/tusky/components/preference/TabFilterPreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt
This is a variant of #2567 that changes the key to forcibly reset the key to true for everyone. This may be desirable because many of the people who had this key set to hide replies (including me, and at least two other people I talked to) were surprised to learn how the key was set and additionally did not know the key existed.
=> Fix unintended [mismatched] show-replies preference (with key force-reset)

app/build.gradle
This fixes a crash with gifs some instances have as custom emoji, see https://github.com/penfeizhou/APNG4Android/issues/148
=> update android animation glide plugin to 2.22.0

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt
Loading of statuses and loading of filters is an "intended" race:
we want to display statuses first, especially if they are cached.
Unfortunately we do not cache filters themselves so when we load cached
statuses we do not apply filters.
One part of the solution is to re-filter the statuses once we fetch the
filters. This commit implements it. Caching of filters is not included
yet.
fixes #2546
=> Fix filters in timelines in a simple way

app/schemas/com.keylesspalace.tusky.db.AppDatabase/38.json, app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java, app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt, app/src/main/java/com/keylesspalace/tusky/di/NetworkModule.kt, app/src/main/java/com/keylesspalace/tusky/json/UtcDateTypeAdapter.java
Basically the built-in `Date` handling sucks, see https://github.com/google/gson/issues/935
closes https://github.com/tuskyapp/Tusky/issues/2476
I was thinking we could also migrate to Moshi, but
➕ Moshi has better Kotlin support
➖ According to my measurements [here](https://github.com/tuskyapp/tusky-json-benchmark) it is slower than Gson
➖ Migration is quite an effort and we could break something
=> Add UtcDateTypeAdapter for Gson

app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt, app/src/main/java/com/keylesspalace/tusky/network/MediaUploadApi.kt
This PR updates the MediaUploadApi logic to use Conny's `NetworkResult` instead of the previous `Result` that was being returned.
closes https://github.com/tuskyapp/Tusky/issues/2576
=> Use NetworkResult in MediaUploadApi

app/src/main/java/com/keylesspalace/tusky/components/notifications/PushNotificationHelper.kt
Only use distributors which are compatible with FEATURE_BYTES_MESSAGE. This is because Mastodon sends notifications that are arbitrary bytes, not UTF-8. This causes issues in older versions of UnifiedPush distributors and providers that don't support FEATURE_BYTES_MESSAGE, specifically Gotify w/ Postgres, see #2547 for more info.
I have tested this on my device.
Closes #2547
=> UnifiedPush: FEATURE_BYTES_MESSAGE distributors

app/src/main/java/com/keylesspalace/tusky/db/InstanceDao.kt
This gets rid of the build warning and it should be slightly more efficient because unused columns are not loaded into memory (and the column holding the emojis can be huge)
=> rewrite InstanceDao queries to drop unused columns

app/src/main/java/com/keylesspalace/tusky/adapter/AccountSelectionAdapter.kt
- Add multiple accounts to Tusky
- Share something to Tusky from another app
- Observe the account selection list
Expected result: Only bot accounts are badged as bots
Actual result: All accounts are badged as bots
In the place where we create this dialog, we don't have any information about whether the account is a bot (because it's only on `TimelineAccount` and not `AccountEntity`). However, it's not useful information here anyway, so let's never show the badge.
=> Don't display bot badge in account selection dialog

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/db/TimelineDao.kt
New approach for the same problem as https://github.com/tuskyapp/Tusky/pull/2573
In contrast to #2573 this does not delay any network calls, but there might still be race conditions were the timeline stays empty or filters are not applied immediately. It worked fine in may testing though.
=> fix empty timeline on initial load

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/res/values-fa/strings.xml, app/src/main/res/values-gd/strings.xml, app/src/main/res/values-gl/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-is/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-no-rNB/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
The new message for the crop feature, "The attachment could not be edited.", turned out to be awkward in some languages (French) where according to the translator it would be better to more specifically say "The image could not be edited." (as currently we can only edit images). Patch replaces `error_media_edit_failed` with a `error_image_edit_failed` and deletes the existing `error_media_edit_failed`s.
=> Use specific term "image" in error UI, not "attachment"

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java, app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.kt
Fixes #2565 
Verified:
- Non-cwed statuses (timeline)
- Non-cwed statuses (detail view)
- CWed statuses (timeline)
- CWed statuses (detail view)
- NonCWed autocollapsing status (timeline)
- NonCWed autocollapsing status (detail view)
- CWed autocollapsing status (timeline)
- CWed autocollapsing status (detail view)
=> Fix hiding/showing preview cards for sensitive statuses

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/PushNotificationHelper.kt, app/src/main/res/layout/activity_main.xml
As recommended by Material guidelines: https://material.io/components/snackbars#placement
closes https://github.com/tuskyapp/Tusky/issues/2597
=> show push migration snackbar above floating action button

app/build.gradle
This update simply bumps the version code of Openmoji to 14.0 to allow updates for those who use it.
Waiting for the release to Maven Central to complete...
=> Update FilemojiCompat to version 3.2.3

app/src/main/java/com/keylesspalace/tusky/StatusListActivity.kt, app/src/main/java/com/keylesspalace/tusky/entity/HashTag.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/res/drawable/ic_person_remove_24dp.xml, app/src/main/res/menu/view_hashtag_toolbar.xml, app/src/main/res/values/strings.xml
Addresses #2637
Adds a follow/unfollow toolbar item to the hashtag list activity when instance responds to the new api, and gracefully does nothing when an instance doesn't support it yet.
Tested with:
- glitch.taks.garden (supported)
- mastodon.gamedev.place (unsupported)
=> Add support for following hashtags

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
This prevents accidental closing of dialog by clicking
outside of the dialog.
=> Make CaptionDialog non-cancellable

app/schemas/com.keylesspalace.tusky.db.AppDatabase/42.json, app/src/main/java/com/keylesspalace/tusky/adapter/LocaleAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewData.kt, app/src/main/java/com/keylesspalace/tusky/components/drafts/DraftHelper.kt, app/src/main/java/com/keylesspalace/tusky/components/drafts/DraftsActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineTypeMappers.kt, app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java, app/src/main/java/com/keylesspalace/tusky/db/DraftEntity.kt, app/src/main/java/com/keylesspalace/tusky/db/TimelineStatusEntity.kt, app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt, app/src/main/java/com/keylesspalace/tusky/entity/DeletedStatus.kt, app/src/main/java/com/keylesspalace/tusky/entity/NewStatus.kt, app/src/main/java/com/keylesspalace/tusky/entity/Status.kt, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java, app/src/main/java/com/keylesspalace/tusky/receiver/SendStatusBroadcastReceiver.kt, app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt, app/src/main/res/layout/activity_compose.xml, app/src/main/res/values/strings.xml, app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/ComposeActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/FilterTest.kt, app/src/test/java/com/keylesspalace/tusky/components/timeline/StatusMocker.kt, app/src/test/java/com/keylesspalace/tusky/db/TimelineDaoTest.kt
#2459 
- Add dropdown to compose view
- iso language code on spinner button
- language name in current language (language name in target language) on dropdown entries
- Language is included when posting statuses
- Language is saved/restored with drafts
- Compose language defaults to the language chosen for Tusky or the system language
Known issues:
- ~~We're tight on UI space in the compose view bottom bar, maybe need to rearrange~~
- ~~At least one of our translations (norsk bokmål) is keyed with a language code that doesn't match the one android gives it, making the defaulting not work (see [matrix message](https://matrix.to/#/!PWkUGGpeMZWDPmdfRE:matrix.org/$1659728795246423pnsUm:matrix.org?via=m.charlag.space&via=matrix.org&via=tchncs.de))~~
- Dropdown doesn't prioritize recently used …
=> Add language dropdown to compose view

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/res/layout/activity_compose.xml, app/src/main/res/values/strings.xml
- Shown on the main toolbar (subtitle)
- Shown just above the "replying to" message (even if not replying)
I made this feature for users who frequently post across multiple accounts with the same avatar. Currently there isn't an easy way to know which timeline you're on from the main view without sliding the sidebar open, and when posting (rather important) it's impossible to know who you're posting as, unless you have a unique avatar.
I am hoping these changes are minor enough that they should be OK. Please let me know if any tweaks would improve this.
Note that these altered visuals are only present when more than one account is present in the list.
I decided to change the text of `compose_active_account_description` instead of adding a new entry, because the text seems to only be used …
=> Add display of handle when using multiple accounts

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/keylesspalace/tusky/util/LinkHelperTest.kt
Addresses #2694
My *instinct* is to spend more time trying not to iterate the content multiple times, but maybe it's ok because many posts don't contain links/tags/mentions, and they only have a few when they do 🤷
=> Show target domains for non-mention/non-hashtag links where the target domain is not provided or differs from the domain in the text

app/src/main/java/com/keylesspalace/tusky/util/AsciiFolding.kt, app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/main/java/com/keylesspalace/tusky/util/SpanUtils.kt, app/src/test/java/com/keylesspalace/tusky/SpanUtilsTest.kt, app/src/test/java/com/keylesspalace/tusky/util/LinkHelperTest.kt
I noticed this while testing https://github.com/tuskyapp/Tusky/pull/2698 - hashtags like #bitsundbäume, #séance21h, and #GroßerGarten weren't getting the custom tag span
Note: there are some inconsistencies with non-mastodon servers: for example, pixelfed normalizes "GroßerGarten" to "grossergarten" and mastodon makes it "großergarten", but I guess our approach is generally to follow mastodon
- Update mention and tag regexes from current mastodon
- Perform unicode => ascii normalization the way that mastodon does
- Add test cases for nonascii tags
=> Fix the tag span generation for tags with nonascii characters

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
This PR improves the restoration behavior of `ComposeActivity` for the case that it is killed by the Android system and later restored from instance state.
Some information, like post content, is retained correctly by the Android system. Certain information is however currently lost during kill&restore:
* post visibility
* schedule time
* visibility of content warning field (however, not the content warning text itself)
To test:
1. Open developer settings, scroll to "Apps", toggle "Don't keep activities".
2. Open Tusky, compose a new post.
3. Expand content warning field, set a visibility that is different from the default, and a schedule time.
4. Open the app switcher (this kills `ComposeActivity`) and open it again.
Without this PR:
5. Observe that the CW field is collapsed (even though …
=> Retain instance state in compose activity

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/test/java/com/keylesspalace/tusky/util/LinkHelperTest.kt
Prior to this, if the markup were like `<a href="https://itch.io/">itch.io</a>`, it would render as `itch.io (🔗 itch.io)`
=> Don't markup urls where the display text is exactly the domain

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/entity/Card.kt, app/src/main/res/layout/item_status.xml, app/src/main/res/layout/item_status_detailed.xml
There where several bugs with link previews in timelines when the setting is on:
- blurhash not being scaled to image size
- weird cropping/scaling on the preview images
- in rare cases even the wrong image from another status was displayed
Additionally the ripple effect when clicking a card did not work as expected. Took me while to figure out that I need to use `ShapeableImageView` but I eventually fixed all problems.
Thread with a lot of links for testing: https://chaos.social/web/@ConnyDuck/109264267201083712
Before:
After:
=> Fix rendering of link preview images

app/src/main/res/values-large-land/dimens.xml
On tablets in landscape format the compose field would be too big (400dp) and be hidden behind the bottom bar when composing long texts. This fixes the problem.
=> fix compose field on landscape tablets

app/src/main/res/layout/activity_account.xml, app/src/main/res/layout/item_account_field.xml
Fixes #2752 
By enabling selection on text fields for `accountFieldValues` and `accountNote`
=> #2752: enable to copy the profile bio and its account fields

app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt
fixes: #2072
hide/show add reaction chip based on the reaction count
[device-2022-11-06-183243.webm](https://user-images.githubusercontent.com/841681/200185881-ffe1cb1d-2832-47e5-a99b-14af62d9c362.webm)
=> #2072: hide add reaction when limit is reached

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/test/java/com/keylesspalace/tusky/util/LinkHelperTest.kt
It seems like URLs could be marked up repeatedly. See screenshot below.
1. Display a post with URL markup
2. Hide the post by scrolling up or down
3. Display the post again by scrolling
4. Repeat 2 and 3
`SpannableBuilder.valueOf` does not create new instance when passed `CharSequence` is an instance of `SpannableBuilder`.
`markupHiddenUrls` is called every time `StatusBaseViewHolder.setupWithStatus` called, and updates status object.
Example post from my misskey account: https://misskey.io/notes/97hkq07foc
=> Fix `markupHiddenUrls` destructs original CharSequence

app/src/main/java/com/keylesspalace/tusky/util/AbsoluteTimeFormatter.kt, app/src/test/java/com/keylesspalace/tusky/util/AbsoluteTimeFormatterTest.kt
Noticed when scrolling notifs that the short date format is ambiguous as to whether it is DD/MM or MM/DD (figured it is the latter), but that's unintuitive to users where that's not the standard date format. This change uses MMM instead of MM to make it more clear (e.g. 10 Nov. vs. 11/10).
=> Switch to an unambiguous date format in Absolute Time mode

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/test/java/com/keylesspalace/tusky/util/LinkHelperTest.kt
Some Misskey users use Markdown to share URLs with its title with URL. URL markup is too redundant for such URLs.
Examples of URLs with trailing URL:
* [GitHub | https://github.com/](https://github.com) (`[GitHub | https://github.com/](https://github.com)`)
* [GitHub - github.com](https://github.com) (`[GitHub | https://github.com/](https://github.com)`)
* [GitHub https://github.com](https://github.com) (`[GitHub | https://github.com/](https://github.com)`)
There are some variations for such representation, so I decided to cut texts with whitespace and take the last part of them.
Example post from my misskey account: https://misskey.io/notes/97hjya45lu
=> Make URLSpans with trailing URL not marked up

app/src/main/AndroidManifest.xml, app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
Turns out the scoped storage thing on Android 10+ allows us to just not ask for the permission and still read/write what we want.
closes https://github.com/tuskyapp/Tusky/issues/2801
=> fix media permissions on Android 10+

app/src/main/res/layout/activity_main.xml
* Fix the toolbar subtitle appearing slightly cropped (see #2712).
* It's an AppCompat.Toolbar, so applying the default theme appears to do the trick.
This is how it looks after the change:
=> Use the appcompat style for Toolbar. Fixes subtitle vertical cropping.

app/schemas/com.keylesspalace.tusky.db.AppDatabase/43.json, app/src/main/java/com/keylesspalace/tusky/adapter/LocaleAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/AccountPreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/db/AccountEntity.kt, app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt, app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java, app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt, app/src/main/java/com/keylesspalace/tusky/entity/Account.kt, app/src/main/java/com/keylesspalace/tusky/util/LocaleExtensions.kt, app/src/test/java/com/keylesspalace/tusky/ComposeActivityTest.kt
- Fix duplicated "sublanguages" (e.g. en-US vs. en-IN) in the preferred list (#2900)
- Prefer modern language codes (e.g. yi over ji) (#2903)
- Prefer the server's per-account posting language, if set (#2902)
- Support setting the post language to languages android doesn't know yet (e.g. toki pona)
Future work: UI for setting the server's per-account posting language from Tusky
=> Language selection fixes

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/account/list/ListsForAccountFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/account/list/ListsForAccountViewModel.kt, app/src/main/java/com/keylesspalace/tusky/di/FragmentBuildersModule.kt, app/src/main/java/com/keylesspalace/tusky/di/ViewModelFactory.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/res/layout/fragment_lists_for_account.xml, app/src/main/res/layout/item_add_or_remove_from_list.xml, app/src/main/res/menu/account_toolbar.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Implemented "Add or remove from list" feature in account column of Mastodon frontend.
Though Mastodon doesn't show this menu for self account, I configured to show since Mastodon supports adding self into lists.
* Fix #2815 
* Fix accelforce/Yuito#20
* I don't know why but text in the Snackbar is really hard to see. Please help me if you know how to fix this.
* Currently spawned Snackbar disappears automatically after `LENGTH_LONG`. Should this be `LENGTH_INDEFINITE`?
=> Add or remove from lists in AccountActivity

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/search/SearchActivity.kt
The "Enable swipe gesture to switch between tabs" preference was ignored on the tabs on a profile page ("Posts", "With Replies", "Pinned", "Media"), and search ("Posts", "Accounts", "Hashtags").
Fix this.
While I'm here, replace a string for the preference name in MainActivity.kt with a constant.
Fixes https://github.com/tuskyapp/Tusky/issues/2874.
=> Disable tab swiping by preference in profile and search

app/src/main/java/com/keylesspalace/tusky/BottomSheetActivity.kt, app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/util/LinkHelperTest.kt
- goto social status urls
- goto social profile urls
- microblog.pub status urls
(microblog.pub profile urls are just site urls, so 🤷 )
I also moved the utility function into `LinkHelper`, it felt weird to keep it in `BottomSheetActivity`
#2893
=> Load goto social and microblog.pub urls in the app

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/styles.xml
This should help all those users that disable the top bar and then don't find the menu anymore.
The 4 possible states:
closes https://github.com/tuskyapp/Tusky/issues/2799
makes https://github.com/tuskyapp/Tusky/pull/2750 obsolete
=> Show Avatar next to tabs when main top bar is disabled

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
- Convert to use view binding
- Use requireContext() in places a context is required
- Simplify code with .sublist() and .contains()
- Add @nonnull annotations where appropriate
- Use consistent comment styles
=> Cleanup NotificationFragment to make future conversion to Kotlin easier

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
This should prevent a rare crash I'm seeing in the Play console
```
Exception android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 clip={text/uri-list hasLabel(0) {U(content)}} (has extras) }
at android.app.Instrumentation.checkStartActivityResult (Instrumentation.java:2167)
at android.app.Instrumentation.execStartActivity (Instrumentation.java:1811)
at android.app.Activity.startActivityForResult (Activity.java:5470)
at androidx.activity.ComponentActivity.startActivityForResult (ComponentActivity.java:728)
at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult (ActivityCompat.java:809)
at androidx.core.app.ActivityCompat.startActivityForResult (ActivityCompat.java:246)
at …
```
=> hide "take photo" button when no photo app is installed

app/src/main/res/layout/notifications_filter.xml
On smaller devices the notification filter listview may be longer than the screen height, and pushes the "Apply" button out of sight.
Fix this by:
- Set the height of the listview to 0dp and its layout_weight to 1
- Set the layout_weight of the button to 0
This ensures the button always appears (because the listview height is 0dp) and the listview then expands to fill any remaining space (because the layout_weight is 1).
Fixes https://github.com/tuskyapp/Tusky/issues/2985
=> Ensure the "Apply" button is always visible

app/src/main/java/com/keylesspalace/tusky/db/Converters.kt
This is needed to convert the "editedAt" attribute of ConversationStatusEntity, without it ConversationsFragment shows the sad elephant frend.
(regression from https://github.com/tuskyapp/Tusky/pull/2935)
=> make date converter null safe

app/build.gradle, app/src/main/AndroidManifest.xml
to get rid of this warning
```
package="com.keylesspalace.tusky" found in source AndroidManifest.xml: C:\Users\Conny Duck\AndroidApps\Tusky\app\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
```
=> replace Manifest package with Gradle namespace

app/src/main/res/layout/fragment_view_image.xml
Fixes #2819, #2126
In my quick testing text selection here didn't conflict with dragging up and down. May also be worth adding a copy alt option to the menu options?
=> Left-align image alt text & make it selectable

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt
If the user is viewing their own account activity the FAB will be shown. However, clicking on the FAB will not populate mentions in the Compose activity.
Fixes #3058
=> Add FAB to self account view

app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt
Fixes an issue where attachment doesn't autoplay when swiping left/right from initial attachment.
`setUserVisibleHint` is deprecated and it looks like `ViewPager2` does not call `setUserVisibleHint` when swiping between pages.
Testing:
- Open a toot with multiple videos or gifs: https://peoplemaking.games/@lacruzo/109537282222626550
- Swipe away from initial video and ensure attachment autoplays
Fixes #3066
=> Fix auto play when swiping between attachments

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
While only present in a Log.d call, which should be stripped out of release builds, this feels like an unnecessary privacy risk.
=> Remove debug logging of keypresses

app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledStatusAdapter.kt
If the user submits an edit to the scheduled status then this one will be deleted, the paging source will notice, the adapter will be notified in the normal way, and this binding will be reused.
Or the user backs out of the edit, and this adapter entry is still valid and should remain clickable.
Fixes https://github.com/tuskyapp/Tusky/issues/2705
=> Leave the "edit scheduled status" button enabled after clicking

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java, app/src/main/res/values/styles.xml
These aren't necessary for the app, and are overwritten with the actual style in `BaseActivity.onCreate()`.
But if they're missing the Android Studio layout preview renderer crashes.
=> Provide default text sizes in TuskyBaseTheme

app/src/main/java/com/keylesspalace/tusky/adapter/MutesAdapter.kt, app/src/main/java/com/keylesspalace/tusky/fragment/AccountListFragment.kt, app/src/main/res/layout/item_muted_user.xml, app/src/main/res/values/strings.xml
As discussed in our dev channel, use a switch instead of a button to avoid confusion about the state.
- also migrates the adapter to view binding
- also migrates the layout to a ConstraintLayout
While doing this I found several problems with account lists, like the bot overlay missing and other inconsistencies. I will fix those in a follow up PR.
cc @mal0ki
=> Improve muted users list

app/src/main/res/values-en-rGB/strings.xml, app/src/main/res/values/strings.xml
Tusky mostly uses (correctly, per Android style guide) sentence case (i.e., a single initial capital letter) in strings like "Scheduled posts" or "Muted users".
But there are a few instances of title case (i.e., each initial letter is capitalised) that have crept in ("Account Preferences", "Log Out", "Follow Requests", etc).
Convert them to sentence case.
=> Convert "title case" strings to "sentence case"

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/entity/Account.kt, app/src/main/res/menu/account_toolbar.xml, app/src/main/res/values/strings.xml
Attempting to address #3093 (and maybe some of the semi-overlap bugs linked at the bottom of 3093). Here's what I have currently:
[<img width=250 src="https://files.mastodon.social/media_attachments/files/109/594/372/136/707/170/original/7db50a0dde776e97.png" />](https://files.mastodon.social/media_attachments/files/109/594/372/136/707/170/original/7db50a0dde776e97.png) [<img width=250 src="https://files.mastodon.social/media_attachments/files/109/594/373/215/574/008/original/83f72331a773c14c.png" />](https://files.mastodon.social/media_attachments/files/109/594/373/215/574/008/original/83f72331a773c14c.png)
And what you see works but there are Problems and I need Advice.
1. What should the wording be (IE, should "handle" be "handle"? or "address"? Or "username"? or something else? I …
=> Share and copy menu items for account page

app/src/main/java/com/keylesspalace/tusky/json/Rfc3339DateJsonAdapter.kt
fixes https://github.com/tuskyapp/Tusky/issues/2272
according to the Google Play stats we had 36 crashes in the last 30 days because of this
=> don't crash on unparseable date

app/src/main/java/com/keylesspalace/tusky/adapter/TabAdapter.kt
The intent of the previous code seems to be to show an "X" icon on a hashtag chip when two or more chips are present.
This didn't work because the icon was not set as visible.
Fix this. In addition, set this as a "cancel" icon, not the chip's regular icon, so it appears on the right (in LTR locales), as is normal for the close button on chips.
Tinting the icon did nothing, so remove that.
=> Show a close button for hashtag tab chips

app/build.gradle
Robolectric normally swallows output from `Log.*` calls in tests and the code under test. This can make debugging failing tests more difficult than it needs to be.
Set `robolectric.logging.enabled` to `true` to enable the logs.
=> Enable robolectric logging

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/components/viewthread/edits/ViewEditsAdapter.kt, app/src/main/java/com/keylesspalace/tusky/view/MediaPreviewLayout.kt
This fixes two issues
- blurhashes sometimes not being scaled to fit the imageview
- ALT labels being displayed when the media preview is hidden
I have also been seeing layout shifts after media was loaded, I can no longer reproduce this though.
Not 100% sure why the `doOnLayout` was added in the first place, it defintely causes more problems than it solves.
=> Fix media preview bugs

app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt
Also make sure that thread view is closed when detailed status is blocked or deleted
closes https://github.com/tuskyapp/Tusky/issues/3158
=> prevent thread view from scrolling when post is interacted with

app/build.gradle
As of Kotlin 1.7 the opt-in feature is now stable and does not need an explicit declaration.
https://kotlinlang.org/docs/whatsnew17.html#stable-opt-in-requirements
=> Remove old opt-in for RequiresOptIn

app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt
Click on a link that looks like a Mastodon url in the detailed status while the thread is still loading -> 💥 
```
Exception java.lang.ClassCastException:
at com.keylesspalace.tusky.components.viewthread.ViewThreadViewModel.detailedStatus (ViewThreadViewModel.java:181)
at com.keylesspalace.tusky.components.viewthread.ViewThreadFragment.onViewUrl (ViewThreadFragment.kt:310)
at com.keylesspalace.tusky.util.LinkHelper$setClickableText$2$customSpan$1.onClick (LinkHelper.kt:123)
at android.text.method.LinkMovementMethod.onTouchEvent (LinkMovementMethod.java:232)
at android.widget.TextView.onTouchEvent (TextView.java:12347)
at android.view.View.dispatchTouchEvent (View.java:15533)
at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3316)
at …
```
=> fix crash when user clicks url in partially loaded thread

app/src/main/java/com/keylesspalace/tusky/fragment/AccountListFragment.kt
Open a AccountListFragment and close it before stuff is loaded -> 💥 
Happens because catching all exception also catches the CancellationException, and in onFetchAccountsFailure the binding is accessed which no longer exists at that point. Solution is to only catch the expected IOException. Cancellation exception will be propagated and ignored. 
Also launch coroutines with view lifecycle to make sure binding is always available.
```
Exception java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
at androidx.fragment.app.Fragment.getViewLifecycleOwner (Fragment.java:377)
at com.keylesspalace.tusky.util.FragmentViewBindingDelegate.getValue (ViewBindingExtensions.kt:56)
at …
```
=> fix crash in AccountListFragment when network calls are cancelled

app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/com/keylesspalace/tusky/db/TimelineDao.kt
Fixes a crash (class cast of a Placeholder) when tapping a reply in a conversation in the notfications and that conversation is then loaded starting with that reply.
I'm not really sure if this is correct/sufficient there. Or if for example that debug output ("Loaded status from network") is still correct.
@nikclayton 
Stems from: https://github.com/tuskyapp/Tusky/pull/3118
(Unfortunately there is no issue attached there.)
That is the exception: StatusViewData$Placeholder cannot be cast to com.keylesspalace.tusky.viewdata.StatusViewData$Concrete
=> Check for status "type" before casting (class cast exception Placeholder)

app/src/main/java/com/keylesspalace/tusky/db/DraftDao.kt
"true" and "false" are not available before SQLite  3.23 / Android 11
> SQLite recognizes the keywords "TRUE" and "FALSE", as of version 3.23.0 (2018-04-02) but those keywords are really just alternative spellings for the integer literals 1 and 0 respectively. 
https://www.sqlite.org/datatype3.html
> API 30    3.28
API 28    3.22
https://developer.android.com/reference/android/database/sqlite/package-summary.html
closes #3230
=> Fix DraftDao queries on older SQLite

app/src/main/java/com/keylesspalace/tusky/components/notifications/PushNotificationHelper.kt
It is not guaranteed to be a `HttpException`, could be `IOException` as well
```
Exception java.lang.ClassCastException:
at com.keylesspalace.tusky.components.notifications.PushNotificationHelper$unregisterUnifiedPushEndpoint$2.invokeSuspend (PushNotificationHelper.kt:216)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run (LimitedDispatcher.kt:42)
at kotlinx.coroutines.scheduling.TaskImpl.run (Tasks.kt:95)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.java:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
at …
```
=> Fix crash when failing to unsubscribe push notifications

app/src/main/java/com/keylesspalace/tusky/util/ViewExtensions.kt
Verified by enabling "Pointer Location" in the developer options, and then experimenting to see which angles trigger opens of the nav. drawer, and in a stock "Tabbed Activity" generated in Android Studio (New > Activity > Tabbed Activity) that uses ViewPager2.
=> Set swipe scale factor to 2

app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt
Seems like a very rare edge case where the adapter finished updating after the fragment is already destroyed.
```
Exception java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
at androidx.fragment.app.Fragment.getViewLifecycleOwner (Fragment.java:377)
at com.keylesspalace.tusky.util.FragmentViewBindingDelegate.getValue (ViewBindingExtensions.kt:56)
at com.keylesspalace.tusky.components.viewthread.ViewThreadFragment.getBinding (ViewThreadFragment.kt:68)
at com.keylesspalace.tusky.components.viewthread.ViewThreadFragment.access$getBinding (ViewThreadFragment.java:61)
at com.keylesspalace.tusky.components.viewthread.ViewThreadFragment$onViewCreated$4$1.emit$lambda-1 …
```
=> fix crash in ViewThreadFragment

app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt
Original report in this thread: https://fosstodon.org/@gudenau/109785420799278861
Sometimes, shortcuts are kept around until after the corresponding account logged out. Clicking the shortcuts afterwards causes no account being marked as active which effectively logs all other accounts out as well.
Clicking invalid shortcuts can also result in null accounts being loaded in MainActivity:
```
java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at …
```
=> prevent the app from getting into an invalid state when old shortcuts are used

app/build.gradle
This worked in 21.0 but was broken by the gradle modernization patch (PR#3171)
Building with this patch I get the warning
> Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
I don't know if this is because I broke something or if it was printing that warning already.
=> Fix non-git build

CONTRIBUTING.md
Covers two things that would have originally helped me getting started if they were in a doc: The minimum required Android Studio version, and the difference between "blue" and "green".
=> Small "Building" section in CONTRIBUTING.md.

app/build.gradle
(using patch by @nikclayton)
#3296 worked for non-incremental builds but not incremental builds. So it would always work on the first try and fail on all subsequent tries. Apparently spooky gradle magic is needed here
=> Fix sporadic failure in non-git build

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/MediaPreviewAdapter.kt, app/src/main/java/com/keylesspalace/tusky/entity/Attachment.kt, app/src/main/java/com/keylesspalace/tusky/entity/NewStatus.kt, app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt
Completes #3211 
We could also add support for viewing them in the edit history view, but I think that will maybe not be super useful since that view is mainly for seeing the history of *other* people's statuses
Also fixes #3273
=> Add support for updating media description and focus point when editing statuses

app/build.gradle, app/getGitSha.gradle
https://github.com/tuskyapp/Tusky/pull/3299 fixed the non-git build, but unbeknowst to us, only by forcing the git build to always use the git hash "unknown". :(
This fix uses unusual code provided by Mikhail Lopatkin of Gradle Inc in an issue I filed on gradle complaining about our problems: 
https://github.com/gradle/gradle/issues/23914#issuecomment-1431909019
It wraps the git sha function in a "value source". This allows it to interact correctly with configuration caching. Because the code is longer than before, it is now broken out into its own file getGitSha.gradle.
I did more extensive tests than I did on the previous PR (with git, without git, with git but in a non-git repo) and it worked correctly and consistently on all of them. Changing the git hash but not changing any project …
=> Previous attempt to fix git sha on non-git build broke git build

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
Previous code was:
```
for (i in tabs.indices) {
// ...
if (tabs[i].id == LIST) {
tab.contentDescription = tabs[i].arguments[1]
} else {
tab.setContentDescription(tabs[i].text)
}
// ...
}
```
When I converted it over, `i` was replaced with `position`, but I misread `tab.contentDescription = tabs[i].arguments[1]` as `tab.contentDescription = tabs[i].arguments[i]`.
Put the `1` back.
=> Fetch list title from second value in arguments

app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsAdapter.kt
This ensures that the position is valid w.r.t. to the backing array.
Fixes https://github.com/tuskyapp/Tusky/issues/3333
=> Use the adapter position when responding to clicks on followed tags

app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt
Partially related to 3170e1ce7167
Moved code to show UI to `OnPreparedListener` because internally `VideoView` calls `MediaController#setEnabled()`  in `onPrepared()`. Calling `MediaController#show()` before `MediaController#setEnabled()` will have no effect.
Testing
- Open audio attachment: https://solarpunk.moe/@vv/109562659215759090
- Ensure media control UI and alt text is shown once playback starts
Fixes https://github.com/tuskyapp/Tusky/issues/3261
=> Fix media controller UI not showing during audio playback

app/src/main/java/com/keylesspalace/tusky/util/ViewBindingExtensions.kt
Fragments can go `onCreate` -> `onCreateView` -> `onViewCreated` -> `onDestroyView` without transitioning through `onStart`.
The previous code assumed `onStart` was always called. 
Se https://itnext.io/an-update-to-the-fragmentviewbindingdelegate-the-bug-weve-inherited-from-autoclearedvalue-7fc0a89fcae1
=> Fix lifecycle handling bug

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/AccountPreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/util/LocaleUtils.kt, app/src/test/java/com/keylesspalace/tusky/util/LocaleUtilsTest.kt
Ensures that all of (language of the post being replied to, default post language, configured app languages, configured system languages) are prioritized when constructing the language list for composing, regardless of whether any of those are languages android knows about.
Partially addresses #3277
=> Improve language list prioritization

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java, app/src/main/java/com/keylesspalace/tusky/receiver/SendStatusBroadcastReceiver.kt
=> 2528: Do not remove notifications on general resume

app/src/main/java/com/keylesspalace/tusky/TuskyApplication.kt, app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt
Every nightly release has a new BuildConfig.VERSION_CODE, so the previous code would not do the right thing.
Require the schema version to be explicitly set. While I'm here, provide a clear set of guidelines as to what has to happen when the schema changes.
=> Use an explicit SCHEMA_VERSION instead of BuildConfig.VERSION_CODE

app/src/main/java/com/keylesspalace/tusky/BottomSheetActivity.kt, app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt
=> When looking up fediverse urls, verify that account results returned match the input query

app/src/main/java/com/keylesspalace/tusky/components/viewthread/edits/ViewEditsAdapter.kt
=> Perform unicode text isolation on user names in post edit history view

app/proguard-rules.pro
Suppress some warnings, this is necessary for upgrading AGP 8, we can remove these rules after updating to OkHttp 4.10.x.
```
> Task :app:minifyBlueReleaseWithR8
AGPBI: {"kind":"warning","text":"Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/goooler/StudioProjects/Tusky/app/build/outputs/mapping/blueRelease/missing_rules.txt.\n","sources":[{}]}
Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/goooler/StudioProjects/Tusky/app/build/outputs/mapping/blueRelease/missing_rules.txt.
AGPBI: {"kind":"warning","text":"Missing class com.android.org.conscrypt.SSLParametersImpl (referenced from: void …
```
=> Add extra proguard rules for OkHttp

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
`LinkMovementMethod` has a bug in its calculation of the clickable width of a span on a line. If the span is the last thing on the line the clickable area extends to the end of the view. So the user can tap what appears to be whitespace and open a link.
Previous code tried to fix this by adding a zero-width space after the link so that `LinkMovementMethod` wouldn't consider it empty. However the ZWS was selected by copy/paste operations, resulting in junk results if users tried to copy the link.
Fix this by subclassing `LinkMovementMethod` and fixing the click detection code to ignore clicks that are outside the bounds of the line that was clicked on.
Remove the code that adds the ZWS.
Fixes https://github.com/tuskyapp/Tusky/issues/1567
=> Ignore clicks outside the start/end of a line

app/build.gradle
Not all Robolectric tests interact with activities, so lazy loading the activity can speed them up.
I benchmarked the impact with gradle-profiler. Each test run performed 6 warmup runs, and then 10 benchmarked runs with and without this change.
Without this change (all values rounded to nearest second):
Mean: 151
Median: 149
P75: 157
StdDev: 10
With this change:
Mean: 127
Median: 125
P75: 130
StdDev: 7
So a ~ 18% reduction in median and P75 times,
=> Lazily load activities in Robolectric tests

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java
When the spoiler warning is toggled, we update the ViewHolder immediately, but until now the "show more/less" button of collapsible posts and the link preview card were not included in this immediate update. The subsequent update through the rebinding of the ViewHolder sets their state correctly but a weird two step animation occurs, were first the post content is shown/hidden, and in a second step the card. This always felt extremely glitchy to me, I'm glad I could fix it.
Here you can see the glitch but it happens very quickly:
https://user-images.githubusercontent.com/10157047/221639655-03a56165-69b2-4dd9-b15c-a74643e0828b.mp4
I also experimented with removing the immediate updates completly and relying on the adapter rebind entirely, but that makes it feel a bit laggy so I went this …
=> include card and collapsed state in instant expanded change

gradle.properties
Per https://developer.android.com/studio/build/optimize-your-build#experiment-with-the-jvm-parallel-garbage-collector
I benchmarked this, and p75 incremental build time dropped from 33s to 30s.
https://github.com/gradle/gradle/issues/19750 means that if `org.gradle.jvmargs` is set any unchanged default values are lost, so include those too.
=> Enable parallel GC for Gradle builds

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsPagingSource.kt
The previous code returned the text representation of the error body type, which resulted in errors appearing in the UI as:
```
okhttp3.ResponseBody$Companion$asResponseBody$1@...
```
This code actually converts the *body* of the error response to a string, so the error is displayed correctly.
=> Fix UI error, return the actual error body as a string

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/main/java/com/keylesspalace/tusky/util/NoUnderlineURLSpan.kt, app/src/main/java/com/keylesspalace/tusky/util/SpanUtils.kt, app/src/test/java/com/keylesspalace/tusky/SpanUtilsTest.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeActivity/ComposeActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeActivity/StatusLengthTest.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeTokenizer/ComposeTokenizerTest.kt
In a status with a mention ("@foo@example.org") only the "@foo" part should be included in the calculated status length. It wasn't, so the app was preventing people from posting statuses that should have been allowed.
Fix this.
- Lift the length calculation code in to a separate static function (easier and faster to test)
- Add a `MentionSpan` type, to reuse existing code for detecting mentions
- Fix a bug in `FakeSpannable.getSpans()` (it was returning the outer type, not the wrapped inner span)
- Add additional fast tests
The tests made sense under the `components.compose.ComposeActivity` package, so I also created that and moved the existing ComposeActivity tests there.
Fixes https://github.com/tuskyapp/Tusky/issues/3339
=> Ignore "@instance..." part of username when computing status length

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/res/menu/status_favourite.xml, app/src/main/res/menu/status_reblog.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
The previous code used dialogs and displayed the text of the status when reblogging or favouriting.
This didn't work when the post just contained images, and other material from the status (content warning, polls) was not shown either.
Fix this by displaying a popup menu instead. The status remains visible so the user can clearly see what they're acting on.
In addition, this lays the groundwork for supporting a long-press menu in the future to allow the user to reblog/favourite from a different account.
Fixes https://github.com/tuskyapp/Tusky/issues/3308
=> Show reblog/favourite confirmations as menus not dialogs

Release.md, bitrise.yml
Automatic release pipeline makes it easier to build, sign and upload the release. The changelog prepared for F-Droid will also be used for the Google Play release.
=> update release process

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsPagingSource.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsRepository.kt, app/src/main/java/com/keylesspalace/tusky/entity/Error.kt, app/src/test/java/com/keylesspalace/tusky/components/notifications/NotificationsPagingSourceTest.kt
The errors are returned as a JSON object, parse it, and show the error message it contains.
Handle the cases where there might be no error message, or the JSON may be malformed.
Add tests.
Fixes #3445
=> Show better errors when loading notifications fails

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt
This one's missing.
(Be on notifications timeline, get bing of new notifications, refresh should be the same as resume.)
=> #2528: Also clear notifications on refresh in notifications timeline

.editorconfig
Out-of-the-box Android Studio will perform wildcard imports if the import list is >= 3. This is a lint failure.
Adjust the default to 999 so that, in practice, wildcard imports never happen.
=> Disable wildcard imports for Java and Kotlin files

app/src/main/java/com/keylesspalace/tusky/components/account/AccountViewModel.kt
Found while looking at Google crash reports.
I checked a few other "[0]" in the code. Most are guarded by a "isNotEmpty" but some are not.
For example in `searchAutocompleteSuggestions`.
=> Do not crash on empty relationship response

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt
Use `getOrNull` instead of `get`, which was occasionally throwing IndexOutOfBoundsException.
=> Fix IndexOutOfBoundsException in onPause

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
Avoid showing the user the things they have filtered on when showing a filter placeholder in a timeline.
Fixes https://github.com/tuskyapp/Tusky/issues/3587
=> Show filter title instead of filter keywords

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsRepository.kt
The pageSize is large enough that there's no need for the default 3 x pageSize initialLoadSize value, and this improves performance.
Fixes https://github.com/tuskyapp/Tusky/issues/3578
=> Set initialLoadSize = pageSize

app/src/main/res/layout/item_status_notification.xml
Add additional 6dp margin to the top of the username view, to provide more space after the "X <performed an action>" view, consistent with item_follow.xml and previous iterations of this layout.
=> Add additional margin after the "X <performed an action>" view

app/src/main/java/com/keylesspalace/tusky/components/filters/FiltersActivity.kt
On Account preferences > Filters
With the list hidden on an empty view the FAB is erroneouly placed on the top left of the screen.
(Introduced with #3430)
=> #3430: (fix) do not hide the anchor of the FAB

app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
without the `suspend` it throws `android.os.NetworkOnMainThreadException`
relevant for #3551
=> fix reporting

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsPagingSource.kt
Requesting a non-existent notification ID will cause the fall-back requests to succeed but return empty lists which stops pagination.
Check for this, and in the worst case, fall back to returning the most recent notifications.
=> Check for non-empty pages when falling back

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
Previous code had an IndexOutOfBoundsException where tab.position could be larger than the tabs array.
=> Use the tab's contentDescription as the toolbar title

app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt
from Google Play console
```
Exception java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.get (ArrayList.java:437)
at java.util.Collections$UnmodifiableList.get (Collections.java:1356)
at com.keylesspalace.tusky.components.viewthread.ViewThreadFragment.removeItem (ViewThreadFragment.kt:419)
at com.keylesspalace.tusky.fragment.SFragment$showConfirmDeleteDialog$1$1.invokeSuspend (SFragment.kt:364)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
at android.os.Handler.handleCallback (Handler.java:938)
at android.os.Handler.dispatchMessage (Handler.java:99)
at android.os.Looper.loopOnce (Looper.java:226)
at android.os.Looper.loop (Looper.java:313)
at …
```
=> fix crash in ViewThreadFragment.removeItem

app/src/main/java/com/keylesspalace/tusky/entity/FilterResult.kt
This was a Mastodon documentation bug, and is being fixed on their side in https://github.com/mastodon/mastodon/issues/24900.
=> FilterResult.status_matches is a List<String>?

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationFetcher.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
Otherwise markers are updated for the wrong account.
Fixes https://github.com/tuskyapp/Tusky/issues/3658
=> updateMarkersWithAuth(): Require DOMAIN header

README.md
As discussed we don't want any figureheads but instead run this project as a team
=> Delete "head of development" section from readme

app/schemas/com.keylesspalace.tusky.db.AppDatabase/51.json, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationFetcher.kt, app/src/main/java/com/keylesspalace/tusky/db/AccountEntity.kt, app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java
Not all servers support the marker API. If they don't the user will potentially get duplicate Android notifications.
To resolve this, store a copy of the notification marker ID locally as well. Defer to the remote marker if it exists (and is newer than the local marker).
Fixes https://github.com/tuskyapp/Tusky/issues/3671
=> Save a copy of the notification marker ID locally

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt
The previous code gets the user's reading position *once*, when the viewmodel is created, and uses that whenever it needs to be restored.
This is a problem. Suppose the user is a few days behind on their notifications, and opens the app.
The reading position is restored, as expected. They scroll up to start reading newer notifications.
Then they change their notification filters. This causes the notifications list to change, and when it does their reading position is set back to what it was when they first switched to the Notifications tab.
Fix this by:
NotificationsFragment:
- Save the reading position whenever the user stops scrolling.
NotificationsViewModel:
- Use the saved reading position whenever the list of notifications can change, not just when the view model is created.
=> Save and restore the user's reading position more frequently

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt
Fix a bug where the active account can be overwritten.
1. Have two accounts logged in to Tusky, A and B
2. Open Tusky as account A
3. Send a DM to account B (doesn't have to be a DM, just anything that creates a notification for account B)
4. Restart Tusky so the Android notification for the DM is displayed immediately. You are still acting as account A.
5. Drag down the Android notification, you should see two options, "Quick reply" and "Compose"
6. Tap "Compose"
7. ComposeActivity will start. You are now acting as account B. Compose and send a reply
8. You'll be returned to the "Home" tab.
The UI will show you are still account A (i.e., it's account A's avatar at the top of the screen, if you have the "Show username in toolbars" option turned on it will be account A's username in the …
=> Don't overwrite the active account when composing from a notification

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt
Don't use `accountManager.activeAccount` throughout the code.
Instead, get the active account once, and use that over the life of the viewmodel.
As shown in https://github.com/tuskyapp/Tusky/issues/3689#issuecomment-1567219338 the active account can change before the view model is destroyed, and if that happens account information for the account will be written to the wrong account.
=> Write notification account information to the correct account

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationFetcher.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsPagingSource.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
Previous code fetched the oldest page of unfetched Mastodon notifications.
If you had more than a page of Mastodon notifications you'd get Android notifications for that page, then ~ 15 minutes later Android notifications for the next page, and so on.
This code fetches all the outstanding notifications at once.
If this results in more than 40 total notifications the list is still trimmed so that a maximum of 40 Android notifications is displayed.
Fixes https://github.com/tuskyapp/Tusky/issues/3648
=> Fetch all outstanding Mastodon notifications when creating Android notifications

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/util/FlowExtensions.kt, app/src/test/java/com/keylesspalace/tusky/util/FlowExtensionsTest.kt
Introduce Flow<T>.throttleFirst(). In a flow this emits the first value, and each value afterwards that is > some timeout after the previous value.
This prevents accidental double-taps on UI elements from generating multiple-actions.
The previous code used debounce(). That has a similar effect, but with debounce() the code has to wait until after the timeout period has elapsed before it can process the action, leading to an unnecessary UI delay.
With throttleFirst a value is emitted immediately, there's no need to wait. It's subsequent values that are potentially throttled.
=> Throttle UI actions instead of debouncing

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/res/menu/fragment_notifications.xml, app/src/main/res/values/strings.xml
- Create a flow with new items (arbitrary ints) when a reload from the top should happen
- Combine this flow with notificationFilter, so changes to either of them trigger a reload
- Provide a menu item in NotificationsFragment to initiate the reload
- Handle the action in the view model
=> Add a menu option to load the newest notifications

app/src/main/java/com/keylesspalace/tusky/util/CustomEmojiHelper.kt
closes https://github.com/tuskyapp/Tusky/issues/635
Instead of forcing all emojis to be square, only the width is fixed now and the emoji scaled to fit.
For testing, check the replies to this post https://chaos.social/@ConnyDuck/110490834316501211
=> correctly show non-square custom emojis

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt, app/src/main/res/values/strings.xml
address #3576 
I'm sort of following https://github.com/tuskyapp/Tusky/issues/3576#issuecomment-1527504752.
When the user is closing the compose view,
- if it's new and empty, don't show a prompt.
- if it's an existing draft and now empty, ask if the user wants to delete it or continue editing. I don't think there is much value in saving an empty draft.
=> Improve prompt when draft is empty

app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/account/list/ListsForAccountFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/account/media/AccountMediaFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/accountlist/AccountListFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/instancemute/fragment/InstanceListFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledStatusActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/edits/ViewEditsFragment.kt, app/src/main/java/com/keylesspalace/tusky/util/ThrowableExtensions.kt, app/src/main/java/com/keylesspalace/tusky/view/BackgroundMessageView.kt, app/src/main/res/values/strings.xml
Instead of repeating the same if/else check on the error type when setting up the background message, move this in to BackgroundMessageView.
Provide different `setup()` variants, including one that just takes a throwable and a handler, and figures out the correct drawables and error message.
Update and simplify call sites.
=> Simplify repeated code that shows errors

app/lint-baseline.xml, app/src/main/java/com/keylesspalace/tusky/TuskyApplication.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationFetcher.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java, app/src/main/java/com/keylesspalace/tusky/worker/NotificationWorker.kt, app/src/main/java/com/keylesspalace/tusky/worker/PruneCacheWorker.kt, app/src/main/res/values/strings.xml
Fix a crash where workers, in some conditions, should show a notification, but didn't.
These new notifications are sent to a dedicated channel with no importance.
Convert `NotificationWorker` to a `CoroutineWorker` and remove its use of `runBlocking`.
Fixes #3754
=> Show notifications from workers

app/src/main/java/com/keylesspalace/tusky/adapter/AccountFieldEditAdapter.kt
Fixes https://github.com/tuskyapp/Tusky/issues/3807
=> Fix ArrayIndexOutOfBoundsException

app/lint.xml
The typo database that lint uses may be incorrect, and it's unclear how to add or remove entries to it.
=> Convert lint "Typos" errors to warnings

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
GBoard and other IME's support pasting images, which are converted to attachments.
Sometimes these have labels that describe the image. If present, set it as the default alt-text.
Fixes #3799
=> Set default alt-text to media label when pasting images

app/lint.xml
`OldTargetApi` default behaviour is to warn (https://googlesamples.github.io/android-custom-lint-rules/checks/OldTargetApi.md.html)
Set it back to that, so that CI runs on runners with newer versions of the SDK installed do not fail.
=> Set OldTargetApi to a warning

app/src/main/res/layout/fragment_view_thread.xml
Fixes an issue where the view's width is only enough to wrap the image, resulting in a very narrow view that obscures the text of the error.
=> Set statusView width/height to match_parent

app/src/test/java/com/keylesspalace/tusky/util/AbsoluteTimeFormatterTest.kt
Fixes #3859: As tests are run against locale JVM and test does not force a locale to run, so some tests may fail due to a different result only due to the locale of the JVM used.
Example here with test `same year formatting` in class `AbsoluteTimeFormatterTest` line 30 on a French JVM. There may be other lines to fail with other languages.
=> Fixes #3859: Ensures AbsoluteTimeFormatterTest class is not locale-dependant

app/src/main/java/com/keylesspalace/tusky/view/SliderPreference.kt
Preferences are shown using view holders.
The previous code did not clear the listeners or hide the icons if necessary.
The practical upshot of this was that if you had two or more slider preferences, *and* they were situated more than a screen's height apart, the viewholder from the first one would get reused.
And if the first one enabled icons then the second one would show them. And clicking on the second one would also call the listeners for the first one.
=> Clear listeners, hide icons when appropriate

app/lint-baseline.xml, app/lint.xml, gradle.properties
Android lint was erroneously warning that the forEach construct in Kotlin required API 24+, which is incorrect, see https://issuetracker.google.com/issues/185418482.
Work around that by forcing the Android lint version to 8.1.0.
This triggered some additional checks, which have been ignored, and a new baseline.
=> Use lint version 8.1.0 to fix erroneous warning about forEach

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
The previous code used `notificationTabPosition`, which was never changed, so always 0.
This meant that if you e.g., got to `MainActivity` by clicking on a notification, and the notification tab was current, the title would still show "Home".
Fix that by using the existing `position` variable which represents the currently selected tab, and ensure the correct title is shown.
Fixes #3864.
=> Show the correct tab title when opening the activity

app/src/main/res/layout/view_compose_schedule.xml
The "edit" icon when showing a scheduled status' time was grey, so it's not obvious that this section is clickable.
Use colorPrimary, so it looks more like a button.
=> Use colorPrimary for the "edit" schedule icon

.github/workflows/populate-gradle-build-cache.yml
The build cache is used in ci.yml to speed up builds, but it needs to be populated by building code that's been merged.
=> Populate gradle build cache on each push to develop

app/src/main/java/com/keylesspalace/tusky/components/preference/TabFilterPreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/settings/SettingsDSL.kt
Nowhere else in the preferences are checkboxes used.
Also removed the now unused extension function.
Fixes #3535.
| Before | After |
|--------|--------|
| <img src="https://github.com/tuskyapp/Tusky/assets/1063155/41f61713-3a59-4eb5-a625-992a7c39f426" width=320 /> | <img src="https://github.com/tuskyapp/Tusky/assets/1063155/8823e652-a6d3-405a-8901-ffa538f0fdfd" width=320 />|
=> Filters> Tabs: use checkbox instead of switch

app/src/main/java/com/keylesspalace/tusky/BottomSheetActivity.kt
=> Use case-insensitive checks when comparing account URLs in search

app/src/main/res/layout/item_status_detailed.xml
While the status text in the detailed layout was selectable, CW description wasn't.
Also made both CW and text selectable when viewing edits.
Fixed layouts:
- `item_status_detailed.xml`: from the bug report
- ~~`item_status_edit.xml`: I deemed it worth it to fix it there too~~
Reviewed but not made selectable:
- `item_status.xml`: as tapping on the view opens the detailed view and adding a long press to select gesture could make UX confusing
- `item_status_notification.xml`: as tapping on the notification launches the app
Fixes #3826.
=> Make CW description selectable

.github/ci-gradle.properties, .github/workflows/ci.yml, .github/workflows/populate-gradle-build-cache.yml
Expectation is that these will result in faster builds by disabling options (like the gradle daemon) that benefit long-lived processes but do not benefit ephemeral build workers.
=> Provide specific gradle properties for builds on CI

app/src/main/res/layout/item_media_preview.xml, app/src/main/res/layout/item_report_status.xml
Using the same background and margin as the ALT button.
| Before| After |
|--------|--------|
| <img src="https://github.com/tuskyapp/Tusky/assets/1063155/d9a862fa-c1b5-4f65-b27a-d223cbfb2c3d" width=320 /> | <img src="https://github.com/tuskyapp/Tusky/assets/1063155/c4e77eb9-eeef-4995-b4b7-9d4fbdf6bacd" width=320 /> |
| <img src="https://github.com/tuskyapp/Tusky/assets/1063155/0d1565b8-ee3b-43ec-8b88-7e4a51d8da4a" width=320 />| <img src="https://github.com/tuskyapp/Tusky/assets/1063155/d633df7c-77ef-4b84-98c0-e6a6151b67e8" width=320 /> | 
Fixes #3772
=> Add background to sensitive media button

app/src/main/java/com/keylesspalace/tusky/components/filters/EditFilterActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/FilterExtensions.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/FiltersActivity.kt, app/src/main/java/com/keylesspalace/tusky/util/AlertDialogExtensions.kt, app/src/main/res/values/strings.xml
* Prevent users from accidentally deleting filters by prompting them to confirm.
* The code to delete a filter is untouched, I simply inserted the AlertDialog in the middle (where it applies).
* Added corresponding Strings.
#3736 
<details>
<summary>Screenshots</summary>
</details>
=> Prompt the user before deleting a Filter. (#3736)

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/account/AccountViewModel.kt
Fixes #3798.
I was not sure if I should put the domain comparison in the `Activity` (since it seems to keep some state and there is code there already accessing `AccountManager`) or in `ViewModel` (to me, this is the "right place" for it to be, being more encapsulated and easier to test, were this class already tested).
How do you feel about converting the cascading `if/else` to a `when` statement?
Also, should I do a case insensitive comparison, as in https://github.com/tuskyapp/Tusky/pull/3931? I opted not to, as the problematic case there was about casing for the username/handle, not the domain portion.
=> Account: hide option to mute own domain (it is a no-op).

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java
https://github.com/tuskyapp/Tusky/commit/dc9e9f2aebfd3feb057fee4c3ac72b05cbc75a12 modifed the code that fetched the value of EXTRA_NOTIFICATION_TYPE in an intent, to use getSerializable().
However, the value was being placed in to the intent using putString().
This caused an exception when trying to update the summary notification, so it would never update.
```
java.lang.ClassCastException: java.lang.String cannot be cast to com.keylesspalace.tusky.entity.Notification$Type
at com.keylesspalace.tusky.components.notifications.NotificationHelper.updateSummaryNotifications(NotificationHelper.java:321)
at com.keylesspalace.tusky.components.notifications.NotificationFetcher.fetchAndShow(NotificationFetcher.kt:87)
at com.keylesspalace.tusky.components.notifications.NotificationFetcher$fetchAndSho …
```
=> Fix exception when updating summary notifications

bitrise.yml
Reverts tuskyapp/Tusky#3840. Turns out this needs to be enabled at Bitrise, and it's not on our plan. So every build is running this extra workflow, but it's not providing any benefit, just slowing things down.
=> Revert "Enable gradle build cache for Bitrise builds"

README.md
Our Matrix link goes to riot.im. Riot has been renamed to Vector and the riot.im frontpage now redirects to element.io. Since most users will now be using Element not riot.im, the riot link will (although it will partially work) not work as expected.
Vector now recommends Space links use matrix.to, which is a pretty neat site that will forward the space invite to the user's preferred Matrix frontend *even if it is not Element*. So we should use that.
=> Fix link to Matrix in README

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
=> fix links sometimes being underlined

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/test/java/com/keylesspalace/tusky/util/LinkHelperTest.kt
While helping test an issue with [Bookwyrm](https://github.com/bookwyrm-social/bookwyrm) I noticed that the URL formats used by that project aren't checked as possible profile or post links. They're quite close to a couple of others, so I just copied close examples and edited a couple of terms.
It's pretty minor, I just used a previous commit as a reference. Let me know if it needs anything more though. I've only quickly tested it on a local build with a couple of links against a live Bookwyrm and it picks them up as expected now.
=> Detect Bookwyrm URL formats

.editorconfig, app/src/main/java/com/keylesspalace/tusky/components/report/Screen.kt, app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledStatusActivity.kt
Trailing commas on Kotlin sources [has many advantages](https://pinterest.github.io/ktlint/0.49.0/rules/standard/#trailing-comma-on-call-site):
- It makes version-control diffs cleaner – as all the focus is on the changed value.
- It makes it easy to add and reorder elements – there is no need to add or delete the comma if you manipulate elements.
- It simplifies code generation, for example, for object initializers. The last element can also have a comma.
This PR doesn't go as far as require it, but tweaks KtLint to at least allow it.
The two `.kt` files prove that the KtLint rules have been properly disabled.
=> Kotlin - Enable trailing comma

gradle/libs.versions.toml
I moved the library from Jitpack to Maven Central and changed the group id (so renovate won't pick that up), other than that there is only a dependency upgrade to `androidx.appcompat:appcompat:1.6.1` included
=> update SparkButton to 4.2.0

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java, app/src/main/java/com/keylesspalace/tusky/entity/Notification.kt
Not quite sure why/when this happens - every stack trace is not our code, but I do get an ClassNotFoundException for Notification$Type with the new reverted code.
The notification fetching (worker) then stops/crashes so I never get an Android notification.
It might have something to do with https://github.com/tuskyapp/Tusky/pull/3732 ?
=> Avoid crash on notification worker

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/account/AccountViewModel.kt, app/src/main/java/com/keylesspalace/tusky/entity/Account.kt, app/src/main/res/drawable/profile_badge_background.xml, app/src/main/res/drawable/profile_badge_person_24dp.xml, app/src/main/res/layout/activity_account.xml, app/src/main/res/values/dimens.xml
This adds support for the new Mastodon 4.2 role badges. Admins can define if a role should be visible in the interface and then we get it delivered by the Api on the `Account` object like this:
```
"roles": [
{
"id": "4",
"name": "TEST",
"color": "#ffee00"
}
]
```
- keeps compatibility with older Mastodon version and non Mastodon servers
- Took me a while, but I figured out a way to use the color and have it look ok on all backgrounds (Mastodon itself ignores the color and just always uses its brand color)
- falls back to Tusky blue in case no color is configured
- I adjusted the "Follows you" and "Bot" badges so they match the new badge style
- In case the "Follows you" and "Bot" badges are visible at the same time, "Follows you" gets its own line and "Bot" goes into the same line as the …
=> add role badges

app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt, app/src/main/java/com/keylesspalace/tusky/util/AdaptiveTabLayout.kt, app/src/main/java/com/keylesspalace/tusky/view/AdaptiveTabLayout.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_tab_preference.xml, app/src/main/res/values/strings.xml
Fixes #2512 
Can add an arbitrary number of tabs.
Graphical behavior is unchanged for small numbers: the whole space if filled with the tabs - they are enlarged if needed.
If there are more the mode switches to "scrollable".
This does not, however, look very differently (see screenshot with the current tab scrolled out).
=> 2512: Allow more than 5 tabs

app/src/main/res/color/tab_color.xml, app/src/main/res/layout/activity_main.xml
Tries to fix the random colors for tabs on the bottom after #4051.
Does not work yet: The "selected" color does not take effect.
=> 2512: Fix random tab colors

app/schemas/com.keylesspalace.tusky.db.AppDatabase/54.json, app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/appstore/Events.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationFetcher.kt, app/src/main/java/com/keylesspalace/tusky/db/AccountEntity.kt, app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java, app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.kt
Fixes #3532
(Old PR, now closed: https://github.com/tuskyapp/Tusky/pull/3533)
Listens on new notifications and if a "direct mention" is detected a badge (red dot) is shown on the conversations tab if present.
I am missing things like this a lot and also big accounts are unhappy with the usability so far: https://mastodon.social/@pallenberg/110129889996182814
=> 3532: Show badge on conversations tab on new conversations

app/src/main/res/layout/exo_player_control_view.xml
In the new Tusky version, we switched from "old and busted" Android video player to "Exoplayer". This PR # 3857 was a collaboration between Nik and me.
In Nik's final commit, there is a dark "curtain" that displays on top of all videos, under the controls. I don't think this was ever discussed by anyone except me and Nik and I would like to revisit it. I find the curtain very distracting, it is like all videos display dark.
This patch removes the curtain, bringing closer to the Tusky 23.0 look. There are two problems:
- This means if you ever watch a video which has a white background and fills an entire screen, you will not be able to see the buttons. I think this problem was present in 23.0 but it is still a problem. Possible fixes: - Edit the buttons to give them backgrounds so they …
=> Customize exoplayer to remove dark "curtain" 

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt, app/src/main/res/layout/dialog_image_description.xml, app/src/main/res/values/strings.xml
Fixes: #4063
Switching from an AlertDialog to only a DialogFragment.
I didn't get the AlertDialog to be sized correctly.
It also opens now directly with the right (full screen) size. When the imageView fails to load (i.e. with an audio file) it will be hidden.
This changes the button layout somewhat.
One observation: The placeholder text "... visually impaired..." is not quite right as a description for an audio file is not intended for the visually impaired. But I couldn't think of a better text just yet.
=> 4063: Make dialog size more stable

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
1. install Gboard
(https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin)
2. open a direct link to any image in Firefox
3. long-press the image to get a "Copy Image" dialogue (and copy the
image)
4. compose a new post in Tusky
5. Gboard will suggest to paste the image from clipboard
6. paste image, see that when opening alt text editor, it is filled out
with this garbage string
Why is this bad? It's not when I just fix the alt text. But it breaks
every mechanism that is supposed to remind me of adding alt text.
It's hard to argue that this is within scope of Tusky but I also don't
see it getting fixed in Gboard, so here we go.
=> Remove garbage alt text from images attached via Gboard

app/src/main/java/com/keylesspalace/tusky/StatusListActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/drafts/DraftsActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/EditFilterActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/EditFilterViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/FiltersViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/instanceinfo/InstanceInfoRepository.kt, app/src/main/java/com/keylesspalace/tusky/components/login/LoginWebViewViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/com/keylesspalace/tusky/entity/Instance.kt, app/src/main/java/com/keylesspalace/tusky/entity/InstanceV1.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/java/com/keylesspalace/tusky/util/ThrowableExtensions.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeActivity/ComposeActivityTest.kt
=> Add support for v2/instance

app/src/main/res/layout/exo_player_control_view.xml, app/src/main/res/values/styles.xml
I [posted our new video player layout] on Mastodon for comments and multiple people said the buttons were too close together. I agree. I added some space (I eyeballed it, I made it bigger until it felt too big and then I narrowed it), I think we have now increased the space from 10dp to 25dp. I added the space by wrapping the buttons in LinearLayouts, because they are <include>s and could theoretically insert more than one button.
Concerns: If the "next"/"prev" buttons ever become active, the space will not be correctly applied to those. We can fix that if it ever comes up (we don't display those buttons). If people think the buttons should be placed even further apart we can do this by just increasing the number in styles.xml.
This is what it looks like now. See previous look and …
=> Exoplayer: Increase space between rewind, pause, ffwd buttons

app/src/main/java/com/keylesspalace/tusky/components/viewthread/edits/ViewEditsAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/edits/ViewEditsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/util/StatusParsingHelper.kt
=> Support code blocks

renovate.json
Notice this was done upstream in https://github.com/mastodon/mastodon/pull/26306 by one of the Renovate people, so thought it would make sense here too
=> Use Renovate recommended baseline

app/src/main/java/com/keylesspalace/tusky/components/preference/TabFilterPreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt, app/src/main/res/values/strings.xml
Some Mastodon posters have a annoying habit of boosting their own posts some time after they've posted them.
No need to see the same toot over and over again.
- Add an additional option to the "Filters > Tabs" preference to show these self-boosts (default: on)
- If "Show boosts" is turned off, self-boosts are automatically hidden.
***screen of "Filters > Tabs" preference***
before | after
:--: | :--:
| <image src="https://github.com/tuskyapp/Tusky/assets/62137820/16ed2f4a-0776-4f60-afe6-29827acf5bbd" width="300"> |<image src="https://github.com/tuskyapp/Tusky/assets/62137820/9d4e1457-f71d-440c-959f-b91f7433b29a" width="300" />
***screen of Home Timeline***
***switch-on(self-boosts are displayed)*** | ***swith-off(self-boosts are not displayed)***
:--: | :--:
| <image …
=> feat: Hide self-boosts (#3534)

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationFetcher.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java
Fixes #3820 
This mainly corrects the "first of batch" logic.
(Each group/batch has a list so the question "only one per this group?" can be answered.)
=> 3820: Group android notifications and properly use the "group summary alert"

app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt, app/src/main/res/layout/fragment_view_video.xml
When viewing a video in Tusky, there is a top toolbar where the description is shown and the bottom toolbar where play, forward, backward, and scrub controls are found. In both Tusky 23 and the new media3 video player code, the logic for showing these toolbars is *unrelated*; Tusky catches tap events and shows and hides the description, and the Android media library separately catches tap events and shows and hides the bottom toolbar. Meanwhile, Tusky and the Android media library each separately manage a set of logic for auto-hiding their respective toolbars after a certain number of seconds has passed. This all results in several problems:
- The top and bottom toolbars can desync, so that one is visible and the other is not, and tapping to show/hide after this will only swap which one …
=> Regularize show/hide logic for video player scrub/play controls (fixes #4073)

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
Steps to reproduce: Open the dialog to set a catption on an image. Rotate the screen.
<details>
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
at com.keylesspalace.tusky.components.compose.dialog.CaptionDialog.onCreateView (CaptionDialog.kt:61)
at androidx.fragment.app.Fragment.performCreateView (Fragment.java:3114)
at androidx.fragment.app.DialogFragment.performCreateView (DialogFragment.java:775)
at androidx.fragment.app.FragmentStateManager.createView (FragmentStateManager.java:557)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:272)
at androidx.fragment.app.FragmentStore.moveToExpectedState …
```
=> fix crash when rotating caption dialog

app/src/main/res/values/strings.xml
This changes one word in the string `pref_failed_to_sync` in the file `values/strings.xml`.
See my reasoning here #4133 
"Failed to sync settings" changes to "Failed to sync preferences".
=> Reword the string "pref_failed_to_sync"

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/util/CompositeWithOpaqueBackground.kt
Found with Leak canary: The transformation ends up in Glide's memory cache and leaks whole Activities through the view -> context reference.
This fixes the problem by removing the background detection logic (so the view reference is no longer needed) and setting the background directly instead. Looks exactly as before.
=> fix memory leak in CompositeWithOpaqueBackground

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeActivity/ComposeActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeTokenizerTest.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/StatusLengthTest.kt
Thx to @evant for the help 
closes #4140
=> correctly count emojis when composing a post

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
Another fix for a memory leak. This one is not as big as #4150, but still worth fixing for memory constrained devices imo.
The `DrawerImageLoader` implementation (a global singleton) references a member of the `MainActivity`, causing the whole activity to leak.
This weird construct was introduced in #1989 to fix a crash, but I think since we migrated to coroutines it is no longer necessary because all calls get correctly cancelled. I tried reproducing the crash but could not, so I'm pretty sure it is fine. I would appreciate it if someone else could try it as well though.
(The crash could be reproduced on slow internet, when `onFetchUserInfoSuccess` was called while the activity was being destroyed, causing Glide to crash the app because it can't use destroyed activities. …
=> prevent MainActivity from leaking through the DrawerImageLoader singleton

app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt
We got reports on Mastodon that the media3 upgrade broke this previously functional behavior. In my testing, this restores the v23 behavior.
Note, @Gryzor suggested we do this with a Wake Lock. After looking at the docs, I conclude that (1) a wake lock is not what v23 was using, and is not appropriate for video but (2) a wake lock *is* appropriate for audio and possibly other purposes, and we should consider adding one in the v25 timeframe. I will file a followup issue explaining what I mean by this later today.
=> Prevent device from dimming or sleeping screen while video/audio playing

app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt
For reasons not totally clear to me, Github marked #4160 as "merged" and will not let me reopen it.
I believe this should be included for 24.1 because it fixes a 24.0 regression in the media player.
I have tested this newest commit in a number of ways, and in my testing I find (1) when viewing an image, it sleeps after about a minute (2) when viewing video, it stays awake indefinitely (3) this is true whether the image/video was opened directly, or reached by swiping from another attachment. I have not tested swiping to/from audio but I am confident it will work the same.
=> Prevent device from dimming or sleeping screen while video/audio playing (but really)

app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.keylesspalace.tusky.test/com.keylesspalace.tusky.ViewMediaActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at …
```
=> fix crash when opening profile image

app/src/main/java/com/keylesspalace/tusky/util/SpanUtils.kt
@Lakoja do you remember why you added that version check? Removing it fixes the bug.
Before / after
closes #4175
=> fix icon alignment in help text of empty timelines

app/src/main/java/com/keylesspalace/tusky/view/ClickableSpanTextView.kt
<details>
```
java.lang.ClassCastException: java.lang.String cannot be cast to android.text.Spannable
at com.keylesspalace.tusky.view.ClickableSpanTextView.dispatchTouchEvent(ClickableSpanTextView.kt:208)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
at …
```
=> fix ClassCastException in ClickableSpanTextView

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
Turns out that the crash I thought will not occur with #4153 did occur again. 😒 
But this time I managed to reproduce it (faking a slow network for that one request only and then quickly switching activities to get it destroyed) so I'm sure it is fixed, and I did a check for possible side effects but it seems Glide is clever enough to cancel all requests by itself.
<details>
<summary>stacktrace</summary>
```
Exception java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed (RequestManagerRetriever.java:236)
at com.bumptech.glide.manager.RequestManagerRetriever.get (RequestManagerRetriever.java:110)
at com.bumptech.glide.manager.RequestManagerRetriever.get …
```
=> fix Glide IllegalArgumentException in DrawerImageLoader

doc/Release.md
It is no longer necessary since we have lint checks.
Also fixed some typos.
=> remove string check step from Release.md

app/src/main/java/com/keylesspalace/tusky/TuskyApplication.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/AccountPreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/TabFilterPreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/db/AccountEntity.kt, app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java, app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt, app/src/main/java/com/keylesspalace/tusky/di/FragmentBuildersModule.kt, app/src/main/java/com/keylesspalace/tusky/settings/AccountPreferenceDataStore.kt, app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt, app/src/main/res/values/strings.xml
In the previous code, when you open preferences, there is a section headed "Filters" with a section called "Tabs"
This is confusing.
- Change the section title from "Filters" to "Per-timeline preferences."
- Change the current "Tabs" section to "Home timeline" since it is only for home timelines
account preference screen | detail screen
:--: | :--:
|<image src="https://github.com/tuskyapp/Tusky/assets/62137820/12694f24-b7e3-4ba3-90f5-53740e9c4269" width="250" />|<image src="https://github.com/tuskyapp/Tusky/assets/62137820/796e9ac1-76d6-43ef-a087-a1cd2d899ef8" width="250" />
- Maybe string resources should have a new property? (for translation)
Fixes #3536
=> feat: Change name of Preferences > Filters > Tabs and move them to Account Preferences(#3536)

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
Chrome defaults to showing it anyways, but Firefox doesn't. By enabling this feature, users across both browsers will now have the same experience.
closes tuskyapp/Tusky/issues/4137
=> feat: explicitly enable the share-button in Chrome Custom Tabs

app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt, app/src/main/res/values/strings.xml
It was probably forgotten when we restored the old notifications behavior.
closes #4222
=> bring back the notification filter preference

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
The sensitive flag indicates sensitive media, but we want to check if there is a contentwarning on the post. I think statuses that have a contentwarning but no sensitive flag are rare so we never noticed this bug.
closes #4201
=> make sure link preview card is not shown when cw is collapsed

app/build.gradle, build.gradle, gradle/libs.versions.toml
This reverts commit 649424730133188da585cd47063b00c4f01ff3e8.
Seems like dagger/ksp is still a bit buggy, I'm getting one of these errors every other build, so lets revert this for now.
https://github.com/google/dagger/issues/4181
https://github.com/google/ksp/issues/1196
=> Revert "Migrate to Hilt KSP compiler (#4136)"

app/build.gradle
I had it happen multiple times recently that I was testing green Tusky but Android Studio actually put blue Tusky on my device and I wasted a lot of time until I found out 😣
This change should tell it that greenDebug is the preferred flavor for developing.
=> set greenDebug as default flavor

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
This makes the dot badge that we show on the direct messages tab when there are unread messages blue instead of red. I prefer it that way because its more subtle and doesn't look like there is some kind of error.
before / after:
=> make badge for new direct messages blue

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/res/layout/item_status_detailed.xml, app/src/main/res/values/strings.xml
#4205 did change how the counters for the detailed posts behave and for a good reason I believe.
However I find the changed order very confusing and not aesthetically pleasing.
I have tried a few options, including reserving space for it but it was confusing (when counters are not displayed there would be a danging separator or if we show separator together with it it would be confusing as well).
I propose we simply show the counters independent on the counts. I know we try to de-emphasize the counters but I believe this is fine to do in detailed view.
One disadvantage is that we need translators to update the translations.
Additionally I've done two spacing changes: I removed a separator between the counters and the buttons, removed padding around the counters and increased the space …
=> Improve detailed status looks

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java, app/src/main/java/com/keylesspalace/tusky/receiver/SendStatusBroadcastReceiver.kt, app/src/main/res/values/strings.xml
While working on #4249 I noticed that quick replies also don't work as expected. The notification just stays in the sending state forever.
There are actually 2 problems:
- Notifications are sent in `NotificationFetcher` with the id of the Mastodon notification as tag and the current account id as id. The wrong notification id was forwarded to `SendStatusBroadcastReceiver` so it never had a chance of updating the notification.
- Notifications containing an active remote input can't be cancelled (they just stop their animation when doing so). So instead I update the notification with info that the reply is being sent and have it dismiss automatically.
I also tried replacing the original notification with the "sending" notification of `SendStatusService`, but that doesn't work because …
=> fix quick replies from notifications

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java
=> fix compose notification action not recreating MainActivity

app/src/main/java/com/keylesspalace/tusky/util/ViewBindingExtensions.kt
This reduces complexity of view binding inflation in Fragments, and also reduces overhead (no `KProperty` objects need to be generated by the compiler) by implementing `Lazy` instead of `ReadOnlyProperty`.
For a full explanation, see this [detailed blog post](https://medium.com/@bladecoder/viewlifecyclelazy-and-other-ways-to-avoid-view-memory-leaks-in-android-fragments-4aa982e6e579).
=> Simplify and reduce overhead of lazy view binding in Fragments

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java, app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/login/LoginActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/TabFilterPreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.kt, app/src/main/java/com/keylesspalace/tusky/util/ActivityExensions.kt, app/src/main/res/anim/actitivity_close_enter.xml, app/src/main/res/anim/activity_close_exit.xml, app/src/main/res/anim/activity_open_enter.xml, app/src/main/res/anim/activity_open_exit.xml, app/src/main/res/anim/fast_out_extra_slow_in.xml, app/src/main/res/anim/slide_from_left.xml, app/src/main/res/anim/slide_from_right.xml, app/src/main/res/anim/slide_to_left.xml, app/src/main/res/anim/slide_to_right.xml
I mostly took Android 13 transitions and removed the sliding for the "deeper"/background one because "extend" animations are not available until Android 13.
Here are the original ones: https://cs.android.com/android/platform/superproject/+/android-13.0.0_r8:frameworks/base/core/res/res/anim/;bpv=1
Initially I've made separate versions fro Android 13+ that are close to the original but I think it's not worth it to keep both.
https://github.com/tuskyapp/Tusky/assets/3099142/616fc40c-f944-45b4-bf6f-167f62d30493
=> Better screen transitions

app/build.gradle, app/proguard-rules.pro
Using saner defaults for R8 while reducing the app size even further.
- Add Kotlin compiler options to skip adding assertions in release builds
- Remove `optimizations`, `optimizationpasses` and `dontpreverify` rules that are ignored by R8
- Only keep runtime annotations by default. If other attributes are needed by a specific library, these will already be provided by the library rules (for example Retrofit or coroutines)
- Remove the obsolete rule allowing a View to reflectively call any arbitrary public Activity method accepting a View as argument. This has always been a bad practice and is not used in this project anyway
- Remove the rules related to enums. R8 already optimizes enums properly out-of-the-box and keeping these rules may prevent some of these optimizations
- Add support …
=> Optimize Proguard rules

app/proguard-rules.pro
Regression from #4291 // cc @cbeyls 
<details>
```
Process: com.keylesspalace.tusky, PID: 31230
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.keylesspalace.tusky/com.keylesspalace.tusky.components.accountlist.AccountListActivity}: java.lang.RuntimeException: java.lang.NoSuchMethodException: h4.a.values []
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at …
```
=> put r8 rules for enums back in to fix crash in AccountListActivity

app/src/main/java/com/keylesspalace/tusky/di/AppComponent.kt, app/src/main/java/com/keylesspalace/tusky/di/PlayerModule.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewMediaFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt, gradle/libs.versions.toml
Currently, ExoPlayer is initialized explicitly in `ViewMediaFragment` with all its dependencies, including many that are not useful for viewing Mastodon media attachments.
This pull request moves most ExoPlayer initialization and configuration to a new Dagger module, and instead a `Provider<ExoPlayer>` factory is injected in the Fragment so it can create new instances when needed.
The following ExoPlayer components will be configured:
- **Renderers**: all of them (audio, video, metadata, subtitles) except for the `CameraMotionRenderer`.
- **Extractors**: FLAC, Wav, Mp4, Ogg, Matroska/WebM and MP3 containers, to provide the same support as Firefox or Chrome browsers. Other container formats that are either image formats (already covered by Glide), not web-friendly or reserved for live …
=> Move ExoPlayer initialization to a Dagger module and optimize its dependencies

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineRemoteMediator.kt
classic operator precendence issue
closes #4317
=> prevent media visibility from changing when refreshing timelines

app/src/main/java/com/keylesspalace/tusky/components/instanceinfo/InstanceInfoRepository.kt
Steps to reproduce: Cold start the app while being logged in and offline.
=> fix crash when instance info fails to load

app/src/test/java/com/keylesspalace/tusky/MainActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeActivityTest.kt, app/src/test/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModelTest.kt
Found while working on #4026 but not directly related.
Two cases of unmocked methods and one of unclosed resource.
=> fix warnings in test runs

app/src/main/java/com/keylesspalace/tusky/util/Either.kt, app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountsInListViewModel.kt, app/src/main/java/com/keylesspalace/tusky/viewmodel/ListsViewModel.kt
Seems we don't need them in newer Kotlin.
=> Remove redundant crossinline

app/src/main/java/com/keylesspalace/tusky/components/account/AccountViewModel.kt
The flow must emit every update even if the values are the same, so use SharedFlow instead of StateFlow.
Regression from https://github.com/tuskyapp/Tusky/pull/4337 cc @Goooler
=> fix swipe-refresh spinner showing forever when refreshing AccountActivity

app/src/main/java/com/keylesspalace/tusky/di/PlayerModule.kt
This helps playing some media even if there is a problem with the primary decoder.
E.g. [this video](https://mastodon.social/@krzyzanowskim/112208964123517040) fails on my Fairphone 4 without this change.
<details>
```
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640034, -1, null, [1920, 1440, 119.99593, ColorInfo(BT709, Limited range, sRGB, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:620)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at …
```
=> enableDecoderFallback for ExoPlayer

app/src/main/java/com/keylesspalace/tusky/entity/Attachment.kt
closes #4361 
```
com.squareup.moshi.JsonDataException: Required value 'width' missing at $.statuses[0].media_attachments[0].meta.original
at com.squareup.moshi.internal.Util.missingProperty(Util.java:660)
at com.keylesspalace.tusky.entity.Attachment_SizeJsonAdapter.fromJson(Attachment_SizeJsonAdapter.kt:81)
at com.keylesspalace.tusky.entity.Attachment_SizeJsonAdapter.fromJson(Attachment_SizeJsonAdapter.kt:23)
at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
at com.keylesspalace.tusky.entity.Attachment_MetaDataJsonAdapter.fromJson(Attachment_MetaDataJsonAdapter.kt:64)
at com.keylesspalace.tusky.entity.Attachment_MetaDataJsonAdapter.fromJson(Attachment_MetaDataJsonAdapter.kt:23)
at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonA …
```
=> fix deserializing audio attachments

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt, app/src/main/res/values/dimens.xml
=> Apply window insets to SwipeRefreshLayout in AccountActivity to not obscure spinner

app/build.gradle, app/src/main/java/com/keylesspalace/tusky/LicenseActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt, app/src/main/java/com/keylesspalace/tusky/components/drafts/DraftHelper.kt, app/src/main/java/com/keylesspalace/tusky/network/UriRequestBody.kt, app/src/main/java/com/keylesspalace/tusky/util/CompositeWithOpaqueBackground.kt, app/src/main/java/com/keylesspalace/tusky/util/MediaUtils.kt, gradle/libs.versions.toml
- Read license resource using Okio inside a coroutine (instead of the main thread) in `LicenseActivity`
- Use Okio and its buffer system to copy ContentProvider streams and files to a temporary file in `MediaUploader.prepareMedia()`
- Properly close the input file after copying it to a temporary file in `MediaUploader.prepareMedia()`
- Properly close sink in case of null body source during file copy in `Uri.copyToFolder()` in `DraftHelper.kt`
- Add comment explaining the current value of `DEFAULT_CHUNK_SIZE` in `UriRequestBody.kt` and indent the file properly
- Replace hardcoded `Charset` and `Int` byte size with the proper constants, and align the `hashCode()` implementation with other `BitmapTransformation` implementations in `CompositeWithOpaqueBackground`
- Properly close …
=> Optimize I/O code using Okio - part 2

app/src/main/java/com/keylesspalace/tusky/di/PlayerModule.kt
All subtitle formats used to be enabled by default in older versions of media3.
After the media3 library was upgraded to 1.3.0, Extractors should specify a `SubtitleParser.Factory` explicitly. By default, no subtitle formats are supported when using the now deprecated empty constructor of Extractors.
Limit support to **WebVTT** and **TTML** which are the only true web standards amongst all the subtitle formats supported by ExoPlayer.
Note that only subtitles embedded in MP4 and WebM files are supported until Mastodon provides a way to upload subtitles separately.
=> Enable support for WebVTT and TTML subtitles for the player

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/util/ShareShortcutHelper.kt
The only crash so far in the 25.0-beta1 crash reports. Probably not a regression though as that code did not change in a while.
```
Exception java.lang.IllegalArgumentException: Max number of dynamic shortcuts exceeded
at android.os.Parcel.createExceptionOrNull (Parcel.java:3032)
at android.os.Parcel.createException (Parcel.java:3012)
at android.os.Parcel.readException (Parcel.java:2995)
at android.os.Parcel.readException (Parcel.java:2937)
at android.content.pm.IShortcutService$Stub$Proxy.addDynamicShortcuts (IShortcutService.java:618)
at android.content.pm.ShortcutManager.addDynamicShortcuts (ShortcutManager.java:240)
at androidx.core.content.pm.ShortcutManagerCompat.addDynamicShortcuts (ShortcutManagerCompat.java:334)
at com.keylesspalace.tusky.util.ShareShortcutHelper$updateShortcut$1. …
```
=> never create more than the allowed number of shortcuts

app/src/main/java/com/keylesspalace/tusky/appstore/Events.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt
Mastodon returns different reponses when posting normally and when scheduling. This was previously ignored silently, but Moshi is more correct than Gson and fails, which causes the `SendStatusService` to retry sending forever and a lot of posts are scheduled. 
Mastodon should actually ignore multiple attempts at scheduling the same post, but doesn't so I filed this https://github.com/mastodon/mastodon/issues/30039
cc @cbeyls
=> fix scheduling posts

app/src/main/java/com/keylesspalace/tusky/entity/Card.kt
Akkoma does not always set all attributes for Cards and when they are loaded from the database, the app crashes. When they are loaded from the network, Tusky displays an error. Adding more default values fixes the problem.
```
com.squareup.moshi.JsonDataException: Required value 'authorName' (JSON name 'author_name') missing at $
at com.squareup.moshi.internal.Util.missingProperty(Util.java:660)
at com.keylesspalace.tusky.entity.CardJsonAdapter.fromJson(CardJsonAdapter.kt:122)
at com.keylesspalace.tusky.entity.CardJsonAdapter.fromJson(CardJsonAdapter.kt:22)
at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
at com.keylesspalace.tusky.components.timeline.TimelineTypeMappersKt.toViewData(Tim …
```
=> fix deserializing Akkoma cards

app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsActivity.kt
Steps to reproduce: Quickly unfollow a bunch of hashtags, try clicking unfollow buttons multiple times. If you are faster than the network, the app crashes.
```
java.lang.ArrayIndexOutOfBoundsException: length=20; index=-1
at java.util.ArrayList.remove(ArrayList.java:506)
at com.keylesspalace.tusky.components.followedtags.FollowedTagsActivity$unfollow$1.invokeSuspend(FollowedTagsActivity.kt:152)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at …
```
=> fix crash when quickly unfollowing hashtags

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/components/account/media/AccountMediaGridAdapter.kt, app/src/main/java/com/keylesspalace/tusky/util/AttachmentHelper.kt
- Use `TooltipCompat.setTooltipText()` instead of setting an `OnLongClickListener` showing a Toast, to show the attachment description. This method will display native tooltips on API 26+, and set an `OnLongClickListener` on older versions to display a special Toast anchored to the view. In both cases this provides a better user experience.
- Simplify `Attachment.getFormattedDescription()` by using Kotlin's `Duration`. Since it's an inline class, no extra memory will be allocated on the heap. Also, ensure that the calculation of minutes and hours use the rounded number of seconds instead of the non-rounded one.
=> Show tooltips instead of Toasts when long-pressing attachment images

app/src/main/java/com/keylesspalace/tusky/util/ShareShortcutHelper.kt
I made a mistake in https://github.com/tuskyapp/Tusky/pull/4389 🙄 
With `addDynamicShortcuts` the limit can still be exceeded, `setDynamicShortcuts` is what we want.
Also, `setLongLived` says:
> Sets if a shortcut would be valid even if it has been unpublished/invisible by the app (as a dynamic or pinned shortcut). If it is long lived, it can be cached by various system services even after it has been unpublished as a dynamic shortcut.
I don't think we want that so I removed it.
=> [v25.1] fix crash when exceeding max shortcut number

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineTypeMappers.kt, app/src/main/java/com/keylesspalace/tusky/entity/Status.kt, app/src/main/java/com/keylesspalace/tusky/network/FilterModel.kt
closes https://github.com/tuskyapp/Tusky/issues/4424
=> make Status.filtered nullable to make some weird api implementations work again

app/src/main/java/com/keylesspalace/tusky/adapter/FollowRequestViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/ReportNotificationViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/util/CustomEmojiHelper.kt, app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/main/res/values/dimens.xml
This should save quite some memory, but most importantly it gets rid of this crash:
```
java.lang.RuntimeException: Canvas: trying to draw too large(121969936bytes) bitmap.
at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
at com.keylesspalace.tusky.util.EmojiSpan.draw(CustomEmojiHelper.kt:131)
...
```
=> don't load custom emojis in their full size

app/src/main/java/com/keylesspalace/tusky/util/ShareShortcutHelper.kt
Glide sometimes calls the callback more than once (for the placeholder, then for the actual image), but a coroutine can only resume once.
```
Exception java.lang.IllegalStateException:
at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError (CancellableContinuationImpl.kt:555)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl (CancellableContinuationImpl.kt:520)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default (CancellableContinuationImpl.kt:493)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith (CancellableContinuationImpl.kt:364)
at com.keylesspalace.tusky.util.GlideExtensionsKt$submitAsync$2$target$1.onResourceReady (GlideExtensions.kt:39)
at com.bumptech.glide.request.SingleRequest.onResourceReady (SingleRequest.java:650)
at …
```
=> fix another crash in ShareShortcutHelper

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt
The menu doesn't show up anymore after merging #4026.
I assume this was unintentional since the Fragment still implements `MenuProvider`.
=> Re-enable options menu in NotificationsFragment

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/res/values-night/theme_colors.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/theme_colors.xml
Fixes: #3477
This tweaks two colors: 
* for the dark theme a new slightly darker (timeline) background is used.
* for the light theme a darker shade of blue is used as highlight color (`colorPrimary` and `colorSecondary`)
Additional change:
* Use green and red more consistent: use existing colors for the diff display; move the new light variants to colors.xml like all colors
=> 3477 tweak colors for contrast

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt, app/src/main/res/values/strings.xml
This means a popup will appear if you have that option enabled in the preferences which will have a popup similar to the unfollow dialog asking you if you want to follow the user.
=> Add a feature and preference to confirm follows.

app/src/main/java/com/keylesspalace/tusky/util/ShareShortcutHelper.kt
Loading the image as a `Drawable` allows using the Drawable API to abstract the drawing.
This way, any kind of `Drawable` (including the fallback vector drawable) can be drawn in one pass to the Bitmap, without having to be converted to a `Bitmap` first.
Also, `BitmapDrawable` will automatically use [`Paint.FILTER_BITMAP_FLAG`](https://developer.android.com/reference/android/graphics/Paint#FILTER_BITMAP_FLAG) when drawing, ensuring the resized image is high-quality even when using a Bitmap-backed Canvas.
=> Load shortcut image as Drawable instead of Bitmap

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
API 31+ devices don't need to install the compat SplashScreen because they have their own native splash screen implementation. Furthermore, we don't need to customize the splash screen so there is no need to call the library.
On API 31+, the SplashScreen compat library registers some kind of listener which causes display bugs with the Tusky theme on some Android versions. Disabling the library on API 31+ solves this issue.
Fixes #4446.
=> Disable SplashScreen compat implementation on API 31+

app/src/main/java/com/keylesspalace/tusky/components/account/media/AccountMediaViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/domainblocks/DomainBlocksRepository.kt, app/src/main/java/com/keylesspalace/tusky/components/drafts/DraftsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsPagingAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/report/ReportViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledStatusViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt
This does four things
- set `enablePlaceholders = false` on `PagingConfig`s to avoid Paging Data that contains null placeholders, we don't want them (everywhere, not just in notifications)
- make sure NotificationsPagingAdapter does not crash when it encounters a null placeholder
- makes sure the notifications refresh correctly when the filters change
- the filters are now also respected when loading a gap
closes #4433
=> fix notification filters behaving weirdly

app/src/main/java/com/keylesspalace/tusky/components/compose/view/FocusIndicatorView.kt, app/src/main/java/com/keylesspalace/tusky/entity/Attachment.kt, app/src/main/java/com/keylesspalace/tusky/util/FocalPointUtil.kt
Found a post with this weird media focus in the wild on chaos.social:
```
"focus": {
"x": 0.0,
"y": null
}
```
```
com.squareup.moshi.JsonDataException: Expected a double but was NULL at path $[0].media_attachments[0].meta.focus.y
at com.squareup.moshi.JsonUtf8Reader.nextDouble(JsonUtf8Reader.java:787)
at com.squareup.moshi.StandardJsonAdapters$6.fromJson(StandardJsonAdapters.java:167)
at com.squareup.moshi.StandardJsonAdapters$6.fromJson(StandardJsonAdapters.java:164)
at com.keylesspalace.tusky.entity.Attachment_FocusJsonAdapter.fromJson(Attachment_FocusJsonAdapter.kt:37)
at com.keylesspalace.tusky.entity.Attachment_FocusJsonAdapter.fromJson(Attachment_FocusJsonAdapter.kt:20)
at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
at …
```
=> fix deserializing null focus values

app/src/main/java/com/keylesspalace/tusky/components/account/media/AccountMediaRemoteMediator.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/report/adapter/AdapterHandler.kt, app/src/main/java/com/keylesspalace/tusky/components/report/adapter/StatusViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.kt, app/src/main/java/com/keylesspalace/tusky/viewdata/AttachmentViewData.kt, app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.kt, app/src/main/res/layout/item_status.xml, app/src/main/res/layout/item_status_detailed.xml
This does 4 things:
- Alt text is now translated when opening media of translated posts. Previously only the long-press alt text was translated. 
- The translate button is now hidden on non-public posts. The Mastodon api returns 403 there.
- Translated posts will only be collapsible when the original was collapsible as well. It is just weird when an "show more" button suddenly appears because the post got longer by translating it.
- The translation status and the untranslate button are now shown below each other instead of next to each other. Looks way better on smaller display or long texts.
Before / After
=> Improve translating posts via Mastodon api

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java
The pull request to integrate the SplashScreen library (#4413) required overriding the theme before setting the layout in `MainActivity.onCreate()`, in order to switch from `SplashTheme` to `TuskyTheme`. Since the parent `BaseActivity` already contained code to override the theme in case the user selects the "black" theme, that logic was added at the same spot in `BaseActivity`.
However, since other Activities inherit from `BaseActivity` and sometimes declare a different default theme than `TuskyTheme` in the Manifest, the wrong theme was set for those Activities when not in Black theme mode.
This pull request ensures that the theme will only be overridden to `TuskyTheme` in `MainActivity`, the only Activity that uses a splash screen.
=> Fix incorrect theme override outside of MainActivity

app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/account/list/ListSelectionFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/account/media/AccountMediaFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/accountlist/AccountListFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/domainblocks/DomainBlocksFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/trending/TrendingTagsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt
This pull request has main 2 goals related to improving the handling of View lifecycles in Fragments:
- **Use viewLifecycleOwner when applicable**: every coroutine touching Views in Fragments must be launched in the `coroutinescope` of `viewLifecycleOwner` to avoid the following issues:
1. The code will crash if it references a View binding that is no more available and keeps running after the Fragment view hierarchy has been destroyed.
2. The code will leak Views if it references Views from its parent scope after the Fragment view hierarchy has been destroyed.
3. Multiple instances of the same coroutine will run at the same time, if the coroutine is launched in `onViewCreated()` from the wrong scope and the view hierarchy is destroyed then re-created in the same Fragment instance.
- …
=> Clear View-related references in Fragments and use viewLifecycleOwner when applicable

app/src/main/java/com/keylesspalace/tusky/components/account/media/AccountMediaViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/domainblocks/DomainBlocksRepository.kt, app/src/main/java/com/keylesspalace/tusky/components/drafts/DraftsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/report/ReportViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledStatusViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/trending/TrendingTagsFragment.kt
Two things changed here:
The check for `positionStart`only in `onItemRangeInserted` is not always correct - we only want to jump up when something is inserted at the top, if we already are at the top.
`enablePlaceholders = false` has unintended side effects -  the recyclerview adapter sometimes receives an "onItemRangeRemoved" followed by an "onItemRangeInserted", instead of just "onItemRangeChanged".
Together they should make sure the timelines stay were they are.
=> fix timeline jumping

app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt
The option was removed in https://github.com/tuskyapp/Tusky/pull/3877, then forgotten to be added again in https://github.com/tuskyapp/Tusky/pull/4015. https://github.com/tuskyapp/Tusky/pull/4026 added it again, but took to long to merge, so we made https://github.com/tuskyapp/Tusky/pull/4225 as well and that is how we ended up with the option twice.
=> remove duplicate SHOW_NOTIFICATIONS_FILTER option

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt
Without this, the check that decides if the dialog on close should be shown operates on incorrect data.
closes #4434
=> correctly set currentContent in ComposeViewModel.setup

app/src/main/java/com/keylesspalace/tusky/TuskyApplication.kt, app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/FiltersActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt, app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt, app/src/main/res/layout-sw640dp/fragment_timeline.xml, app/src/main/res/layout-sw640dp/fragment_timeline_notifications.xml, app/src/main/res/layout-sw640dp/fragment_view_thread.xml, app/src/main/res/layout/activity_announcements.xml, app/src/main/res/layout/activity_drafts.xml, app/src/main/res/layout/activity_filters.xml, app/src/main/res/layout/activity_followed_tags.xml, app/src/main/res/layout/activity_lists.xml, app/src/main/res/layout/fragment_account_list.xml, app/src/main/res/layout/fragment_domain_blocks.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/fragment_timeline.xml, app/src/main/res/layout/fragment_timeline_notifications.xml, app/src/main/res/layout/fragment_trending_tags.xml, app/src/main/res/layout/fragment_view_edits.xml, app/src/main/res/layout/fragment_view_thread.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
As discussed in our contributors meeting.
Advantages:
- last element of list never obscured by action button
- less code that runs on every scroll
- less settings to worry about
Additionally: 
- Added a (smaller) padding to the bottom of lists without action button, I think it looks nice if there is a bit of white space and the nav bar divider and the last list divider don't touch.
- The list of filters had no dividers, I added them.
- Recyclerviews with fixed height (Drafts, Filters, edits) now have scrollbars
- code formatted all touched xml files
closes https://github.com/tuskyapp/Tusky/issues/1563
=> Replace "Hide compose button while scrolling" setting with bottom padding

app/src/main/res/layout/activity_view_thread.xml
"Open Drawer" makes no sense here. Removing the attribute makes the description fall back to the default "Navigate up" which is better.
=> fix wrong content description of back button in ViewThreadActivity

app/src/main/java/com/keylesspalace/tusky/StatusListActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/EditFilterActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/EditFilterViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/FiltersViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/res/values/strings.xml
closes #4499 
This restores support for v1 filters. The problem was that the state was uncoditionally set to error instead of checking the v1 response. 
While checking the code I found some other problems:
- Two error messages that were shown to users were not translatable
- When filters were updated sometimes `PreferenceChangedEvent` was sent instead of `FilterUpdatedEvent`
- The notifications fragment was not listening to the `FilterUpdatedEvent`
=> Fix some filter bugs

app/src/main/java/com/keylesspalace/tusky/components/login/LoginActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledStatusViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineTypeMappers.kt, app/src/main/java/com/keylesspalace/tusky/util/AsciiFolding.kt, app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/main/java/com/keylesspalace/tusky/util/ListUtils.kt, app/src/main/java/com/keylesspalace/tusky/viewmodel/EditProfileViewModel.kt
just some smaller things I noticed recently, I hope it is ok if I bunch them up like this
=> small code improvements / code cleanup

gradle/verification-metadata.xml
Sync project with gradle files fails for me in android studio without this change
See https://youtrack.jetbrains.com/issue/IDEA-258328/Dependency-verification-failed-Checksums-of-downloaded-sources-not-included-in-verification-metadata.xml
=> dependency verification: Trust sources packages used by android studio

app/src/main/java/com/keylesspalace/tusky/util/BlurHashDecoder.kt
This pull request aims to dramatically improve the performance of `BlurHashDecoder` while also reducing its memory allocations.
- Precompute cosines tables before composing the image so each cosine value is only computed once.
- Compute cosines tables once if both are identical (for square images with the same number of colors in both dimensions).
- Store colors in a one-dimension array instead of a two-dimension array to reduce memory allocations.
- Use a simple `String.indexOf()` to find the index of a Base83 char, which is both faster and needs less memory than a `HashMap` thanks to better locality and no boxing of chars.
- No cache is used, so computations may be performed in parallel on background threads without the need for synchronization which limits throughput.
Simple: 4x4 …
=> Improve BlurHashDecoder performance

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
I encountered [this weird post](https://akko.wtf/notice/Aiz78vrg9jBNHJrvIO) today that had a content warning button but no content.
This change will match Mastodon behavior and hide the button when there is no content to reveal.
We probably did not encounter this bug earlier because Mastodon moves the CW to the content when the content is empty, but apparently not for federated posts.
=> hide content warning button when there is no content

app/src/main/java/com/keylesspalace/tusky/appstore/Events.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt
=> fix (un)muting conversations

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
When investigating #4517, I found that sharing to Tusky sometimes just does nothing.
This is because when `MainActivity` is already open, it isn't always restarted (`onCreate` not called) but instead the Intent is delivered to `onNewIntent` of the existing `MainActivity`. This fixes the issue by overriding `onNewIntent`.
The problem does not always reproduce, it seems to depend on what is shared from where and on the Android version. `MainActivity` must be open for the problem to occur though.
This probably also fixes the issue that sometimes Tusky does not show the right tab when clicking on a notification (https://github.com/tuskyapp/Tusky/issues/2691)
=> override onNewIntent in MainActivity to improve sharing

app/src/main/java/com/keylesspalace/tusky/adapter/EmojiAdapter.kt, app/src/main/java/com/keylesspalace/tusky/entity/Emoji.kt
Emojis are sorted by category within the emoji picker. The original alphabetical sorting is preserved within categories.
This partially addresses #1868 and is only a small part of what is done in #3300, but I think it is still enough to improve quality of life for users.
=> Sort by category in emoji picker

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsPagingAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/StatusViewHolder.kt
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
at com.keylesspalace.tusky.adapter.StatusBaseViewHolder.setupFilterPlaceholder(StatusBaseViewHolder.java:894)
at com.keylesspalace.tusky.adapter.StatusBaseViewHolder.setupWithStatus(StatusBaseViewHolder.java:825)
at com.keylesspalace.tusky.adapter.StatusViewHolder.setupWithStatus(StatusViewHolder.java:91)
at com.keylesspalace.tusky.components.notifications.StatusViewHolder.bind(StatusViewHolder.kt:46)
at com.keylesspalace.tusky.components.notifications.NotificationsPagingAdapter.bindViewHolder(NotificationsPagingAdapter.kt:150)
at com.keylesspalace.tusky.components.notifications.NotificationsPagingAdapter.onBindViewHolder(Notificatio …
```
=> fix displaying filtered notifications

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
=> show gifs in CaptionDialog

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/FocusDialog.kt
Found while testing #4528
The problem seems to be that Glide does not scale GIFs as it does static images. This workaround makes sure they still show up correctly.
before / after
=> correctly scale gifs in FocusDialog

app/schemas/com.keylesspalace.tusky.db.AppDatabase/64.json, app/src/main/java/com/keylesspalace/tusky/StatusListActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/instanceinfo/InstanceInfoRepository.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java, app/src/main/java/com/keylesspalace/tusky/db/dao/InstanceDao.kt, app/src/main/java/com/keylesspalace/tusky/db/entity/InstanceEntity.kt, app/src/main/java/com/keylesspalace/tusky/entity/FilterV1.kt, app/src/main/java/com/keylesspalace/tusky/network/FilterModel.kt, app/src/test/java/com/keylesspalace/tusky/FilterV1Test.kt, app/src/test/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModelTest.kt
Instead of calling the endpoint every time filters are needed, it will be called only once and the result cached. This will result in quite some requests less on instances supporting v2.
I also tested v1 filters and made some small improvements. We should [remove filters v1 support](https://github.com/tuskyapp/Tusky/issues/4538) some time in the future though.
=> only check once for filters v2 availability

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt
A user still on Mastodon 3 complained that since my change in https://github.com/tuskyapp/Tusky/pull/4539 the timeline reloads on starting Tusky. Well, we need to do some reloading of the timeline after loading the v1 filters or they won't work. Changing the `fullReload` to `invalidate` improves the situation by not loading everything from the network again (just the database) but there is still some noticeable loading.
(I'm not willing to invest any more time to support these old instances)
=> improve filters v1 loading

app/src/main/java/com/keylesspalace/tusky/components/notifications/UnknownNotificationViewHolder.kt
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setClipToOutline(boolean)' on a null object reference
at com.keylesspalace.tusky.adapter.StatusBaseViewHolder.<init> (StatusBaseViewHolder.java:150)
at com.keylesspalace.tusky.adapter.StatusViewHolder.<init> (StatusViewHolder.java:55)
at com.keylesspalace.tusky.components.notifications.UnknownNotificationViewHolder.<init> (UnknownNotificationViewHolder.java:27)
at com.keylesspalace.tusky.components.notifications.NotificationsPagingAdapter.onCreateViewHolder (NotificationsPagingAdapter.kt:139)
at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder (RecyclerView.java:7788)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline …
```
=> fix crash on unknown notification

app/src/main/java/com/keylesspalace/tusky/components/instanceinfo/InstanceInfoRepository.kt
https://social.froonix.org/@cs/112767747835228296
We were caching the instance info with the instance name as the key and then look it up with the actual domain and those do not always match so the check if translation is supported fails.  fnx.li vs social.froonix.org in this case.
=> fix translations not working on instances where domain does not match instance name

app/src/main/java/com/keylesspalace/tusky/components/preference/AccountPreferencesFragment.kt
Without the `isPersistent = false` flag the preference is saved to SharedPreferences in addition to the account and overrides the shown value. So it would always show the value of the last account it was set to. It was working fine though, only the shown value was wrong.
https://social.sitedethib.com/@Claire/112769984398891581
=> fix default post privacy setting sometimes showing the value of the wrong account

app/src/main/java/com/keylesspalace/tusky/util/GlideExtensions.kt
This is the third attempt to fix `RequestBuilder.submitAsync()`. For the rationale, see the comments of #4436.
We now clear the continuation reference after resuming it, to make sure that:
1) It will only be resumed once
2) It will not leak the coroutine when Glide keeps the `Request` around.
=> fix: RequestBuilder.submitAsync() throwing an Exception if the Glide request is restarted

app/src/main/java/com/keylesspalace/tusky/components/search/SearchActivity.kt
Addresses issue #4573. Updates searchView in SearchActivity to clear focus when a user makes a search. This allows the keyboard to not keep popping up after a user goes back to search screen after clicking on a searched item.
=> Updates searchView in SearchActivity to clear focus after search

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt
This will make it less likely that data from different accounts will get mixed up.
I checked  the codepaths and we shouldn't hit viewModel if account is not there but this is still a bit of risk to assume that so I'll investigate if we can pass in more things and use DI to make it more secure
=> Bind account early in timeline & notification view models

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt
fixes https://github.com/tuskyapp/Tusky/issues/4589
=> fix translating boosts in home timeline

app/src/main/res/values/strings.xml
This makes the interface less cluttered and matches Mastodon. The "default" is already in the preference group title, I think this is clear enough.
Before:
After:
Mastodon:
=> remove "default" from posting defaults preference names

app/src/main/res/layout/item_status_placeholder.xml
I don't know why exactly, but when the ViewHolder gets recycled and the ProgressBar is set to visible again, it just doesn't show anything. It seems to be a bug in the platform ProgressBar, and it doesn't happen on all devices. Replacing it with a CircularProgressIndicator fixes the bug and looks the same.
Reported here: https://github.com/tuskyapp/Tusky/issues/4493#issuecomment-2182407513
=> fix "load more" progressbar sometimes not showing up

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
This fixes a bug where the timeline would jump to the position of a previously clicked "load more" when new post are inserted at the top after swiping to refresh.
This only happens when "Reading order" is set to "Oldest first".
The problem is that updateReadingPositionForOldestFirst (which consumes the marker to which it should jump) is called from onItemRangeInserted. But onItemRangeInserted is not called everytime a "load more" is clicked, leaving the marker active, causing a jump the next time onItemRangeInserted is called.
I am not sure this fixes all cases of the various jumping bugs that have been reported recently as this was the only one I could reliably reproduce.
Related to https://github.com/tuskyapp/Tusky/issues/4493
=> fix timeline jumping around when new posts are inserted at the top

app/src/main/java/com/keylesspalace/tusky/components/search/SearchActivity.kt, app/src/main/res/layout/activity_search.xml
Adds feature if user clicks on toolbar, on the pages box, or on the tabs buttons that the keyboard will minimize and focus will be taken off of search bar.
Further addresses issue #4573
=> Minimizes keyboard on search screen

app/src/main/java/com/keylesspalace/tusky/util/SpanUtils.kt, app/src/test/java/com/keylesspalace/tusky/SpanUtilsTest.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/StatusLengthTest.kt
=> Fix detecting urls

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationTypeMappers.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsRemoteMediator.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/test/java/com/keylesspalace/tusky/components/notifications/NotificationsRemoteMediatorTest.kt, app/src/test/java/com/keylesspalace/tusky/components/timeline/TimelineFaker.kt
```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.kt:42)
at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.kt:101)
at com.keylesspalace.tusky.db.dao.TimelineStatusDao_Impl$insert$2.call(TimelineStatusDao_Impl.kt:345)
at …
```
=> fix crash when there are reblogs in notification statuses

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
This one is odd.
I find that if I
- Add an image to a post
- Set a caption on the image
- Tap the caption dialog to bring up the keyboard
- Tap the navbar (very easy to do by accident while typing, just tap under the spacebar)
The caption dialog disappears and you lose your caption.
(This doesn't happen in ANY other dialog in the app, and in the caption dialog it ONLY happens when the keyboard is up.)
I got a tablet and on the tablet this happens ALL THE TIME.
I was considering adding a "really cancel?" dialog to the caption dialog. But then I discovered (thank you @memorion@mastodon.social) by setting getCanceledOnTouchOutside(false), I could make the bad behavior go ahead completely. In my tests now I can only make the dialog go away by tapping the actual back button.
I believe the …
=> Do not cancel the caption dialog on touches on navbar

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
Found a post that had a link that contained a 🔗 in the link text, which tripped up our algorithm.
https://toot.mirbsd.org/@fefes_blog/statuses/01J6YVRNW9C3Q6GBCWKT96CYD0
Before / After
=> fix hidden url markup when link text contains 🔗

app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt
regression from https://github.com/tuskyapp/Tusky/pull/4599
https://pug.ninja/@motoridersd/113102603349423738
The problem is, `MediaUploader` is no longer a singleton, so the state is not correctly shared between `ComposeActivity` and `SendStatusService.` But it can't be a singleton, since `MediaUploadApi` (injected into `MediaUploader`) needs to be recreated on account change.
Let's share the state in the companion object instead.
=> continue uploading media after sending post

app/src/main/AndroidManifest.xml, app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
This fixes
- The problem where Tusky drops your draft when you switch apps while composing
- The problem where MainActivity does not restart when switching theme in preferences
This adds back a bug where one can have multiple instances of MainActivity which can behave weirdly when the active account was switched after they were created. This bug is (unlike the timeline mixup one) transient though, it will go away when restarting the app. As a small mitigation MainActivity is finished when forwarding to ComposeActivity (Tusky 25 behavior).
=> revert MainActivity launchMode again

app/src/main/java/com/keylesspalace/tusky/entity/Announcement.kt
https://docs.joinmastodon.org/entities/Announcement/
The statuses in this model are not full statuses but we expect them, so parsing a response that contains one fails.
`com.squareup.moshi.JsonDataException: Required value 'account' missing at $[0].statuses[1]`
Since we don't even use the attribute, we can just remove it to fix the bug.
Closes #4696
=> remove wrong statuses attribute from Announcement model

app/src/main/AndroidManifest.xml
Fixes #4255 
Tested on Pixel 9 Pro Fold.
Before
https://github.com/user-attachments/assets/dd4d3a06-fb9f-4d89-94c3-401875cfe6f7
After
https://github.com/user-attachments/assets/dac01631-1add-48f4-9cb9-7365b3da2c9c
=> Recreate activities on screenLayout change

.github/workflows/deploy-test.yml
When merging a bunch of PRs at once, it is enough if the newest one gets deployed.
=> only run one test deployment at once

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/main/res/values/donottranslate.xml, app/src/test/java/com/keylesspalace/tusky/util/LinkHelperTest.kt
closes https://github.com/tuskyapp/Tusky/issues/4720
=> fix how emojis in link texts are displayed

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
closes https://github.com/tuskyapp/Tusky/issues/4725
I checked with examples from https://github.com/tuskyapp/Tusky/pull/2743 and looks like nothing broke. Not sure why the `.dontTransform()` was there. It prevents Glide from correctly sizing the image, leading to a crash.
<details>
```
java.lang.RuntimeException: Canvas: trying to draw too large(401361624bytes) bitmap.
at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
at android.widget.ImageView.onDraw(ImageView.java:1446)
at com.google.android.material.imageview.ShapeableImageView.onDraw(ShapeableImageView.java:188)
at …
```
=> fix crash when loading card images with unusual aspect ratio

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
Before (sometimes) vs after:
I'm not sure what is going on here, Glide is being weird sometimes and this change fixes it.
Regression from https://github.com/tuskyapp/Tusky/pull/4738
=> fix link preview images

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt
This is to match Mastodon web behavior.
Also, make revealing filtered boosts in non-cached timelines work (can only happen on user profiles, other timelines don't have boosts).
found thanks to this: https://tech.lgbt/@darkfox/113378644538792719
=> never filter own posts

app/src/main/java/com/keylesspalace/tusky/StatusListActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/EditFilterActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/EditFilterViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/filters/FilterExpiration.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/test/java/com/keylesspalace/tusky/FilterV1Test.kt
Before we would not send `expires_in` when "indefinite" was selected. But that left the expiration at the value it was before. To actually set it to indefinite we need to send `expires_in`, but leave it empty.
With a value class this was actually really nice to fix, the code now self-documents what the special values mean.
Also fixes a regression from the Material 3 redesign where the filter duration drop down would not get populated when creating a filter.
Found while working on https://github.com/tuskyapp/Tusky/pull/4742
=> fix updating filter expiration to indefinite

app/src/main/res/layout/activity_main.xml
Before there was a weird gap when the bar was set to bottom & and the title bar was hidden.
=> set the correct height to the main bottom app bar

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/test/java/com/keylesspalace/tusky/util/LinkHelperTest.kt
```
java.lang.StringIndexOutOfBoundsException
at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:63)
at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:1198)
at com.keylesspalace.tusky.util.LinkHelper.setClickableText(LinkHelper.kt:99)
at com.keylesspalace.tusky.adapter.StatusBaseViewHolder.setTextVisible(StatusBaseViewHolder.java:289)
at com.keylesspalace.tusky.adapter.StatusBaseViewHolder.setSpoilerAndContent(StatusBaseViewHolder.java:244)
at com.keylesspalace.tusky.adapter.StatusBaseViewHolder.setupWithStatus(StatusBaseViewHolder.java:820)
at com.keylesspalace.tusky.adapter.StatusViewHolder.setupWithStatus(StatusViewHolder.java:91)
at com.keylesspalace.tusky.components.timeline.TimelinePagingAdapter.bindViewHolder(TimelinePagingAdapter. …
```
=>  fix crash when post is single line with hashtags 

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt, app/src/main/java/com/keylesspalace/tusky/util/StringUtils.kt
https://masto.nyc/@GetMisch/113557332197065306 causes an infinite loop in the native matcher with the original pattern, trying a different approach
=> Simplify hashtag line checker to avoid infinite loop in android matcher

app/src/main/res/layout-sw640dp/fragment_view_thread.xml
So it matches the rest of the app
Before / after
=> fix thread view background on tablets

app/src/main/res/layout/activity_main.xml
`TabLayout` with Material 3 styling has a thin line at the bottom. That makes sense when it is above the scrollable content, but not when it is below.
Before:
After:
=> fix background of bottom tab bar

app/src/main/res/drawable/tab_indicator_bottom.xml, app/src/main/res/layout/activity_main.xml
Looks way better imho
Before
After
=> rotate tab indicator when tab bar is at the bottom

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt, app/src/main/res/layout/dialog_image_description.xml, app/src/main/res/values/styles.xml
The Material 3 redesign seems to have broken the dialog when very small images where used.
Also removes the weird background behind the context menu (seen in the before screenshot)
Before / after:
=> fix caption dialog

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
https://social.tchncs.de/@KazuShuSora/113621293051641672
=> Preserve the case of hashtags from content when possible

app/src/main/AndroidManifest.xml, app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
This fixes two issues, but I tested them together to make sure this time everything works as expected.
1) The fix in #4813 went into the right direction, but the condition was a bit too broad. When sharing something to Tusky so that Tusky switches accounts, sometimes nothing would happen.
2) fixes #4766. There are two possibilities here (I think it depends mostly on API level):
2a) Sharing starts a new task. `android:maxRecents="1"` makes sure old tasks disappear and are not left in the weird in-between state.
3a) Sharing starts a new `MainActivity` in an existing task. `Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK` makes sure old `MainActivity` instances are removed. On newer Android versions this has the sideeffect of changing the switch animation, but whatever. …
=> fix MainActivity behavior

app/src/main/java/com/keylesspalace/tusky/db/dao/NotificationsDao.kt, app/src/test/java/com/keylesspalace/tusky/db/dao/NotificationsDaoTest.kt
The brackets were at the wrong position and notification types are actually serialized differently.
Closes #4817
=> fix "delete all notifications by user" query

app/src/main/res/values/strings.xml
Now all references to "moderators" uses the plural form, and the app settings are always referred to as "preferences".
=> Standardise strings

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt, app/src/main/res/values/dimens.xml
(or giant soft keyboards)
https://mastodon.social/@bewitchedmind/113703199056088283
Before / After
This makes it also look a bit weird on large screens, but I found no easy way to limit the size. Its now basically back to where it was in Tusky 26.
closes https://github.com/tuskyapp/Tusky/issues/4832
=> improve CaptionDialog for small screens

app/src/main/res/values/strings.xml
The way that translations are shown on the Weblate interface is sometimes incorrect compared to how the string resources are processed by Android, I think because of how Weblate reads newlines and spaces. I guess it's Weblate's fault, but since that's what we use, I'm hoping this MR fixes the discrepancy, or at least minimises it.
I've opted to collapse multi-line strings onto one line (i.e. `help_empty_home`), unless there's a list or something (i.e. `wellbeing_mode_notice`) in which case (for XML source readability) minimal newlines are used which hopefully makes the Weblate issue uniform and minor, if it appears at all.
Here's an example of a good string in the strings.xml:
```
<string name="action_post_failed_detail">Your post failed to upload and has been saved to drafts.\n\nEither …
```
=> Tidy translation strings for better Weblate translation

app/src/main/java/com/keylesspalace/tusky/components/notifications/StatusNotificationViewHolder.kt
We do this in other ViewHolders as well
Seen in this crash report on Google Play:
```
Exception java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
at androidx.paging.PageStore.checkIndex (PageStore.kt:56)
at androidx.paging.PageStore.get (PageStore.kt:66)
at androidx.paging.PagingDataPresenter.peek (PagingDataPresenter.java:290)
at androidx.paging.AsyncPagingDataDiffer.peek (AsyncPagingDataDiffer.java:476)
at androidx.paging.PagingDataAdapter.peek (PagingDataAdapter.kt:312)
at com.keylesspalace.tusky.components.notifications.NotificationsFragment.onViewThread (NotificationsFragment.kt:409)
at com.keylesspalace.tusky.components.notifications.StatusNotificationViewHolder.bind$lambda$0 (StatusNotificationViewHolder.java:104)
at android.view.View.performClick (View.java:7684)
at …
```
=> guard against invalid position in StatusNotificationViewHolder

app/src/main/res/drawable/tab_indicator_bottom.xml, app/src/main/res/drawable/tab_indicator_top.xml, app/src/main/res/layout/activity_account.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_search.xml
There have been multiple complaints by users that the new Material 3 tab indicator is too small. 
Setting `app:tabIndicatorFullWidth="true"` alone looks weird imho, so I additionally added some padding.
cc @mcclure 
Before / After
=> increase width of tab indicator

app/src/main/java/com/keylesspalace/tusky/components/preference/AccountPreferencesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt, app/src/main/res/values/styles.xml
We want multi line titles so they are readable on small screens or with large font sizes, and setting the attribute on every single preference individually is annoying (and we forgot one).
https://pawb.fun/@keeri/113772067202381363
=> set singleLineTitle=false for all preferences via theme

app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt
The problem is that the MaterialAlertDialog uses a layout with "wrap_content" around the custom view. Even though the dialog was stretched to the whole window size, the content was never shown.
The fix reverts to the default dialog and styles it as if it was a MaterialAlertDialog, which works and also looks better on smaller screens.
fixes #4850
=> fix AccountsInListFragment not showing any accounts

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/MediaPreviewAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt, app/src/main/java/com/keylesspalace/tusky/util/PickMediaFiles.kt
This restructures the code so that all picked media will be added to the upload queue in the correct order and also does some other code cleanup.
closes #4754
=> keep ordering when picking multiple media files at once

app/src/main/java/com/keylesspalace/tusky/db/dao/TimelineDao.kt
Fixes (should) doubled reply posts in timelines (https://corteximplant.com/@Sirs0ri/113783407002282357)
Hard to test as you need two accounts logged in to Tusky with operlapping locally cached account data.
=> 3771: Only use timeline entries tied to the currently viewing account

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt
There were network calls inside a database transaction. That basically locked the database for the duration of the network call, causing the app to freeze if the call took to long.
=> fix ANR when loading more on a slow connection

app/src/main/java/com/keylesspalace/tusky/components/systemnotifications/NotificationFetcher.kt, app/src/main/java/com/keylesspalace/tusky/components/systemnotifications/NotificationHelper.java, app/src/test/java/com/keylesspalace/tusky/MainActivityTest.kt
Do summary notifications like the Api defines it:
* Schedule and summarize without delay (in order for summerization to work)
* Always have a summary notification: simplify code with this and make more reliable
* Do not care about single notification count (the system already does that as well)
* **Bugfix: Schedule summary first: This avoids a rate limit problem that (then) not groups at all**
Testing this is probably the most difficult part.
For example I couldn't get any notification to ring with older Api versions in the debugger. (Same as for current develop)
However one hack to always get notifications: Fix "minId" in "fetchNewNotifications()" to a somewhat older value.
Next possible step: Have only one summary notification at all (for all channels/notification types). You can still …
=> Properly summarize all notifications

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
Instead of just "Hashtags".
Actually, this was a bug. The code to generate the correct title is already here, but it wasn't called. 🤷 
closes https://github.com/tuskyapp/Tusky/issues/4867
=> show actual hashtags in title of hashtag tab

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/res/layout/item_preview_card.xml
Remove the bottom space on vertical layout, center text vertically on horizontal layout. Make sure the image on the horizontal layout is at least square.
Before / After:
=> improve preview card when there is no author or description

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt
Without this fix, the vote goes through but the poll in the app doesn't update.
Fixed by using `updateStatusByActionableId`, which automatically handles boosted & regular posts. Also handle poll votes the same way as in the home timeline, by listening to the `PollVoteEvent`.
=> fix voting in boosted polls on user profiles

app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesActivity.kt
`EXTRA_RESTART_ON_BACK` is never set on the Intent extras, but `intent.extras?.getBoolean(EXTRA_RESTART_ON_BACK)` will return `false` as long as there are any extras, hiding the actual value from the `savedInstanceState`.
=> fix MainActivity not restarting when theme changes

app/src/main/java/com/keylesspalace/tusky/adapter/FilteredStatusViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/adapter/FollowRequestViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java, app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/FollowViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsPagingAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/ReportNotificationViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/StatusViewHolder.kt, app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchStatusesAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelinePagingAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ThreadAdapter.kt
Several cases of payloads not being forwarded correctly, leading to unnecessary re-binding of the whole status view. I simplified the logic by removing the additional list level, making it easier to understand what is going on.
=> fix diffing statuses

app/src/main/java/com/keylesspalace/tusky/components/trending/TrendingTagsFragment.kt
This fixes a bug where the action button would be hidden until app restart when trending tags have been visible once.
=> don't hide the action button when showing trending tags

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/dimens.xml
back to what it was in Tusky 27
Api 29 before / after
Api 35 before / after
=> reduce height of bottom bar

app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/AddPollDialog.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt, app/src/main/res/values/dimens.xml
I tried to find a solution without using a deprecated api to no avail. But better a working app than perfect code I guess.
In the end this probably is a bug in the Material component library https://github.com/material-components/material-components-android/issues/3307.
I also made the insets smaller which improves the dialogs a lot on small screens.
=> fix dropdowns in dialogs going behind the keyboard

app/src/main/java/com/keylesspalace/tusky/util/ViewExtensions.kt
The setOnApplyWindowInsetsListener callback is not always excecuted, e.g. because there are no insets to consume on older api levels. This fixes the problem and makes sure our RecyclerViews always have the correct bottom padding and are not covered by other views.
=> fix RecyclerView.ensureBottomPadding on older Api levels

app/src/main/java/com/keylesspalace/tusky/components/instanceinfo/InstanceInfoRepository.kt, app/src/main/java/com/keylesspalace/tusky/entity/Instance.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/java/com/keylesspalace/tusky/viewmodel/EditProfileViewModel.kt, app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeActivityTest.kt
Also read `configuration.accounts.max_profile_fields` from `api/v2/instance` to get the correct limit for GoToSocial.
Glitch-soc also allows more fields but does not provide configuration yet, see https://github.com/glitch-soc/mastodon/issues/2973
closes https://github.com/tuskyapp/Tusky/issues/3305
=> Properly handle more than 4 fields in EditProfileViewModel

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/requests/details/NotificationRequestDetailsFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/notifications/requests/details/NotificationRequestDetailsViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.kt, app/src/main/java/com/keylesspalace/tusky/interfaces/StatusActionListener.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt, app/src/main/res/menu/status_reblog.xml, app/src/main/res/values/strings.xml
Closes #3095
---
Since I had to add `visibility` on the `onReblog` method, it is possible that I have broken something. Also, I kept the old method signature (which calls the new one), but it's possible that it is not needed.
~~I'm not 100% sure that unlisted boost works, as the visibility of the boost is not shown anywehere.~~ I've confirmed that private (followers-only) boosts are not visible on private browsing on the browser.
EDIT: Confirmed visibility in devtools on web browser.
Screenshots:
=> feat: choose boost visibility (#3095)

app/src/main/java/com/keylesspalace/tusky/util/ViewExtensions.kt
re: https://chaos.social/@jannik/114059313885014801
Not sure why I didn't use `onPrepare` previously 🤔 . Makes more sense this way.
The difference between `onStart` and `onPrepare` is that `onPrepare` is called before the `OnApplyWindowInsetsListener` and the other after. So with `onPrepare` it is easy to detect that an animation is starting. The keyboard only seems to animate initially, not when it changes size later, but the previous code always expected an animation.
=> improve WindowInsetsCallback to work when keyboard changes size

app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt
```
Exception java.lang.IllegalStateException:
at androidx.fragment.app.Fragment.requireActivity (Fragment.java:1005)
at com.keylesspalace.tusky.fragment.ViewImageFragment.getPhotoActionsListener (ViewImageFragment.java:58)
at com.keylesspalace.tusky.fragment.ViewImageFragment.access$getPhotoActionsListener (ViewImageFragment.java:48)
at com.keylesspalace.tusky.fragment.ViewImageFragment$ImageRequestListener.onResourceReady$lambda$0 (ViewImageFragment.java:335)
at android.os.Handler.handleCallback (Handler.java:938)
at android.os.Handler.dispatchMessage (Handler.java:99)
at android.os.Looper.loopOnce (Looper.java:226)
at android.os.Looper.loop (Looper.java:313)
at android.app.ActivityThread.main (ActivityThread.java:8751)
at java.lang.reflect.Method.invoke
at …
```
=> add isAdded check in ViewImageFragment to prevent crash

app/src/main/java/com/keylesspalace/tusky/components/systemnotifications/NotificationChannelData.kt
This changes the notification channel names back to what they were pre https://github.com/tuskyapp/Tusky/pull/4929 so users don't lose their settings and the channels won't be duplicated. Tusky nightly users that installed a in-between version will still have duplicate channels, they will need to reinstall.
=> fix notification channel names

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/java/com/keylesspalace/tusky/components/account/media/AccountMediaGridAdapter.kt, app/src/main/java/com/keylesspalace/tusky/components/viewthread/edits/ViewEditsAdapter.kt, app/src/main/java/com/keylesspalace/tusky/util/BlurhashDrawable.kt, app/src/main/java/com/keylesspalace/tusky/util/ImageLoadingHelper.kt, app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt
Glide compares the previous load with the current load, and if they are identical, does basically nothing. Thats what we want, because otherwise it flickers when the requested image is not in the memory cache.
The problem is, we decode the blurhash we use as placeholder everytime. And the BitmapDrawables we get don't have a proper equals implementation.
So Glide is like: Aha, different placeholder, better load again -> Flicker
I added a BlurhashDrawable with custom equals/hashCode and now the flickering is gone.
=> fix images sometimes flickering when interacting with a post

app/src/main/java/com/keylesspalace/tusky/BaseActivity.kt, app/src/main/java/com/keylesspalace/tusky/BottomSheetActivity.kt, app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt, app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt, app/src/main/res/drawable/background_dialog_activity.xml, app/src/main/res/layout/activity_compose.xml, app/src/main/res/layout/fragment_view_image.xml, app/src/main/res/layout/item_status_bottom_sheet.xml, app/src/main/res/values-large-land/dimens.xml, app/src/main/res/values-large/dimens.xml, app/src/main/res/values-large/styles.xml, app/src/main/res/values/dimens.xml
- Fixes the background of the ComposeActivity in table mode which looked weird since https://github.com/tuskyapp/Tusky/pull/4897
- The ComposeActivity in tablet mode will now resize when the keyboard expands, the previously used fixed height would cause the bottom bar to hide entered text on some devices, closes https://github.com/tuskyapp/Tusky/issues/4973
- The bottom sheets in the compose view will now be in fully hidden state by default, as some weirdness on some devices caused them to peek over the bottom bar in half collapsed state. Please test @fin-w 
- The bottom sheet in the image viewer will now expand a bit more in edge-to-edge mode so it doesn't look it is deliberately obscured by the system bar. The image also moves up a bit so it won't be covered by the bottom sheet as much. …
=> fix window insets related bugs

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
regression from https://github.com/tuskyapp/Tusky/pull/4978
I'm sure this `BottomSheetCallback` business had a reason, but it works fine without on all the devices I tried it with 🤷
=> fix media picking not working

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
I just made the dialog non-cancellable. Actually I don't know why it was cancellable when there also is
```kotlin
dialog?.setCanceledOnTouchOutside(false)
```
Fixes #4939
=> Make caption dialog non-cancellable (issue #4939)

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt
When opening the conversations tab with empty cache (i.e. after a frash login), it would sometimes start with 6 year old messages for me, which I find very annoying. The issue is that the loading footer is shown first and the RecyclerView tries to keep it visible when new items are added. This works around the issue. Note that it does not happen when there are already some conversations in the cache.
=> fix conversations jumping down on first load

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
Sometimes a tab is just empty after switching to it, but content appears as soon as you interact with it.
I found that setting a `offscreenPageLimit` on the `ViewPager2` makes that issue go away. 
This also has the side effect that the content of more tabs is preloaded, which makes tab switching *feel* different, one does not see so many loading spinners, content is just there instantly. I'm not sure if that is desireable but I would like to try it out for a while. If it happens to be a problem we can still move tab initialization to when it is actually visible.
=> fix Tusky sometimes displaying empty tabs

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt, app/src/main/java/com/keylesspalace/tusky/MainViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/systemnotifications/NotificationService.kt
`UnifiedPush.registerAppWithDialog` will show a dialog when there are 2 or more distributors, for that it needs an activity context but we passed an application one. I think this is improved in a newer Unified push library version, will upgrade soon. In the meantime this change fixes the crash.
```
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:1314)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:421)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:149)
at android.app.Dialog.show(Dialog.java:352)
at org.unifiedpush.android.connector.UnifiedPush.registerAppWithDialog(UnifiedPush.kt:139)
at …
```
=> fix crash when there are 2 or more unifiedpush distributors

app/lint-baseline.xml, app/src/main/res/values/donottranslate.xml, app/src/main/res/xml/locales_config.xml
Fixes #5032
I added all languages that where marked as unused to the locale file.
The only language that maybe is not really worth putting in there is berber with 36 translations right now.
But in the end those 36 may be better (if they are correct).
=> Fix unused translations lint warnings

app/src/main/res/layout-sw640dp/fragment_view_thread.xml, app/src/main/res/layout/fragment_view_thread.xml
https://layer8.space/@andre/114268763071943595
wtf is this bug 😳
Happens only on Android 15
I have no idea what exactly is going on here, I found this fix by trial and error. `outsideOverlay` seems to look exactly the same as `outsideInset` so i hope this is safe.
=> fix text selection shrinking the view in ViewThreadFragment

app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt
Glide downscales images to fit ImageViews, which makes perfect sense, except here where the ImageView is zoomable.
Always loading the memory in full resolution of course uses more memory but I think this is worth the additional quality. If it leds to performance problems or crashes I will check if we can mitigate those in another way.
Before / after:
=> improve rendering quality when zooming into large images

app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.kt, app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt, app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt
This pull request updates the delete status API call to support the optional `delete_media` parameter introduced in Mastodon 4.2.
Updated `deleteStatus` function to accept a `delete_media` query parameter
Fixes #4986
=> 4986 - Add delete_media parameter support when deleting statuses

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java, app/src/main/res/values/strings.xml
This never worked as intended when the font weight was defined inside the resources. Seems like Weblate is not dealing with that correctly.
If there is `<b>%1$s</b>` used inside the resource, it gets stripped by `getQuantityString`. To work around that, it needs to be HTML escaped `&lt;b>%1$s&lt;/b>` and then passed to `fromHtml`.
Since for some reason not even the source strings got the `&lt;b>%1$s&lt;/b>` correct everywhere, I'm changing it to a completely code based version that will always be right no matter what is defined in the resource.
=> Ensure correct font weight for boost/fav count in all locales

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineTypeMappers.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt
Since https://github.com/tuskyapp/Tusky/pull/5038 the option to filter boosts was ignored and boosts never filtered.
The issue here was that the `HomeTimelineData.status` holds no reblog information, so `timelineData.status?.toStatus(it)` will always return a unreblogged status. `timelineData.toViewData` constructs the correct structure as it considers `HomeTimelineData.reblogAccount` as well.
=> fix filtering boosts from the home timeline

app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesActivity.kt
It is not necessary because the settings are read when the buttons are clicked since https://github.com/tuskyapp/Tusky/pull/5084
=> dont recreate activities when confirm boost/fav setting changes
