tuskyapp/Tusky

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/SplashActivity.java
app/src/main/java/com/keylesspalace/tusky/StatusViewHolder.java
app/src/main/res/drawable/favourite_active.xml
app/src/main/res/drawable/favourite_inactive.xml
app/src/main/res/drawable/reblog_active.xml
app/src/main/res/drawable/reblog_disabled.xml
app/src/main/res/drawable/reblog_inactive.xml
app/src/main/res/drawable/splash_background.xml
app/src/main/res/layout/activity_splash.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml
build.gradle

Animated splash screen will look awesome once we have a Material version of the app logo, but even now it's pretty cool.

Spark animations for boost/favourite, animated splash screen

---

app/src/main/java/com/keylesspalace/tusky/MastodonAPI.java
app/src/main/res/layout/activity_account.xml
app/src/main/res/layout/activity_blocks.xml
app/src/main/res/layout/activity_compose.xml
app/src/main/res/layout/activity_favourites.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_report.xml
app/src/main/res/layout/activity_splash.xml
app/src/main/res/layout/activity_view_tag.xml
app/src/main/res/layout/activity_view_thread.xml
app/src/main/res/layout/activity_view_video.xml
app/src/main/res/values/styles.xml

Unfortunately, I can't seem to figure out why it still gets stuck on media upload dialog. I thought I kept all the latch logic as it was.. I don't understand that part very well yet

Fix crash when adding media, make all activities use coordinator layout

---

app/src/main/res/values-de/strings.xml

Just thought to drop it here :)

Added German localization

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/TuskyTileService.java

Added support for a custom quick settings tile that accesses the Compose Activity

modified manifest to allow for a quick settings tile

---

app/src/main/res/values-fr/strings.xml

Make french translation

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/AccountActivity.java
app/src/main/res/drawable/ic_person_minus_24px.xml

changed AccountActivity so that it shows FAB that allows a user to un/follow a user from it instead of the menu
added an xml svg for unfollowing someone
removed the useless line from build.gradle that I added in the last pull

Better fix for the follow account FAB button

---

app/src/main/res/values-de/strings.xml

heyho,
I added missing german translations, it should be complete now :3

complete german translation

---

app/build.gradle
app/proguard-rules.pro

Added proguard config for release build. Reduces apk size 30%. There is really no reason to not use this.

added proguard config

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/CustomTabURLSpan.java
app/src/main/java/com/keylesspalace/tusky/CustomTabsHelper.java
app/src/main/java/com/keylesspalace/tusky/StatusViewHolder.java
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
build.gradle

Just a small change to enable Chrome Custom Tabs.
Also upgrades some libraries.

Chrome Custom Tab Support

---

app/src/main/res/values-de/strings.xml

Status > Beitrag/Beiträge
TOOT > TRÖT (like in the web interface)
Using same translation for followers like in the web interface
Aut~h~orisierung
"aufgetreten" is lower case, because it's a verb

[German] Some translation improvements

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/java/com/keylesspalace/tusky/TimelineFragment.java
app/src/main/res/xml/preferences.xml

Also allows the user to set a preference whether or not the "compose" FAB gets hidden on scroll

Account header image click opens account

---

app/src/main/java/com/keylesspalace/tusky/ViewVideoActivity.java

videos opened through Tusky now loop, as per gifs

changed VideoActivity to allow for video looping

---

app/src/main/res/values-fr/strings.xml

In the mistake, an big and hardcore mistake found :(

Correct mistake and add new translation

---

app/src/main/res/values-de/strings.xml

added missing german translation

german translation

---

app/src/main/res/values-ar/strings.xml

Hi,
Work made via Transifex via :
https://www.transifex.com/opendz/tusky-in-arabic/
12 missing strings only that I will complete when I'll have enough time :)
Salutations.

Adding arabic localization for Tusky

---

app/src/main/res/values-ja/strings.xml

On dialog_whats_an_instance, Changed mastodon's server address into local.
Signed-off-by: in_dow <in_dow@hotmail.com>

Add Japanese translation

---

app/src/main/java/com/keylesspalace/tusky/ThreadAdapter.java
app/src/main/java/com/keylesspalace/tusky/ViewThreadFragment.java
app/src/main/res/layout/fragment_view_thread.xml

Hi :)
Thanks for Tusky! Hope this is useful!

Allow pull-to-refresh in thread view (closes #73)

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/java/com/keylesspalace/tusky/SFragment.java
app/src/main/java/com/keylesspalace/tusky/ThreadAdapter.java
app/src/main/java/com/keylesspalace/tusky/TimelineFragment.java
app/src/main/java/com/keylesspalace/tusky/TimelinePagerAdapter.java
app/src/main/java/com/keylesspalace/tusky/ViewThreadFragment.java
app/src/main/res/layout/fragment_view_thread.xml

Fixes #74 
**IMPORTANT: This PR is built on top of #159 (which introduces refreshing in the first place) and therefore includes two commits. Please merge #159 first and then review the second commit here separately. If necessary, I can rebase this after #159 is merged :)**

Update thread view after sent reply (closes #74)

---

app/src/main/res/layout/tab_account.xml

Small spacing correction.
Before:
After:

Margins in account tab

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/res/drawable/ic_camera_24dp.xml
app/src/main/res/layout/activity_compose.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/file_paths.xml

Only photos for now, I think it isn't possible doing image and video capture with a single button and I didn't want to clutter the UI.

Allow taking photos directly from the app (closes #139)

---

app/src/main/res/values-nl/strings.xmp

Everything translated. Fully based on Mastodon project translation.

Dutch translation strings

---

app/src/main/java/com/keylesspalace/tusky/ComposeOptionsFragment.java
app/src/main/res/color/drawer_visibility_panel_item.xml
app/src/main/res/drawable/ic_email_24dp.xml
app/src/main/res/drawable/ic_lock_open_24dp.xml
app/src/main/res/drawable/ic_lock_outline_24dp.xml
app/src/main/res/layout/fragment_compose_options.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

Add Direct Message to visibility panel

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.java

Add missing icons in Menu

---

app/src/main/java/com/keylesspalace/tusky/OkHttpUtils.java

Add a custom User-Agent that contains Tusky & Android Version to all requests
https://github.com/Vavassor/Tusky/issues/206

Add a custom User-Agent

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java

At least it fixes the image not loading problem that I am faced with. Not sure whether it fixes the problem for everyone.

Fix #198: Use OkHttp3Downloader by default

---

app/src/main/res/values-ja/strings.xml

Added translations for new strings to Japanese.

Adds Japanese new translations

---

app/src/main/res/values-fr/strings.xml

I don't have the necessary SDK for Android apps, however I was able to fix some awful grammatical errors in the french locales and made the whole thing more coherent.
Could anyone please confirm the app works with my commit? (first ever contribution to an open source project, I might have missed some obvious community guideline)

(untested) Fixed grammatical errors in the french translation

---

app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.java
app/src/main/res/drawable/ic_add_a_photo_32dp.xml
app/src/main/res/drawable/ic_check_32dp.xml
app/src/main/res/drawable/round_button.xml
app/src/main/res/layout/activity_edit_profile.xml
app/src/main/res/menu/edit_profile_toolbar.xml
app/src/main/res/values/strings.xml

Allow profile edition within the app

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.java

Useful title for AccountActivity

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/res/values/strings.xml

Pressing logout in the drawer now shows a dialog to the user asking if they wish to continue.
For #235

Logout Confirmation Dialog

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/StatusViewHolder.java
app/src/main/java/com/keylesspalace/tusky/ViewMediaFragment.java
app/src/main/res/layout/fragment_view_media.xml

Update all dependencies to the most recent version. 
I thought this might be a good thing to do at the start of a new development cycle so we can spot possible incompatibilities early on.

updated dependencies

---

app/src/main/res/values-ar/strings.xml

i18n - Updating Arabic strings translation and added missing ones from "en" version to "ar".

i18n - Updating Arabic strings translation

---

app/src/main/res/values-tr/strings.xml

I suppose this PR doesn't need to be merged and can remain outstanding to collect more updates until before the next release, but I'm opening it now with the strings I see are missing and some touchups to translations now that I see them live in context.

Fix spelling and translate new strings for Turkish

---

app/src/main/res/menu/status_more_for_user.xml

fixes https://github.com/Vavassor/Tusky/issues/283

sharing of own toots now possible

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewMediaFragment.java
app/src/main/res/drawable/ic_file_download_black_24dp.xml
app/src/main/res/layout/fragment_view_media.xml
app/src/main/res/menu/view_media_tooblar.xml

+ toolbar on media
+ navigation button 
+ download button when image is loaded

Download image button or menu option #228

---

app/proguard-rules.pro

I had never build in release before so...
jsoup - proguard

(proguard) add forgoten rule for jsoup in release

---

app/src/main/res/values-pl/strings.xml

Signed-off-by: Marcin Mikołajczak <me@m4sk.in>

l10n: Updated Polish translation

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java
app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.java
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_notification.xml

Add small avatars to boosted toots and to notifications.

---

app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.java

Fix a bug I introduced. Boosted toots didn't have media and clicking avatar led to the wrong account.
Tests. We need them. How to write them.

Fix bug with boosts.

---

app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.java
app/src/main/java/com/keylesspalace/tusky/ViewVideoActivity.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java
app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/ViewMediaFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java
app/src/main/java/com/keylesspalace/tusky/interfaces/StatusActionListener.java
app/src/main/java/com/keylesspalace/tusky/pager/ImagePagerAdapter.java
app/src/main/res/layout/activity_view_video.xml

* show/hide status bar by tapping a photo
* dim and color status bar in video/media viewers
* show/hide status bar in video viewer
* use shared element transition when opening a photo is possible
* center video in VideoView

Improve media browser and video viewer

---

app/src/main/res/xml/preferences.xml

small change, but better usability
before
after

show currently selected check interval in settings

---

app/src/main/res/values-de/array.xml
app/src/main/res/values-de/strings.xml

Just added more strings to the strings.xml file for German. Is it ok to translate the array.xml file as well?

Translating more strings into German

---

app/src/main/res/layout/item_blocked_user.xml
app/src/main/res/layout/item_follow_request.xml
app/src/main/res/layout/item_muted_user.xml
app/src/main/res/layout/item_saved_toot.xml

The buttons where really hard to touch, much better now :)
Also, I changed from android:text to tools:text -> hardcoded strings will not be in final apk, but still in layout preview of android studio
Before:
After:

improve buttons in follow request/muted users/saved toots/blocked users

---

app/src/main/res/values-ja/strings.xml

* tested on my device
* support new strings (ex. drafts, unfollow dialog, search)

l10n: Update Japanese translations

---

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/res/menu/status_more.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

Add a menu entry to copy the link of a toot

---

app/src/main/res/values-ja/strings.xml

add japanese strings for #386 #389 #391 .

Update Japanese Translations

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

Now custom emoji images adapt to the font size.
I didn't have much time to test so please, but here are some results: https://mastodon.social/@charlag/98878611278922865

Fix custom emoji size (closes #404)

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

I didn't find a better solution than just keeping a reference to the context.
Weirdly enough, Studio didn't mark the constructor as deprecated.

Fix deprecated BitmapDrawable constructor

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java

Previews are not saved anymore but rather re-generated on restore.
Also it won't upload finished media anymore.

Fix issues with media uploads restoring. Fixes #419. Fixes #308.

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.java
app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/SavedTootActivity.java
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/res/layout/activity_compose.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

* I refactored things with ```ComposeActivity``` to make it safer, got rid of random extras strings.
* I've added views which show you what status you're replying to. It can be hidden and shown. 
* I didn't start working on fixing #417 because it would be too big for one PR. I'll wait for this to be merged before working on it.

Reply improvements

---

app/src/main/res/values-ja/array.xml
app/src/main/res/values-ja/strings.xml

Improves and adds Japanese translations.

New Japanese translations

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/PlaceholderViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/ThreadAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/TimelineAdapter.java
app/src/main/java/com/keylesspalace/tusky/entity/Notification.java
app/src/main/java/com/keylesspalace/tusky/entity/Status.java
app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java
app/src/main/java/com/keylesspalace/tusky/interfaces/StatusActionListener.java
app/src/main/java/com/keylesspalace/tusky/util/CollectionUtil.java
app/src/main/java/com/keylesspalace/tusky/util/Either.java
app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.java
app/src/main/java/com/keylesspalace/tusky/view/ConversationLineItemDecoration.java
app/src/main/java/com/keylesspalace/tusky/viewdata/NotificationViewData.java
app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.java
app/src/main/res/layout/item_status_placeholder.xml
app/src/main/res/values/strings.xml

fixes #399 
I think I got all special cases & I tested it extensively so it should work fine.
Not quite happy with some constructs & variable names though.
please review @charlag

"load more" Placeholder

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.java

closes https://github.com/Vavassor/Tusky/issues/453

simplify MainActivity back press handling

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
app/src/main/java/com/keylesspalace/tusky/util/NotificationManager.java

So this is how I would fix the crash, please test extensively before merging. (or wait until I find time for testing, probably tomorrow)

fix clear notifications crash

---

app/src/main/res/values-ru/strings.xml

• Added new strings for status text sizes.
• Added new strings for status privacy values.
• Added new string about hidden media.

Russian language updated

---

app/src/main/res/values-ar/strings.xml

Update Arabic translation

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt
app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/java/com/keylesspalace/tusky/ModalTimelineActivity.kt
app/src/main/java/com/keylesspalace/tusky/entity/MastoList.kt
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.java
app/src/main/res/layout/activity_lists.xml
app/src/main/res/layout/activity_modal_timeline.xml
app/src/main/res/layout/item_list.xml
app/src/main/res/layout/toolbar_basic.xml
app/src/main/res/layout/toolbar_shadow_shim.xml
app/src/main/res/values/strings.xml

Bang! Lists list (no pun intended) and list timeline.
I miss Rx a lot but I am not sure that it is a good idea to pull it in yet.
I've decided to split Lists into ViewModel and View early, survives config changes without any dependencies by leveraging nonConfigurationInstance.
I also hate activities. Single Activity Applications FTW.

Add basic lists support

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.java
app/src/main/res/values/strings.xml

So, to finish #411 - setting caption.
There are some debatable UI choices. I went for popup menu and dialog, I think it works well but can be prettier.
I set dialog window to ```SOFT_INPUT_ADJUST_RESIZE``` because otherwise dialog buttons may be invisible. It doesn't always work perfectly, though.
I think I've also fixed a bug with not deleting media URLs properly

Set caption for media

---

app/src/main/res/values-pl/strings.xml

Without build fail with : 
> /var/jenkins_home/workspace/F-Droid/apps/Tusky/app/src/main/res/values-pl/strings.xml:261:6: Error: The content of elements must consist of well-formed character data or markup.
> :app:mergeFdroidReleaseResources FAILED

Translate: Polish: Correct typo

---

app/src/main/res/values-ru/strings.xml

* Added multiaccount strings
* Added licence strings
* Added media caption strings
* Added lists strings
* Added HTTP proxy strings
* Added theme strings
* Some small fixes

Russian translation for Tusky 1.5

---

app/src/main/res/values-fr/strings.xml

Done quickly in vim, some typo can remain. 
Build fine: https://releases.nailyk.fr/jenkins/job/F-Droid/job/k_tusky/106/console

Translates: FR: Add new translations

---

app/src/main/res/values-fr/strings.xml

Messages while media is uploading had no sens. Lets try something different. 
Make "dialog_message_follow_request" innumerable for better reading. 
Signed-off-by: nailyk-fr <jenkins@nailyk.fr>

Update FR translations

---

app/src/main/res/values-fr/strings.xml

Probably another string to change. 
Gonna update the PR later.

Translates: FR: Do not use plural for follows_you

---

app/src/main/res/values-ar/strings.xml

Improving arabic translation

---

app/src/main/res/values-ja/strings.xml

Update japanese translations for some new functions.
Signed-off-by: INAGAKI Hiroshi <musashino.open@gmail.com>

l10n: update Japanese translation

---

app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rMO/strings.xml
app/src/main/res/values-zh-rSG/strings.xml
app/src/main/res/values-zh-rTW/strings.xml

Fix zh-xx translations

---

app/src/main/res/values-ta/strings.xml

I have localized this app in my native language called "Tamil" which has a native speaker  base of about 70 million people. for more info about the Tamil language (https://en.wikipedia.org/wiki/Tamil_language)

Translation for Tamil language is done.

---

app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rMO/strings.xml
app/src/main/res/values-zh-rSG/strings.xml
app/src/main/res/values-zh-rTW/strings.xml

Update zh-XX Translations

---

app/src/main/res/values-pl/strings.xml

* Fixed some small mistakes
* Fixed untranslated strings
* Corrected abbreviations
* Improved consistency
* Added link to GPLv3 translation
@m4sk1n, please check whether everything is okay :)

Improved consistency of Polish translation.

---

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/res/layout/activity_edit_profile.xml

(Pullrequest to trigger bitrise build)
https://stackoverflow.com/questions/45340725/textvew-throws-exception-when-provides-info-for-assistance?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Fix crash on Android 8

---

app/src/main/res/values-nl/strings.xml

I replaced the old and incomplete translation by my new translation.

New Dutch Translation

---

app/src/main/res/values-oc/strings.xml

I'll make more changes soon, so it matches the same wording as in the Mastodon UI.

[OC] first version of the translation

---

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.java

Quickfix for #463 
I didn't test it without customtabs browser but I think it shouldn't break auth flow

Open links in new tabs

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java
app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java
app/src/main/java/com/keylesspalace/tusky/view/ProgressImageView.java
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml
app/src/main/res/values/dimens.xml

- sparks no longer cut off
- higher perf (~50% faster view inflation on my devices)
- antialiased sparks
- bigger hit area for the buttons
- fixed the invalidation of the detailed status
I needed to fork the library because my PRs did not get accepted ¯\\\_(ツ)_/¯
But these things annoyed me for so long, finally I came around to fix them

Fix SparkButtons

---

app/src/main/res/values-fr/strings.xml

* Update needed strings.
* Thanks to @treyssatvincent for the update in #560 !
Signed-off-by: nailyk-fr <nailyk_git@nailyk.fr>

Translates: FR: Update strings

---

app/src/main/java/com/keylesspalace/tusky/SearchActivity.java
app/src/main/java/com/keylesspalace/tusky/adapter/SearchResultsAdapter.java
app/src/main/java/com/keylesspalace/tusky/di/FragmentBuildersModule.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SearchFragment.kt
app/src/main/res/layout/activity_search.xml
app/src/main/res/layout/fragment_search.xml

support for searching statuses

---

.circleci/config.yml
app/src/main/java/com/keylesspalace/tusky/entity/Account.kt

It makes me quite sad that we cannot really check build results in Bitrise, especially when it builds locally.
So, I've set up a CircleCI. As I don't own this repo I set it up for my fork but there's nothing in config that says that so all you need to do is create a project in CircleCI and point it to this repo.
Currently it runs unit tests but we can make it do anything basically? Building and APK would be nice, I don't think it would be hard but we can add it later.
I've been experimenting and broke Git a little so commit history is a disaster and we should squash it.
Thansk!

[CI] Add CircleCI config

---

app/src/main/res/values-fr/strings.xml

* Some strings are gone. Lets remove them.

Translates: FR: Remove unused strings

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.java
app/src/main/java/com/keylesspalace/tusky/BaseActivity.java
app/src/main/java/com/keylesspalace/tusky/BottomSheetActivity.kt
app/src/main/java/com/keylesspalace/tusky/FavouritesActivity.java
app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/java/com/keylesspalace/tusky/ModalTimelineActivity.kt
app/src/main/java/com/keylesspalace/tusky/SearchActivity.java
app/src/main/java/com/keylesspalace/tusky/ViewTagActivity.java
app/src/main/java/com/keylesspalace/tusky/ViewThreadActivity.java
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/interfaces/LinkListener.java
app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.java
app/src/main/res/layout/activity_account.xml
app/src/main/res/layout/activity_favourites.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_modal_timeline.xml
app/src/main/res/layout/activity_search.xml
app/src/main/res/layout/activity_view_tag.xml
app/src/main/res/layout/activity_view_thread.xml
app/src/main/res/layout/fragment_search.xml
app/src/main/res/layout/fragment_timeline.xml
app/src/main/res/layout/fragment_view_thread.xml
app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt

closes #612 
seems to work fine and should also be a bit more efficient since there are less bottom sheets and CoordinatorLayouts inflated

move bottom sheet from fragments to activities

---

app/src/main/res/values-ru/strings.xml

I'm not sure whether we should use word "статусы" (statuses) or "посты" (posts). Or how to mix them in the right way
Anyway, here are the new strings.

[RU] New strings for 1.8

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java

When replying, set default post visibility to the most restrictive of : original post visibility, default visibility preference.

---

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-oc/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-ta/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rMO/strings.xml
app/src/main/res/values-zh-rSG/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

No translations yet. Maybe it breaks defaults. Did I do the right thing at all?...

Add smaller and larger font options (fix #657)

---

app/src/main/java/com/keylesspalace/tusky/fragment/AccountMediaFragment.kt

Things were added in the layout for timelines but I forgot to change AccountMediaFragment. Should be fixed now.

Fix account media progress indicator

---

app/src/main/java/com/keylesspalace/tusky/adapter/AccountViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/BlocksAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/FollowAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/FollowRequestsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/MutesAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/util/CustomEmojiHelper.java
app/src/main/java/com/keylesspalace/tusky/util/ViewDataUtils.java
app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.java

see #631 
Except for ones own username in the drawer, that is not possible with the Api of the drawer. So we probably have to subclass something and/or send a PR to the drawer lib, but lets save that for another relase.

improve custom emoji support

---

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java

Unconditionally scroll timeline a bit on insertion on the top.
Not sure if I should use dp here.

Do not scroll to top on timeline refresh

---

app/src/main/res/values-ru/strings.xml

• Added new strings for emoji settings
• Fixed some bugs with locales
• Updated URLs

Updated Russian language

---

app/src/main/res/values-pt-rBR/strings.xml

- Added missing strings and their translations.

🌎: Updated Brazilian Portuguese translation

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/service/SendTootService.kt

fixes #654
please merge if ok @charlag

use ACTION_GET_CONTENT for media selection again, fix uri permissions

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/fragment/PreferencesFragment.java
app/src/main/res/xml/preferences.xml

a very ugly solution, but a solution

disable emoji fonts on Android 5

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewMediaFragment.java
app/src/main/java/com/keylesspalace/tusky/util/OkHttpUtils.java

increase cache size & dont cache full size media

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewMediaFragment.java
app/src/main/java/com/keylesspalace/tusky/util/OkHttpUtils.java
app/src/main/res/values-it/strings.xml

Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

Updated it (Italian) translation

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java
app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/util/NotificationHelper.java

Just cleaning up some things.
Im wondering if the `ServiceLocator` thing is really necessary?

improve dependency injection

---

app/src/main/res/values-sv/strings.xml

Added the string-arrays etc.

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/view/ProgressImageView.java
app/src/main/res/drawable/spellcheck.xml
app/src/main/res/values/colors.xml

This PR adds small check mark in the corner of the image preview in ComposeActivity.
It works. the only problem is visibility of the check mark. We either need different colors for it or some kind of a circle underneath it.

Add image descriptions indicator. Closes #683

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/adapter/AccountViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/BlocksAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/FollowRequestsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/MentionAutoCompleteAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/MutesAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java
app/src/main/java/com/keylesspalace/tusky/view/RoundedImageView.java
app/src/main/res/drawable/round_button.xml
app/src/main/res/layout/activity_account.xml
app/src/main/res/layout/activity_compose.xml
app/src/main/res/layout/activity_edit_profile.xml
app/src/main/res/layout/item_account.xml
app/src/main/res/layout/item_autocomplete.xml
app/src/main/res/layout/item_blocked_user.xml
app/src/main/res/layout/item_follow.xml
app/src/main/res/layout/item_follow_request.xml
app/src/main/res/layout/item_muted_user.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml
app/src/main/res/layout/item_status_notification.xml
app/src/main/res/layout/view_account_moved.xml

As discussed in #734 
Frankly, I was quite lazy to add a setting for the radius so it's hardcoded but I think that's okay for us

Add RoundedImageView for avatars

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.java
app/src/main/java/com/keylesspalace/tusky/fragment/ViewMediaFragment.java
app/src/main/java/com/keylesspalace/tusky/pager/AvatarImagePagerAdapter.kt

Closes https://github.com/tuskyapp/Tusky/issues/669
Not my prettiest code, but does the job.
I would love to have a ripple effect on the avatar, but no idea how to achieve that 🤔

add possibility to view avatars fullscreen

---

app/src/main/res/values-fr/strings.xml

* Add missing `title_statuses_with_replies` french translation.
Signed-off-by: nailyk-fr <jenkins@nailyk.fr>

Translates: FR: Add missing translation

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt
app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/java/com/keylesspalace/tusky/adapter/AccountFieldEditAdapter.kt
app/src/main/java/com/keylesspalace/tusky/appstore/Events.kt
app/src/main/java/com/keylesspalace/tusky/di/ViewModelFactory.kt
app/src/main/java/com/keylesspalace/tusky/entity/Account.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.java
app/src/main/java/com/keylesspalace/tusky/util/Resource.kt
app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountViewModel.kt
app/src/main/java/com/keylesspalace/tusky/viewmodel/EditProfileViewModel.kt
app/src/main/res/drawable/card_frame_dark.xml
app/src/main/res/layout/activity_edit_profile.xml
app/src/main/res/layout/item_edit_field.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

refactored the `EditProfileActivity` again 
- closes #604 
- closes #561 
- closes #732 
- replaces `AsyncTask` with RxJava
- no more network request on screen rotation

add possibility to change profile fields, refactor

---

app/build.gradle
app/proguard-rules.pro
app/src/main/res/values-ar/strings.xml

Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

Updated ar (Arabic) translation

---

app/src/main/res/values-ko/strings.xml

Files made via Stringlate. Needs to be reviewed before merge. Continued from #782.

Added Korean Translation

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/util/DownsizeImageTask.java
app/src/main/java/com/keylesspalace/tusky/util/MediaUtils.java

closes #827 
We already had the code in Tusky, just needed to call it from the right place.
For some reason Picasso ignores orientation when used with uris as well, so I used RxJava instead.

fix image preview rotation in ComposeActivity

---

app/src/main/res/drawable/tab_page_margin_black.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Make page margin to truly black for tablets.

---

app/src/main/res/values-ru/strings.xml

Re-worded "Favourites" string, replaced "NSFW" with "sensitive"

RU: Translation fixes

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java

As suggested in https://github.com/tuskyapp/Tusky/issues/580#issuecomment-386875000.

Sort custom emojis alphabetically

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java

Extracted from https://github.com/tuskyapp/Tusky/pull/852

Make Tusky a share target for video

---

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java

apparently I still missed a case where the notification tab does not notice its at the end and keeps on loading forever in #807 🙄 
(it loaded forever when there was exactly 1 notification)
(I start hating this)

fix notifications loading (again)

---

app/src/main/java/com/keylesspalace/tusky/adapter/AccountViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java

just some things that bugged me for some time

small improvements for viewholders

---

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/res/values/strings.xml

re #738
Show a confirmation dialog when a user deletes a toot

Add deletion confirmation

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/di/NetworkModule.kt
app/src/main/java/com/keylesspalace/tusky/entity/Status.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.java
app/src/main/java/com/keylesspalace/tusky/network/TimelineCases.kt
app/src/main/res/values/ids.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt

Quick implementation of pin/unpin.
It looks weird without displaying them but as I said before I don't want to make conflicts with #809 again.
I did not add menu item using XML because I think adding two items for one button is weir. I can change that but I would rather change other toggles to programmatic.

Add ability to pin/unpin statuses

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/entity/Account.kt
app/src/main/java/com/keylesspalace/tusky/util/ViewExtensions.kt
app/src/main/res/layout/activity_account.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml

Hey, another small thing.
I didn't figure out if I should make the message more noticeable (Masto has background) and I couldn't do proper German translation, sorry.
<details>
<summary>Screenshots</summary>
</details>

Show "remote profile" message.

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java

Focus content warning field on activation

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/adapter/EmojiAdapter.kt
app/src/main/java/com/keylesspalace/tusky/entity/Emoji.kt

Filter emoji where "visible_in_picker" is set to false.

---

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java

https://github.com/tuskyapp/Tusky/blob/b483a0bf250c9f897489b8cbf68cb2aa192dd018/app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java#L146

Fix typo "accountUsename" to "accountUsername"

---

app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rMO/strings.xml
app/src/main/res/values-zh-rSG/strings.xml
app/src/main/res/values-zh-rTW/strings.xml

Update Chinese translations.

---

app/src/main/res/values-ja/strings.xml

Added ja translate for new-settings and some missing ones.

Improve japanese translation.

---

app/src/main/res/values-ru/strings.xml

• Added string about video limits
• Added "expand"/"collapse" translation
• Updated "Share {smth}..." strings
• Added account preference string translation
• Added media display settings translation
• Translated new strings in Settings
... and more!

Russian translation update

---

app/src/main/res/values-eu/strings.xml

Basque: orro -> tut

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt
app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt
app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt
app/src/main/java/com/keylesspalace/tusky/view/ProgressImageView.java

Removes compat code that is no longer necessary since the upgrade to min api 21.
Other compat code or where I was not sure was left as it is.

remove unnecessary compat code

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/adapter/EmojiAdapter.kt

Improve emoji picker accessibility

---

app/build.gradle
app/schemas/com.keylesspalace.tusky.db.AppDatabase/10.json
app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java

It is extracted part of the #809. I had to rebase it and now I don't have a schema version for the current database. Again.
It's really great to have scheme versions to test migrations without re-installing something 10 times. Room team also insist that it should be checked in.

Export Room schemes

---

app/src/main/res/values-fa/strings.xml

I have made these two things:
- Made several modification to make the existing translation improved
- Added missing stings

Improved Persian translation

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

hide toot content TextView when its empty

---

app/src/main/res/layout/item_status.xml

Fix layout issue with long CWs

---

app/src/main/res/layout/item_status.xml

Fix embarrassing thing with #978

Fix layout issue with narrow timelines

---

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java

This removes `topId` as it is not needed and just plainly uses status id
if needed. During initial loading of notifications `topId`/`bottomId` are
not set so we ended up reloading everything.
We could remove `bottomId` as well but it is used in some logic of reaching the end so I decided to not touch it.

Fix unnecessary reloading of notifications

---

app/src/main/res/layout/activity_edit_profile.xml

Add character counter to profile bio field. #881

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.java

Ensure that the right account is shown as selected after performing "Open as".

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/ReportActivity.java
app/src/main/java/com/keylesspalace/tusky/fragment/AccountMediaFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.java
app/src/main/java/com/keylesspalace/tusky/pager/AccountPagerAdapter.java
app/src/main/res/layout/activity_account.xml
app/src/main/res/values/strings.xml

Related to #443.
I added new tab "pinned" to AccountActivity, which shows user's pinned toot.

Add pinned status tab

---

app/src/main/java/com/keylesspalace/tusky/fragment/AccountMediaFragment.kt
app/src/main/res/layout-sw640dp/fragment_timeline.xml

Fix empty state for account media, fix tablets

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/BaseActivity.java
app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/java/com/keylesspalace/tusky/adapter/AccountSelectionAdapter.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/interfaces/AccountSelectionListener.kt
app/src/main/java/com/keylesspalace/tusky/service/AccountChooserService.kt
app/src/main/res/values/strings.xml

Includes direct-share support when using API 23+

Add support for selecting account when sharing from outside apps

---

app/src/main/java/com/keylesspalace/tusky/fragment/SearchFragment.kt

it was still using the old SharedPreferences based settings

use the correct settings in SearchFragment

---

app/schemas/com.keylesspalace.tusky.db.AppDatabase/13.json
app/src/androidTest/java/com/keylesspalace/tusky/TimelineDAOTest.kt
app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java
app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java
app/src/main/java/com/keylesspalace/tusky/db/TimelineDao.kt
app/src/main/java/com/keylesspalace/tusky/db/TimelineStatusEntity.kt
app/src/main/java/com/keylesspalace/tusky/repository/TimelineRepository.kt
app/src/test/java/com/keylesspalace/tusky/fragment/TimelineRepositoryTest.kt

also add a fast migration so the tables are not created twice when upgrading from Tusky 4.1

remove unneeded instance id from db cache

---

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsRepository.kt
app/src/main/java/com/keylesspalace/tusky/entity/Conversation.kt

try to fix conversations npe

---

app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rMO/strings.xml
app/src/main/res/values-zh-rSG/strings.xml
app/src/main/res/values-zh-rTW/strings.xml

Can't wait for next release any more! :(

Update Chinese translations

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsViewModel.kt
app/src/main/java/com/keylesspalace/tusky/db/ConversationsDao.kt

really nice that they added `Completable` and `Single` support directly to Room in 2.1.0

call db functions on background thread in ConversationsViewModel

---

app/src/main/res/xml/preferences.xml

So that long lines show properly.

Changed CheckboxPreference to SwitchPreference

---

app/src/main/res/values-ru/strings.xml

• Added strings for tabs customization.
• Added strings for Likes/Boosts counters.
• Added strings for external open/share.
• Some other fixes and additions.
String "maximum of 5 tabs reached" is untranslatable atm, by the way.

Russian language updated:

---

app/src/main/res/values-ca/strings.xml

ca: Fix typo: multimètida -> multimèdia

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java

If I click the close button, I definitely want the activity to close, and not hide the bottom sheets.

fix close button behavior in ComposeActivity

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.java

Fixed sharing files doesn't return control after posting

---

README.md

We got our free open source project approved, and it seems to work really good: https://github.com/tuskyapp/Tusky/pull/1054

Replace Stringlate with Crowdin in Readme

---

app/src/main/java/com/keylesspalace/tusky/di/ServicesModule.kt
app/src/main/java/com/keylesspalace/tusky/service/AccountChooserService.kt

I guess there are more sophisticated ways to fix this, but this needs to get out asap
cc @Tak

fix crash on Android 5

---

app/src/main/res/layout/activity_account.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/values/styles.xml

I want the styles as clean as possible

remove empty FAB styling

---

app/src/main/res/values-night-v27/styles.xml
app/src/main/res/values-v27/styles.xml

try to fix black theme navigation bar color on One Plus

---

app/src/main/res/layout/activity_edit_profile.xml

the last major usages of `RelativeLayout`

refactor EditProfileActivity layout

---

app/src/main/res/layout/item_autocomplete_account.xml
app/src/main/res/layout/item_conversation.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml

when we set the text and can guarantee it contains no emojis -> `TextView`
when the text comes from the api -> `EmojiTextView`

remove todos from status layouts

---

app/src/main/java/com/keylesspalace/tusky/util/EmojiCompatFont.java
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-cy/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-eo/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-eu/strings.xml
app/src/main/res/values-fa/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-oc/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-ta/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rMO/strings.xml
app/src/main/res/values-zh-rSG/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml

finally set tusky.app up, had it registered for almost a year :D

change project website url

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java

Fix #581 issue. Wait until bottom sheet not hidden and show the next screen after.

Fix issue with floating media bar after permissions request

---

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java
app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/interfaces/PermissionRequester.java
app/src/main/res/menu/status_more.xml
app/src/main/res/values/strings.xml

...plus one to open the menu :wink: 
- Refactor / generalize external storage permission request
- Add extended status menu item for downloading all media
Addresses #966

Add option to download all media for a toot with one tap

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/util/NotificationHelper.java

Better and safer than rendering them as Mentions.

Hide unknown notifications

---

app/src/main/java/com/keylesspalace/tusky/FiltersActivity.kt
app/src/main/res/layout/activity_filters.xml

currently we are crashing on instances that don't support filters

error handling in FiltersActivity

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java

Have the color of the icon change again, like it was before #1138 
cc @MasterGroosha

change cw icon color on on/off

---

app/src/main/res/layout/activity_account.xml

Use same profile item order (toots, following, followers) as Mastodon

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java

Cancel medias upload on discard a draft message

Cancel media uploads on remove the draft message #838

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java

fix bug where avatars where shown too small

---

app/src/main/res/layout/fragment_view_video.xml
build.gradle
gradle.properties

upgrade build tools and enable r8 full mode

---

CONTRIBUTING.md

Signed-off-by: nailyk-fr <nailyk_git@nailyk.fr>

Contributing: Update translation notice for weblate

---

app/src/main/java/com/keylesspalace/tusky/fragment/preference/PreferencesFragment.kt

add icon for bot indicator preference

---

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java
app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java

The code was doing nothing on Android 5. The check for the Android version is not necessary, `ContextCompat.checkSelfPermission` will just return that the permission has been granted on Android 5.
cc @Tak 
closes #1195

fix downloading media on Android 5

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/entity/Poll.kt
app/src/main/res/layout/item_conversation.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml

4 additional views to every status layout just for this :/ 
I did not find a good way to reuse the RadioButtons though

add support for multiple choice polls

---

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java

Notification filtering fixes

---

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java

I seem to have forgotten this TODO, whoops

fix poll voting in NotificationFragment

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/appstore/CacheUpdater.kt
app/src/main/java/com/keylesspalace/tusky/db/TimelineDao.kt
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
app/src/main/res/layout/item_conversation.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml

Some small bugs with polls. Might add more fixes as I discover problems.

Poll fixes

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/util/DateUtils.java
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-no-rNB/strings.xml
app/src/main/res/values-oc/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rMO/strings.xml
app/src/main/res/values-zh-rSG/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

Sorry, now translators have to translate them again :/
please check if this is what you need @MasterGroosha

fix timespan plurals

---

app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rMO/strings.xml
app/src/main/res/values-zh-rSG/strings.xml
app/src/main/res/values-zh-rTW/strings.xml

I just try the new beta release and fix some translations ...

Fix Chinese translations

---

app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java
app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java
app/src/main/java/com/keylesspalace/tusky/db/TimelineDao.kt
app/src/main/java/com/keylesspalace/tusky/db/TimelineStatusEntity.kt
app/src/main/java/com/keylesspalace/tusky/repository/TimelineRepository.kt

There was another issue with recycling the indicator, maybe the Glide request did not get cancelled when doing `setImageResource`, not 100% sure. The bigger issue was, that the bot flag did not get saved to db and the indicator sometimes was not shown at all.

Fix bot icon indicator again

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/res/values/strings.xml

Fix the #1155 issue.
Add description to the preview image:
1. "Actions for the image %description%" if image has the caption
2. "Actions for the image %idx+1%" if image has not caption, where idx is the index of the image at the queue list.

Add correct Content Description for the preview images at the Compose screen

---

app/build.gradle
app/src/main/res/xml/account_preferences.xml
app/src/main/res/xml/notification_preferences.xml
app/src/main/res/xml/preferences.xml
app/src/main/res/xml/timeline_filter_preferences.xml

Issue #1221 
Update preferences after #1239 
The issues was fixed at the library. "shouldDisableView" may be safely removed now.

Update preferences library, remove unneeded "shouldDisableView"

---

app/src/main/res/layout/item_account.xml

also remove the unnecessary LinearLayout
cc @BoFFire

fix item_account layout for rtl locales

---

app/src/main/res/layout/item_account.xml

I really have to be more careful, recently I always need to re-fix my bugfixes 😞 
before:
after:

fix ellipsize in item_account

---

app/src/main/java/com/keylesspalace/tusky/util/ImageLoadingHelper.kt

add avatar placeholders back in

---

app/src/main/res/layout/activity_view_media.xml
app/src/main/res/values/styles.xml

fix text color in dropdown of light theme

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/res/xml/file_paths.xml

Previous PR: #1164 
Sorry for me accidentally close previous PR when I try to fetch updated code from upstream.
===Previous Message===
Thank @charlag , I solved it by make a copy to cache before upload :)
~~Hi, I bought Samsung S10e currently and try to use Tusky on it. But there have a problem if I upload photos that taken by stock camera. To fix it, the simplest way is always to compress photo before uploading to mastodon instance.~~

make a copy of file before upload on ComposeActivity => solve upload failed bug

---

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

Add setting to show/hide notification filter bar
tuskyapp/Tusky#1306

Add setting to show/hide notification filter bar

---

app/src/main/res/drawable/ic_check_32dp.xml

fix color of check icon in EditProfileActivity

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java

Avatars in the ConversationFragment were not rounded and not respecting the animation setting.

fix conversation avatars

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java
app/src/main/java/com/keylesspalace/tusky/di/NetworkModule.kt
app/src/main/java/com/keylesspalace/tusky/entity/Card.kt
app/src/main/java/com/keylesspalace/tusky/entity/Status.kt
app/src/main/res/drawable/card_frame.xml
app/src/main/res/drawable/card_frame_dark.xml
app/src/main/res/drawable/card_frame_light.xml
app/src/main/res/drawable/card_image_placeholder.xml
app/src/main/res/layout/item_status_detailed.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/styles.xml

- show images for Pleroma Cards
- show a placeholder when there is no image
- show author name when description is empty
- improve design

Improve link preview cards

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java
app/src/main/res/layout/item_conversation.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml

3 more text views? Yes. Is it worth it? I think absolutely.
End goal (and original branch) is to automate it to be on/off depending on network state but I re-did just UI part for now because it's the most benefit (and because I couldn't rebase my older one lol).
Example: https://birb.site/@charlag/102158167894189708

Show media descriptions in timeline when previews are disabled.

---

app/src/main/java/com/keylesspalace/tusky/adapter/PollAdapter.kt
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/report/adapter/StatusViewHolder.kt
app/src/main/java/com/keylesspalace/tusky/entity/Poll.kt
app/src/main/java/com/keylesspalace/tusky/util/NotificationHelper.java
app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt
app/src/main/java/com/keylesspalace/tusky/viewdata/PollViewData.kt
app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.java
app/src/main/res/layout/item_conversation.xml
app/src/main/res/layout/item_poll.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml

- support unlimited number of poll options 
- voting selection no longer gets lost when scrolling
- fix crash when poll has no end date
This makes the code much shorter, I should have done it like this from the beginning 🙄 
closes #1272

Unlimited number of poll options

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/res/layout/activity_compose.xml
app/src/main/res/values/donottranslate.xml

Addresses #810
(Styling help is welcome)

Add @ and # helper buttons to compose activity

---

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java

fix vanishing toots bug when refreshing

---

app/src/main/res/values-en-rGB/strings.xml

Just one additional change - anonymize (US) to anonymise (UK)

Update en-GB strings.xml

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java

Fix respecting bot overlay preference in detailed status view.

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java

- Extract most of the filtering logic into `SFragment`
- Provide specialized overrides in `TimelineFragment` and `ViewThreadFragment`

Apply conversation filters to threads. Addresses #1349

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java

fix card view outline being off a few pixels

---

app/src/androidTest/java/com/keylesspalace/tusky/TimelineDAOTest.kt

these do not run automatically, so I tend to forget about them

fix Android tests

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.java

apparently https://github.com/tuskyapp/Tusky/pull/1379 did not work (still see the error in crash reports), so lets try another approch 🙄

fix glide crash in MainActivity (again)

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/di/NetworkModule.kt
app/src/main/java/com/keylesspalace/tusky/viewmodel/EditProfileViewModel.kt
build.gradle

Deliberately not upgrading the alpha AndroidX libs, as that requires some work and I would like to wait until they are stable for this.
The changes in code are due to OkHttp moving to Kotlin in 4.0.

upgrade dependencies

---

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java

update timestamps on pull-to-refresh even when no new statuses are fetched

update timestamps on pull-to-refresh 

---

app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt

closes #1280
Also makes the avatars round again. Looks like I forgot to call the new method here when introducing the gif animations.

fix avatars and display names in AccountsInListFragment

---

app/src/main/java/com/keylesspalace/tusky/adapter/AccountFieldAdapter.kt

tracking Mastodon web https://github.com/tootsuite/mastodon/pull/11350

show custom emojis in account field names

---

app/src/main/java/com/keylesspalace/tusky/util/NotificationHelper.java

closes https://github.com/tuskyapp/Tusky/issues/763

fix notifications opening the wrong account

---

app/build.gradle
app/src/main/res/xml/account_preferences.xml
app/src/main/res/xml/preferences.xml

closes https://github.com/tuskyapp/Tusky/issues/1411
also upgrade the pref lib, looks like it is finally getting near a stable release

set SwitchPreferenceCompat titles to multiline

---

app/src/main/AndroidManifest.xml

closes https://github.com/tuskyapp/Tusky/issues/1400

[Security] block cleartext traffic

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/report/adapter/StatusViewHolder.kt
app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.java
app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt
app/src/main/java/com/keylesspalace/tusky/util/TimestampUtils.java
app/src/main/res/layout/item_conversation.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml

Goal: make the code easier to read and remove unnecessary stuff
Yes I removed a lot of null checks, but they are all unnecessary with a well-behaving server. In case this introduces a crash we should fix it somewhere else, input validation should not be done when binding views.

cleanup code in StatusViewHolders

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/components/instancemute/InstanceListActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/report/ReportActivity.kt

They removed the old interfaces, we were still using them in 2 places.

upgrade dagger

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java

Regression from https://github.com/tuskyapp/Tusky/pull/1418
I was trying something out and did not mean to commit it 🙄 
On the plus side, this seems to be the only problem introduced in #1418

fix size of visibility icon on detailed toot page

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/res/layout/item_follow.xml

the avatar radius was off for some avatars 🧐
also the alignment was weird in item_follow 🧐
yes this was bugging me a lot

fix avatar radius and alignment in NotificationsAdapter

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt
app/src/main/java/com/keylesspalace/tusky/entity/Instance.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.java
app/src/main/java/com/keylesspalace/tusky/viewmodel/EditProfileViewModel.kt
app/src/main/res/layout/activity_edit_profile.xml
app/src/test/java/com/keylesspalace/tusky/ComposeActivityTest.kt

Add support for instance property `max_bio_chars`

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

Couldn't find an issue for that but I remember that we've discussed this.
Lazily load sensitive media: don't load it until shown.

Load sensitive media previews for only when shown

---

app/build.gradle

Temporary fix until we can solve the problems with https://github.com/tuskyapp/Tusky/pull/1455

revert appcompat upgrade in order to fix in-app-language switching

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java
app/src/main/java/com/keylesspalace/tusky/entity/Attachment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/ViewMediaFragment.kt
app/src/main/res/drawable/ic_music_box_24dp.xml

Straightforward, minimal implementation to get audio attachments to work with Tusky. I don't have time for something more elaborate right now, sorry.
Closes https://github.com/tuskyapp/Tusky/issues/1334

Add audio support for timelines

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java

How to reproduce the bug:
- open thread with sensitive images
- click on sensitive media warning
- observe media not loading

Notify thread adapter when sensitive media is shown

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java

They added a new `GranularRoundedCorners` transformation, so we can remove the `jp.wasabeef:glide-transformations` dependency!

upgrade glide

---

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java
app/src/test/java/com/keylesspalace/tusky/FilterTest.kt

filter polls

---

app/src/main/java/com/keylesspalace/tusky/fragment/AccountListFragment.kt

Introduced by me in https://github.com/tuskyapp/Tusky/pull/1484, found by our awesome nightly testers <3

Fix crash in AccountListFragment

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt
app/src/main/res/layout/fragment_view_video.xml

fix videos not always keeping aspect ratio

---

app/src/main/res/layout/item_follow.xml

fix follow message being cut off with large font

---

app/src/main/java/com/keylesspalace/tusky/adapter/PollAdapter.kt
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/util/NotificationHelper.java
app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt
app/src/main/java/com/keylesspalace/tusky/viewdata/PollViewData.kt
app/src/main/res/values-bn-rIN/strings.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-eo/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-no-rNB/strings.xml
app/src/main/res/values-oc/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rHK/strings.xml
app/src/main/res/values-zh-rMO/strings.xml
app/src/main/res/values-zh-rSG/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml

Don't interpret html inside poll options.

---

app/src/main/java/com/keylesspalace/tusky/BottomSheetActivity.kt
app/src/main/java/com/keylesspalace/tusky/MainActivity.java
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/res/values/strings.xml
app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt

When opening a post via "Open As", if post lookup from the target instance fails, display an error instead of opening the post in the browser.

---

app/src/main/java/com/keylesspalace/tusky/LoginActivity.kt

closes https://github.com/tuskyapp/Tusky/issues/792

fix login on Chromebook

---

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt
app/src/main/java/com/keylesspalace/tusky/util/ShareShortcutHelper.kt

There might be more, these are the ones I could reproduce.

fix crashes related to missing Rx error handler

---

app/src/main/res/values-eu/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-ru/strings.xml

I don't know why Weblate sometimes gets it right and sometimes it does not
¯\\\_(ツ)\_/¯
cc @MasterGroosha

fix formatting of %s favs %s boosts strings in some languages

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java

Make polls respect content warning visibility setting

---

app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java
app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt
app/src/main/java/com/keylesspalace/tusky/adapter/TabAdapter.kt
app/src/main/res/layout/item_tab_preference.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

<details><summary>GIF of the result</summary>
</details>

Add close icon to tabs in Tabs account preferences page

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

I removed the 2 callback methods we never use

upgrade SparkButton to 3.0.0

---

app/src/main/res/values-night/styles.xml
app/src/main/res/values/styles.xml

fix imagebutton color

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt

fix delete&redraft losing toot text

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt

regression from #1541
thx @MasterGroosha for reporting

fix replying to toots

---

app/src/main/java/com/keylesspalace/tusky/util/VersionUtils.java
app/src/test/java/com/keylesspalace/tusky/util/VersionUtilsTest.kt

I was not 100% sure this thing works as expected, now I am

add test for VersionUtils

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

fix poll button being visible below voted poll

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java

Fix missing cases of using StatusDisplayOptions

---

app/src/main/res/drawable/poll_option_background.xml
app/src/main/res/drawable/poll_option_shape.xml
app/src/main/res/layout/item_poll.xml

give poll result backgrounds a rounded shape

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/report/adapter/StatusViewHolder.kt
app/src/main/res/drawable/toggle_small.xml
app/src/main/res/drawable/toggle_small_light.xml
app/src/main/res/layout/item_conversation.xml
app/src/main/res/layout/item_report_status.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml
app/src/main/res/layout/item_status_notification.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/styles.xml

use material buttons in timeline

---

app/src/main/java/com/keylesspalace/tusky/adapter/EmojiAdapter.kt

Fix emoji sorting

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java

closes https://github.com/tuskyapp/Tusky/issues/1578

fix crash in NotificationAdapter when status is null

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/MediaPreviewAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt
app/src/main/res/drawable/ic_music_box_preview_24dp.xml
app/src/main/res/values/strings.xml

Add support for uploading audio attachments

---

app/src/main/res/layout/activity_compose.xml
app/src/main/res/layout/view_compose_options.xml

Make radio buttons in compose screen sheets full width, fix #1593

---

app/src/main/res/values/donottranslate.xml

Adding kabyle language and correcting arabic.

Adding kabyle language

---

app/build.gradle

I hate that we have to upgrade to an alpha version again, but it fixes the issue

fix in app language switching

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java

thx @MasterGroosha for reporting

fix content collapse button not working in notifications

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt
app/src/main/java/com/keylesspalace/tusky/entity/Account.kt
app/src/main/java/com/keylesspalace/tusky/repository/TimelineRepository.kt

not very nice, but fixes the problem
Currently the bug that causes the most crashes

fix crash when Account.displayName is null

---

app/src/main/res/values-night/theme_colors.xml
app/src/main/res/values/colors.xml

its now the same like it was in Tusky 9 again

revert colorPrimaryDark back for the dark theme

---

app/build.gradle

Turns out its not safe to remove this ooops.
Without this flag editing lists crashes
<details>
```
java.lang.IllegalStateException: acceptButton must not be null
at com.keylesspalace.tusky.AccountsInListFragment$Adapter$ViewHolder.<init>(AccountsInListFragment.kt:203)
at com.keylesspalace.tusky.AccountsInListFragment$Adapter.onCreateViewHolder(AccountsInListFragment.kt:190)
at com.keylesspalace.tusky.AccountsInListFragment$Adapter.onCreateViewHolder(AccountsInListFragment.kt:185)
at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(Re …
```

[Tusky10] put androidExtensions experimental=true back in to fix crash

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

Expanded content before
Expanded content after

Fix descriptions of audio attachments when expanding/collapsing status content

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/EmojiPreference.java
app/src/main/java/com/keylesspalace/tusky/util/EmojiCompatFont.java

thanks @connyduck for pointing out OkHttp behavior.
There are individual commits for the fix itself and for reformatting those files

Fix emoji download

---

app/src/main/res/values/colors.xml

make the light theme background color lighter

---

app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchDataSource.kt

fix url search returning the same post indefinitely

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt

Delete draft when sending its status completes

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt

fix crash when inserting custom emojis at the start of the compose field

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/res/values-night/theme_colors.xml

This PR does three things (individual commits)
- cleanup the image keyboard support related code. I tried to stick with this tutorial as closely as possible: https://developer.android.com/guide/topics/text/image-keyboard
- fix a crash when rotating the phone while taking an image with the camera
- make the poll button visible again in dark theme when it is disabled

Compose activity fixes

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/view/ComposeScheduleView.java
app/src/main/res/layout/view_compose_schedule.xml
app/src/main/res/values/strings.xml

- Pops up an explanatory long toast when scheduling a post within 5:30
- Sets the initial value of the time picker to current time + 15:00

Warn when scheduling a post within 5 minutes

---

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java

Add status url as EXTRA_SUBJECT when sharing status content.

---

app/src/main/java/com/keylesspalace/tusky/util/ListStatusAccessibilityDelegate.kt
app/src/main/res/values/actions.xml

At first I started adding all the missing actions to the accessibility menu but then I realized that I can open a popup and it works well and that's almost no code.

Add "more" popup to a11y menu

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Should we add the wrapper verification or the dependency verification mentioned in the releasenotes? I think both would be really cool.

upgrade Gradle and Android plugin

---

app/schemas/com.keylesspalace.tusky.db.AppDatabase/23.json
app/src/main/java/com/keylesspalace/tusky/appstore/Events.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt
app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java
app/src/main/java/com/keylesspalace/tusky/db/TimelineStatusEntity.kt
app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt
app/src/main/java/com/keylesspalace/tusky/entity/Status.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
app/src/main/java/com/keylesspalace/tusky/network/TimelineCases.kt
app/src/main/java/com/keylesspalace/tusky/repository/TimelineRepository.kt
app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.java
app/src/main/res/menu/status_more.xml
app/src/main/res/menu/status_more_for_user.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/keylesspalace/tusky/BottomSheetActivityTest.kt
app/src/test/java/com/keylesspalace/tusky/FilterTest.kt
app/src/test/java/com/keylesspalace/tusky/fragment/TimelineRepositoryTest.kt

Add support for muting conversations

---

app/src/main/java/com/keylesspalace/tusky/adapter/FollowRequestViewHolder.kt

Fix NPE in follow requests view

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

Confirm blocks and mutes from timelines

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java

These are some nasty bugs. I'm sorry I didn't re-test it properly.
Idk if you want to release everything in develop with the next release, I could send this PR against master too.

Fix reblog confirm

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt

Restore compose options after rotation

---

app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt

closes https://github.com/tuskyapp/Tusky/issues/1763

fix overlapping account items in AccountsInListFragment

---

app/src/main/java/com/keylesspalace/tusky/entity/Filter.kt
app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/preference/AccountPreferencesFragment.kt
app/src/main/res/xml/account_preferences.xml

See also: tootsuite/mastodon#12918

Add "account" filter context

---

app/src/main/res/layout/activity_account.xml
app/src/main/res/layout/activity_compose.xml

fixes https://github.com/tuskyapp/Tusky/issues/1780

fix cut off texts when device font size is set to largest

---

app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt

Fix large media uploading

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/res/layout/item_status.xml

Also properly places the preview card after the "collapse for length" button

Fix showing/hiding of preview cards in timeline posts that are collapsed for length

---

app/src/main/res/values-bn-rIN/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-is/strings.xml
app/src/main/res/values-no-rNB/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-zh-rCN/strings.xml

they slip in via Weblate from time to time, but they are easy to find with lint

cleanup bad string translations

---

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java

Fix loading more than one page of favs/bookmarks

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

Fix preview cards for uncollapsible statuses

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt

closes https://github.com/tuskyapp/Tusky/issues/1715

don't create a CW when sharing text to Tusky

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt

closes https://github.com/tuskyapp/Tusky/issues/1839

fix MainActivity title when coming from a notification

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/entity/Relationship.kt
app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountViewModel.kt
app/src/main/res/values/strings.xml

correctly update the menu when muting domains

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt

This is imperfect as it probably reduces quality of the image but it
fixes the crash for now.

Fix crash in the image viewer

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/ViewMediaFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt
app/src/main/res/drawable/description_bg_expanded.xml
app/src/main/res/drawable/ic_drag_indicator_horiz_24dp.xml
app/src/main/res/layout/fragment_view_image.xml

The branch is based on #1843
Increase description char count and use bottom sheet for viewing image descriptions.
I could use some help regarding the sheet. I don't know how to make a better border. There was also a suggestion to fade text when some part is not visible but I'm not sure how to detect that and how to display that, maybe we can omit it for now. It's just some indication of whether you need to pull the sheet or not would be nice.

Description improvements

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt

It was not checked whether captionSheet is present.
fix #1876

Fix crash in ViewImageFragment

---

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt

Allow newlines in image descriptions

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
app/src/main/java/com/keylesspalace/tusky/PreferencesActivity.kt
app/src/main/java/com/keylesspalace/tusky/fragment/preference/PreferencesFragment.kt
app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt
app/src/main/res/values/strings.xml

closes https://github.com/tuskyapp/Tusky/issues/1893

add setting to hide top toolbar

---

app/src/main/res/values/donottranslate.xml

add bn-bd to the in-app languagepicker

---

app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt

Showing repeats was swapped with showing replies.

SettingsConstants: fix home tab filters

---

app/src/main/res/layout/card_license.xml

explicitly set text colors in LicenseCard

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
app/src/main/res/values/dimens.xml

closes https://github.com/tuskyapp/Tusky/issues/1301

use current user's avatar as drawer toggle

---

app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt

Remove 'Add Data' button if all 4 metadata fields are used in Edit Profile

---

app/src/main/java/com/keylesspalace/tusky/components/report/ReportViewModel.kt

Publish mute/block events from the report activity

---

app/src/main/java/com/keylesspalace/tusky/adapter/PollAdapter.kt
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

Set onClick listener for poll result view

---

app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

Also remove the database inspector, since Android Studio now has its own built in!

upgrade gradle and android gradle plugin

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt
app/src/main/res/layout/activity_tab_preference.xml

The thing where the CoordinatorLayout does it automatically is deprecated

use MaterialContainerTransform for ActionButton animation

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt
app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt
app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/report/ReportActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/report/adapter/AdapterHandler.kt
app/src/main/java/com/keylesspalace/tusky/components/report/adapter/StatusesRepository.kt
app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportDoneFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportNoteFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledTootActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt
app/src/main/java/com/keylesspalace/tusky/util/EmojiCompatFont.kt
app/src/main/java/com/keylesspalace/tusky/view/MuteAccountDialog.kt
app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountViewModel.kt
build.gradle

mostly the new "redundant SAM constructor" one

update Kotlin to 1.4.10 and fix some warnigs

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/report/ReportViewModel.kt
app/src/main/java/com/keylesspalace/tusky/entity/Relationship.kt
app/src/main/java/com/keylesspalace/tusky/fragment/AccountListFragment.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
app/src/main/java/com/keylesspalace/tusky/network/TimelineCases.kt
app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountViewModel.kt
app/src/main/res/layout/activity_account.xml
app/src/main/res/values/strings.xml

- notes are saved automatically once you stop typing
- note field is only shown when server supports it
- I also cleaned up some of the old `Call` things and replaced them with RxJava `Single`

Personal account notes

---

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java

apply the home filter to lists

---

app/src/main/java/com/keylesspalace/tusky/entity/Attachment.kt

fix crash when opening some audio attachments

---

app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementsActivity.kt
app/src/main/res/layout/activity_announcements.xml

Fix links in announcements

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt

Fix negative count on the unread announcements badge

---

app/src/main/java/com/keylesspalace/tusky/adapter/ListSelectionAdapter.kt
app/src/main/java/com/keylesspalace/tusky/adapter/PreviewPollOptionsAdapter.kt
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/TabAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/view/ComposeScheduleView.java
app/src/main/java/com/keylesspalace/tusky/components/preference/AccountPreferencesFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt
app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt
app/src/main/java/com/keylesspalace/tusky/util/ThemeUtils.java
app/src/main/res/layout/activity_compose.xml
app/src/main/res/layout/item_autocomplete_hashtag.xml
app/src/main/res/layout/item_conversation.xml
app/src/main/res/layout/item_poll_preview_option.xml
app/src/main/res/layout/item_report_status.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml
app/src/main/res/layout/item_tab_preference.xml
app/src/main/res/layout/item_tab_preference_small.xml
app/src/main/res/layout/view_compose_schedule.xml
app/src/main/res/values/styles.xml

Comment says `drawableTint in xml once minSdkVersion >= 23`, but today I learned there is actually a compat version of it.

remove ThemeUtils.getTintedDrawable

---

app/src/main/res/layout/activity_main.xml

I guess this got lost when adding the avatar to the toolbar

set contentDescription for menu toggle

---

app/src/main/res/layout/item_emoji_pref.xml

Bug introduced with #2015 
I really need to be more careful not to introduce regressions 😖

fix emoji preference thumbnails

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/res/values/strings.xml

with this PR, now can upload multiple media with the system chooser.
If the user chooses images + uploaded images is greater than 4, then won't upload and show an error message.

multiple media upload support

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt

Make tapping the main toolbar scroll to the top of the timeline

---

app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt
app/src/main/res/values/strings.xml

Prompt before deleting lists

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/AccountMediaFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt
app/src/main/res/values/strings.xml

Support opening unknown attachment types via `openLink`

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt

Doesn't seem that was used anywhere.

ComposeViewModel: remove unused variable

---

app/src/main/res/values/donottranslate.xml

add Bulgarian, Sorani and Sanskrit to the in-app language picker

---

app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.java

fix custom emojis in names when liking/boosting a boosted toot

---

app/build.gradle

I forgot to remove it in #2056

remove okhttp-tls dependency

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/db/Converters.kt
app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt

and use the new ProvidedTypeConverter

update Room to 2.3.0

---

app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.kt

fix event handling in TimelineFragment

---

app/proguard-rules.pro

This gives us about 80kb smaller apk size

improve kotlin related proguard rules

---

app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.kt

fix reblog avatar

---

CONTRIBUTING.md

Update default branch references in the contribution doc

---

app/src/main/java/com/keylesspalace/tusky/entity/Account.kt

https://matrix.to/#/!PWkUGGpeMZWDPmdfRE:matrix.org/$16315373941uEUeD:ondergrond.org?via=matrix.nailyk.fr&via=matrix.org&via=mozilla.org

Fix crash when updating profile and the source field exists, but some of _its_ fields don't

---

app/src/main/java/com/keylesspalace/tusky/adapter/PollAdapter.kt
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java
app/src/main/java/com/keylesspalace/tusky/entity/Poll.kt
app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt
app/src/main/java/com/keylesspalace/tusky/viewdata/PollViewData.kt
app/src/main/res/values-night/theme_colors.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/theme_colors.xml
app/src/test/java/com/keylesspalace/tusky/FilterTest.kt
app/src/test/java/com/keylesspalace/tusky/components/timeline/TimelineViewModelTest.kt

Highlight your own votes when displaying poll results

---

app/src/main/java/com/keylesspalace/tusky/components/instancemute/InstanceListActivity.kt

Fix toolbar for instance list activity

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineAdapter.java
app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java
app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt
app/src/main/java/com/keylesspalace/tusky/util/StatusDisplayOptions.kt
app/src/main/res/values/strings.xml

Adds the same confirmation dialogues for favourite and bookmark actions as boost has.

Add confirmation for favourite and bookmark actions

---

app/src/main/java/com/keylesspalace/tusky/AccountActivity.kt

closes https://github.com/tuskyapp/Tusky/issues/2257

fix compose button on profile page being half hidden

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt

and respect the animateAvatars setting
closes #2259
It is kinda verbose, but it works 🤷

fix loading Gif avatars into the main appbar

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewThreadFragment.java

fixes https://github.com/tuskyapp/Tusky/issues/2294

fix media hidden default in ViewThreadFragment

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineRemoteMediator.kt
app/src/test/java/com/keylesspalace/tusky/components/timeline/NetworkTimelineRemoteMediatorTest.kt

correctly detect end of pagination in network timeline

---

app/build.gradle
app/proguard-rules.pro
app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt
app/src/main/java/com/keylesspalace/tusky/TabData.kt
app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsRemoteMediator.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledTootActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineRemoteMediator.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt
app/src/main/res/raw/keep.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Update gradle, kotlin and other dependencies

---

app/src/main/java/com/keylesspalace/tusky/entity/Relationship.kt
app/src/main/java/com/keylesspalace/tusky/json/GuardedBooleanAdapter.kt
app/src/test/java/com/keylesspalace/tusky/json/GuardedBooleanAdapterTest.kt

e.g. qoto.org
See #2276 and https://git.qoto.org/qoto/qoto/-/issues/11 for more info

use custom JsonAdapter to be compatible with instances that have a custom subscribing feature

---

app/proguard-rules.pro

... of course I forgot to check this in https://github.com/tuskyapp/Tusky/pull/2298
... as always 🙄

add proguard rules to make @JsonAdapter annotation work

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt

This fixes the problem at one end, I am still thinking if I could somehow just detect that a placeholder will not load anything and not even insert it.

fix placeholder not disappearing when no statuses are loaded

---

app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt

closes https://github.com/tuskyapp/Tusky/issues/2307

display custom emoji in announcements

---

app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt

- closes #2308 
- fixes an issue that causes announcement reactions to not properly update when clicked

Fix announcement reactions

---

app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt
app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java

another regression from https://github.com/tuskyapp/Tusky/pull/2238
already fixed in status details by https://github.com/tuskyapp/Tusky/pull/2295
this fix needs to be included in Tusky 16.0

fix sensitive media in search and notifications

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt

Don't use notifyDataSetChanged in TimelineFragment

---

app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchStatusesAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt

Status is included in StatusViewData.Concrete. It makes no sense to have an additional reference to Status.

use ViewData only instead of Pair<Status, ViewData> in Search

---

app/schemas/com.keylesspalace.tusky.db.AppDatabase/29.json
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineTypeMappers.kt
app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java
app/src/main/java/com/keylesspalace/tusky/entity/Status.kt

fix database migration to v29

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java

Not sure where we broke this, this definitely used to work before.
closes #2360

display account name when display name is not set

---

app/src/main/java/com/keylesspalace/tusky/appstore/CacheUpdater.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt
app/src/main/java/com/keylesspalace/tusky/db/TimelineDao.kt
app/src/test/java/com/keylesspalace/tusky/components/timeline/CachedTimelineRemoteMediatorTest.kt
app/src/test/java/com/keylesspalace/tusky/db/TimelineDaoTest.kt

This doesn't fix anything, just makes the code a little bit nicer than before

Improve timeline dao

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/EmptyTimelinePagingSource.kt

found in the Google Play crash reports

fix various timeline related crashes

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/util/TimelineUtils.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineRemoteMediator.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt
app/src/test/java/com/keylesspalace/tusky/components/timeline/NetworkTimelineRemoteMediatorTest.kt

There might be implementation bugs that we are missing if we just catch all exceptions.

Don't hide potential timeline bugs by catching all exceptions

---

app/build.gradle

upgrade glide animation plugin to 2.18.0

---

app/build.gradle

addresses (part of?) #2385 
see https://github.com/penfeizhou/APNG4Android/issues/142 for more info

update glide animation plugin to 2.20.0

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/test/java/com/keylesspalace/tusky/ComposeActivityTest.kt

When calculating post length, count all urls as being of the reserved character count, even if they're shorter

---

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt

Revert unintentional behavior change for mention spans to use remote usernames

---

app/src/main/java/com/keylesspalace/tusky/util/EmojiCompatFont.kt

Until the new emoji picker is ready, the version needs to be updated here 😅
The new versions should fix #2407

Update emoji font versions to 14

---

app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt

It was a race condition - we started the async database query and then cancelled the service without waiting for the database query to return. This fixes the problem so that statuses that fail to send will always be saved to drafts.
I also refactored the code to use `kotlinx.coroutines.delay` instead of `java.util.Timer` which is way nicer.
closes #2399

Fix saving failed status to drafts

---

app/build.gradle

https://issuetracker.google.com/issues/214835299
maybe fix for #2385?

upgrade splashscreen library to 1.0.0-beta02

---

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt

similar to https://github.com/tuskyapp/Tusky/pull/2369

fix crash in ConversationsFragment

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

Don't show preview cards on statuses with polls

---

app/src/main/java/com/keylesspalace/tusky/components/login/LoginWebViewActivity.kt

fix login on Android API level <24

---

app/build.gradle

<details>
```
java.lang.IllegalArgumentException: Unable to create call adapter for wa.f<e9.f>
for method c.Z
at com.bumptech.glide.c.K(SourceFile:4)
at wa.u.b(SourceFile:381)
at wa.y0.b(SourceFile:4)
at wa.x0.invoke(SourceFile:7)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy1.Z(Unknown Source)
at w5.r0.o(SourceFile:5)
at j9.a.h(SourceFile:3)
at x9.z.p0(SourceFile:26)
at h9.d.h0(SourceFile:1)
at x9.a.e0(SourceFile:13)
at x8.a.h0(SourceFile:4)
at x8.a.i0(SourceFile:2)
at com.keylesspalace.tusky.MainActivity.onCreate(SourceFile:63)
at android.app.Activity.performCreate(Activity.java:7136)
at android.app.Activity.performCreate(Activity.java:7127)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
at …
```

upgrade Kotlin Result CallAdapter to v1.0.1 to fix crash

---

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java
app/src/main/java/com/keylesspalace/tusky/util/StatusParsingHelper.kt

regression from https://github.com/tuskyapp/Tusky/pull/2414

fix notifications showing unparsed html

---

app/schemas/com.keylesspalace.tusky.db.AppDatabase/34.json
app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java
app/src/main/java/com/keylesspalace/tusky/components/preference/NotificationPreferencesFragment.kt
app/src/main/java/com/keylesspalace/tusky/db/AccountEntity.kt
app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java
app/src/main/java/com/keylesspalace/tusky/di/AppModule.kt
app/src/main/java/com/keylesspalace/tusky/entity/Notification.kt
app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt
app/src/main/res/drawable/ic_edit_24dp.xml
app/src/main/res/values/strings.xml

:ballot_box_with_check: Notification channel
:ballot_box_with_check: Preference
:ballot_box_with_check: Filter
ref: https://github.com/mastodon/mastodon/pull/16697

Add support for post edit notifications

---

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt
app/src/main/res/drawable/ic_briefcase.xml
app/src/main/res/layout/activity_account.xml

fix "account moved" on profiles not being clickable

---

app/src/main/res/layout/activity_main.xml

closes https://github.com/tuskyapp/Tusky/issues/2444

never collapse bottom app bar tabs

---

app/src/main/java/com/keylesspalace/tusky/components/drafts/DraftsActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java

fix unparsed html in "replying to" toggle

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java

closes https://github.com/tuskyapp/Tusky/issues/2441
closes https://github.com/tuskyapp/Tusky/issues/2252

guard against the status of a notification being null in rare cases

---

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/account/AccountFieldAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/account/AccountViewModel.kt
app/src/main/java/com/keylesspalace/tusky/entity/IdentityProof.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt

Removes identity proof support according to #2440.

Remove Identity Proof Support

---

app/src/main/java/com/keylesspalace/tusky/components/login/LoginWebViewActivity.kt
app/src/main/res/layout/login_webview.xml
app/src/main/res/values/strings.xml

- show a Progressbar while the webview content is loading
- add a title to the activity
- finish without animation

improve LoginWebViewActivityUX

---

app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt
app/src/main/java/com/keylesspalace/tusky/di/NetworkModule.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
app/src/main/java/com/keylesspalace/tusky/network/MediaUploadApi.kt

I'm quite sure that this fixes bugs like https://github.com/tuskyapp/Tusky/issues/995 https://github.com/tuskyapp/Tusky/issues/2226

increase timeout for media uploads

---

app/src/main/java/com/keylesspalace/tusky/adapter/PollAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt

https://gist.github.com/Tak/05f88e104502cd56e7d55448381eb75d
Since we now use emoji2 there s no need to manually process the emojis anymore
cc @Tak @C1710

fix EmojiCompat.get().process crash in polls

---

app/src/main/java/com/keylesspalace/tusky/components/login/LoginWebViewActivity.kt
app/src/main/res/layout/activity_login_webview.xml

It is white on white 😅 
Also, rename the layout file to match our naming scheme

fix login webview title color with light theme

---

app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java

closes https://github.com/tuskyapp/Tusky/issues/2521

fix notification message formatting when username is not at the beginning of the message

---

app/src/main/res/layout/activity_search.xml

never collapse tabs in SearchActivity

---

app/src/main/AndroidManifest.xml

nice to have
https://developer.android.com/reference/android/R.attr.html#appCategory

add app category to AndroidManifest

---

app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt
app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt
app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountsInListViewModel.kt
app/src/main/java/com/keylesspalace/tusky/viewmodel/ListsViewModel.kt

slowly but surely getting rid of Rx

migrate Lists from RxJava to Kotlin coroutines

---

app/proguard-rules.pro

every. single. time.
closes https://github.com/tuskyapp/Tusky/issues/2540

add shrinker rules to keep bouncycastle EC classes

---

app/src/main/java/com/keylesspalace/tusky/components/login/LoginWebViewActivity.kt

this makes it easier to investigate issues like https://github.com/tuskyapp/Tusky/issues/2462

make WebView debuggable in debug builds

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java

An initial delay (0) can also be specified for the older Notifications list.
Fixes https://github.com/tuskyapp/Tusky/issues/2554

2554 refresh timestamps on resume

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt

just a little something I noticed

remove unused member vars from TimelineFragment

---

app/src/main/java/com/keylesspalace/tusky/components/login/LoginActivity.kt
app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
app/src/main/res/values/strings.xml

Basically the solution is to make the verify_credentials call before adding anything to the AccountManager. Adds an additional network call when logging in but I guess thats fine.
closes https://github.com/tuskyapp/Tusky/issues/2593

fix data loss when re-adding existing account

---

app/src/main/java/com/keylesspalace/tusky/components/notifications/PushNotificationHelper.kt

Friendica returns status 200 and html on POST /api/v1/push/subscription. This change makes sure we don't crash when that happens.
Friendica should still fix this on their side: https://github.com/friendica/friendica/issues/11722

don't crash on invalid json response for push subscription

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java
app/src/main/java/com/keylesspalace/tusky/adapter/PollAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/view/ProgressImageView.java
app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/receiver/SendStatusBroadcastReceiver.kt
app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt
app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt

update minSdkVersion to 23

---

app/src/main/java/com/keylesspalace/tusky/FiltersActivity.kt
app/src/main/java/com/keylesspalace/tusky/entity/Filter.kt
app/src/main/java/com/keylesspalace/tusky/network/FilterModel.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
app/src/test/java/com/keylesspalace/tusky/FilterTest.kt

Respect filter expiration date when applying filters

---

app/src/main/java/com/keylesspalace/tusky/FiltersActivity.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
app/src/main/java/com/keylesspalace/tusky/view/FilterDialog.kt
app/src/main/res/layout/dialog_filter.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/keylesspalace/tusky/FilterTest.kt

- Shows the remaining filter duration in the filter list view
- Allows setting/updating durations for filters

Support setting filter expirations

---

app/src/main/java/com/keylesspalace/tusky/components/viewthread/ConversationLineItemDecoration.kt

I made a mistake when refactoring this, see here https://github.com/tuskyapp/Tusky/pull/2617/files#diff-c2e149ca2e677f13df29ee8964ff3fdbc327ba89544f79bd25242aab6b7d6a71

fix ConversationLineItemDecoration

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt

re #2626
Refactored the dialog to be `CaptionDialog` and save/restore the text input state.
I tried to keep existing logic where I can. The main difference is how the dialog communicates with the Activity.

Refactor Caption Dialog to handle screen rotation (#2626)

---

app/src/main/java/com/keylesspalace/tusky/network/FilterModel.kt
app/src/test/java/com/keylesspalace/tusky/FilterTest.kt

Parse html tags out of status content before applying filters

---

app/src/main/res/layout/dialog_focus.xml
app/src/main/res/values/strings.xml

I am still a little shaky on the XML layouts so I did it programmatically. Dunno if that's OK or not.

Add a description to the focus dialog

---

app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt

closes https://github.com/tuskyapp/Tusky/issues/2714

improve check for media upload status

---

app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledStatusActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledStatusAdapter.kt
app/src/main/res/values/strings.xml

closes https://github.com/tuskyapp/Tusky/issues/2706

warn before deleting a scheduled post

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/view/ExposedPlayPauseVideoView.kt

Fixes #2419
Note: I filled a suggestion here about [switching to exoplayer](https://github.com/tuskyapp/Tusky/issues/2753) which I think is still worth considering but this address the issue simply by handling config changes for `ViewMediaActivity`.

Handle config changes for video playback

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java
app/src/test/java/com/keylesspalace/tusky/MainActivityTest.kt
gradle/libs.versions.toml

Navigate to the Follow Requests page from notification

---

app/src/main/res/layout/item_status_placeholder.xml

fixes #2177 
adjust text size and style to make the 'show more' placeholder more visible

#2177 enhance 'show more' visibility

---

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.java
app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/keylesspalace/tusky/usecase/TimelineCasesTest.kt

Show toast if pin fails

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/res/values/strings.xml

Warn about losing media

---

app/src/main/res/layout/item_announcement.xml
app/src/main/res/values/strings.xml

closes https://github.com/tuskyapp/Tusky/issues/2809

add content description to add reaction button

---

app/src/main/java/com/keylesspalace/tusky/TabData.kt

Replace the default federated timeline tab with the direct messages tab

---

app/src/main/res/layout/item_follow_request.xml

fix buttons and usernames overlapping in follow requests

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt

Prioritize users' default locales in language list

---

app/src/main/java/com/keylesspalace/tusky/components/account/media/AccountMediaFragment.kt

(basically same as in TimelineFragment)

correctly show "nothing here" in AccountMediaFragment

---

app/src/main/res/layout-sw640dp/fragment_view_thread.xml
app/src/main/res/layout/fragment_view_thread.xml

closes https://github.com/tuskyapp/Tusky/issues/2916
(the non-tablet file is just reformatted)

fix thread view on tablets

---

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java

Blindfix for #2970 , which I can't reproduce locally

Nullcheck channels when reading importance

---

app/src/main/java/com/keylesspalace/tusky/di/ViewModelFactory.kt

Seems like I messed up somewhere when resolving merge conflicts between PRs

fix crash when trying to add account to list from profile

---

app/src/main/java/com/keylesspalace/tusky/adapter/EmojiAdapter.kt

a small quality of life improvement i guess ^^

Show emoji codes on long press in the picker

---

app/src/main/res/layout/item_follow_request.xml

Also swapped the order to follow android's convention of having the positive button on the right.
When accepting follows I was always scared I'd hit the wrong button!

Increase the size of the accept/reject follow buttons

---

app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt

closes https://github.com/tuskyapp/Tusky/issues/2986

fix blocking accounts in thread view

---

app/src/main/java/com/keylesspalace/tusky/util/LocaleUtils.kt

Another incremental improvement for #2901

Sort language lists by the localized language name

---

app/src/main/java/com/keylesspalace/tusky/adapter/EmojiAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementsActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt

closes https://github.com/tuskyapp/Tusky/issues/2820

respect "animate emojis" setting in emoji picker

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/util/TouchDelegateHelper.kt

in conversations there is no boost button

fix crash in TouchDelegateHelper when not all views are available

---

app/schemas/com.keylesspalace.tusky.db.AppDatabase/46.json

add 46.json

---

app/src/main/java/com/keylesspalace/tusky/components/compose/view/EditTextTyped.kt

Fixes https://github.com/tuskyapp/Tusky/issues/3082.

Ensure text content is always pasted as plain text

---

app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java
app/src/main/java/com/keylesspalace/tusky/db/AccountEntity.kt

Fixes https://github.com/tuskyapp/Tusky/issues/3139

Respect "Always expand posts marked with content warnings" pref in notifications

---

app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt

MIME type detection for files based on extensions (the `getType()` method) returns incorrect results from DownloadProvider and FileProvider for (at least) .m4a files.
Investigation details are in https://github.com/tuskyapp/Tusky/issues/3189
Be safe, and use `MediaMetadataRetriever` to sniff the content of the files to determine the correct type.
Fixes https://github.com/tuskyapp/Tusky/issues/3189

Sniff MIME type for audio/video files before upload

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/components/login/LoginActivity.kt
app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
app/src/main/res/layout/activity_login.xml
app/src/main/res/values/strings.xml

#2767 
Maybe #2703
Maybe #2534
Maybe #2462

Reinstate optional login via custom browser tab

---

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt

Fix subscribe button state in AccountActivity

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt

Fixes https://github.com/tuskyapp/Tusky/issues/1587

Ensure the media description is visible over the video

---

app/src/main/res/layout/activity_main.xml

- Don't show a background
- add a content description
closes #3241

improve avatars next to tabs

---

app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt

Allow viewing of the account header image

---

app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsViewModel.kt
app/src/main/res/layout/activity_followed_tags.xml
app/src/main/res/layout/dialog_follow_hashtag.xml
app/src/main/res/values/strings.xml

- Add a FAB for user interaction (hide on scroll if appropriate)
- Show a dialog to collect the new hashtag
- Autocomplete hashtags the same as when composing a status

Add FAB to follow new hashtags from FollowedTagsActivity

---

app/src/main/res/layout/item_follow.xml

Use the same icon size/placement as other notifications.
Fixes https://github.com/tuskyapp/Tusky/issues/3279

Update avatar size/placement for follow requests

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/java/com/keylesspalace/tusky/util/ThemeUtils.kt
app/src/main/java/com/keylesspalace/tusky/view/GraphView.kt
app/src/main/java/com/keylesspalace/tusky/view/LicenseCard.kt

https://github.com/androidx/androidx/blob/17346638fffb173a69801ee4c9ea293588800214/core/core-ktx/src/main/java/androidx/core/content/res/TypedArray.kt#L227-L236

Use TypedArray.use to obtain attrs

---

app/src/main/java/com/keylesspalace/tusky/TabData.kt

(unless the tab is configurable, like hastag or list)
The code for this [was always in place](https://github.com/tuskyapp/Tusky/blob/6cc79c8d752925eb57d5ae693b0e4396ad794271/app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt#L301-L324), but it did not work because TabData.equals did not compare correctly.
fixes https://github.com/tuskyapp/Tusky/issues/3301

prevent adding multiple tabs of the same type

---

app/src/main/java/com/keylesspalace/tusky/appstore/CacheUpdater.kt
app/src/main/java/com/keylesspalace/tusky/db/TimelineDao.kt

This was causing a lot of ANRs

make sure all timeline database operations run on a background thread

---

app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt
app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt
app/src/main/java/com/keylesspalace/tusky/components/preference/AccountPreferencesFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportNoteFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/search/SearchActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/trending/TrendingAdapter.kt
app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt
app/src/main/java/com/keylesspalace/tusky/receiver/SendStatusBroadcastReceiver.kt
app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
app/src/test/java/com/keylesspalace/tusky/util/LocaleUtilsTest.kt

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/or-empty.html https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/or-empty.html

Use more orEmpty extensions

---

app/src/main/java/com/keylesspalace/tusky/appstore/Events.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt
app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt

Remove stale pre-edit statuses from the thread view

---

app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt

Don't display error message if user cancels picking an image

---

app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java

Remove accidentally doubled migration line.

Fix doubled line from PR 3188 (support mastodon filter api)

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt
app/src/main/java/com/keylesspalace/tusky/appstore/CacheUpdater.kt
app/src/main/java/com/keylesspalace/tusky/appstore/Events.kt
app/src/main/java/com/keylesspalace/tusky/appstore/EventsHub.kt
app/src/main/java/com/keylesspalace/tusky/components/account/AccountViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/instancemute/fragment/InstanceListFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/preference/AccountPreferencesFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledStatusActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/trending/viewmodel/TrendingViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
app/src/main/java/com/keylesspalace/tusky/settings/AccountPreferenceHandler.kt
app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt
app/src/test/java/com/keylesspalace/tusky/components/notifications/NotificationsViewModelTestStatusAction.kt
app/src/test/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModelTest.kt
app/src/test/java/com/keylesspalace/tusky/usecase/TimelineCasesTest.kt

They are quite coupled so it made sense to do them both at the same time.
#2992

Remove Rx from EventHub and TimelineCases

---

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/AddPollDialog.kt

3472: Give polls a default duration

---

app/lint-baseline.xml
bitrise.yml

follow up to https://github.com/tuskyapp/Tusky/pull/3363

add lint to ci checks

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
app/src/main/java/com/keylesspalace/tusky/util/SpanUtils.kt
app/src/main/java/com/keylesspalace/tusky/view/BackgroundMessageView.kt
app/src/main/res/drawable/help_message_background.xml
app/src/main/res/layout-sw640dp/fragment_timeline.xml
app/src/main/res/layout/fragment_timeline.xml
app/src/main/res/layout/view_background_message.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

Fixes #3408
Once this is reviewed I can also add the German text.

3408 home help message

---

app/src/main/java/com/keylesspalace/tusky/util/SpanUtils.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

3408: Only support iconics (get rid of "discouraged api")

---

app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt

Fixes https://github.com/tuskyapp/Tusky/issues/3469

3469: Do not jump in the list on the (second) refresh

---

app/src/main/java/com/keylesspalace/tusky/components/scheduled/ScheduledStatusActivity.kt
app/src/main/res/layout/activity_scheduled_status.xml

We are doing this everywhere but here

distinguish between different error types in ScheduledStatusActivity

---

app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/accountlist/AccountListFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/filters/FiltersActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/filters/FiltersViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
app/src/main/res/layout/activity_filters.xml
app/src/main/res/layout/activity_lists.xml
app/src/main/res/layout/fragment_account_list.xml

Touches / potentially fixes #3430
I have made the different lists more consistent:
* Everything should have a SwipeRefreshLayout
* Everything with an error screen ("message view") should have a retry button

3430: Make list refresh/retry consistent

---

app/src/main/res/values-night/theme_colors.xml
app/src/main/res/values/styles.xml

#3178: Increase contrast for separator lines in dark themes

---

app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

3416: Call the list activity when list list empty

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/notifications/StatusNotificationViewHolder.kt
app/src/main/res/layout/item_status_notification.xml

Fixes https://github.com/tuskyapp/Tusky/issues/3492

3492: Correctly shorten name in drawer and notifications

---

app/src/main/res/layout-sw640dp/fragment_timeline.xml
app/src/main/res/layout-sw640dp/fragment_timeline_notifications.xml
app/src/main/res/layout-sw640dp/fragment_view_thread.xml
app/src/main/res/layout/activity_announcements.xml
app/src/main/res/layout/activity_filters.xml
app/src/main/res/layout/activity_lists.xml
app/src/main/res/layout/activity_scheduled_status.xml
app/src/main/res/layout/fragment_account_list.xml
app/src/main/res/layout/fragment_timeline.xml
app/src/main/res/layout/fragment_timeline_notifications.xml
app/src/main/res/layout/fragment_trending.xml
app/src/main/res/layout/fragment_view_thread.xml

3503: SwipeRefreshLayout must be higher level

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/keylesspalace/tusky/components/filters/EditFilterActivity.kt
app/src/main/res/layout/activity_edit_filter.xml

3509: Ensure filter edit dialog is scrollable

---

app/proguard-rules.pro

We upgraded OkHttp, they are now included automatically

remove shrinker rules for okhttp

---

app/src/main/res/layout/item_status_notification.xml

Fixes https://github.com/tuskyapp/Tusky/issues/3550

Add padding below status content

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

Fixes https://github.com/tuskyapp/Tusky/issues/3588

Show 0/1/1+ for replies, even if show stats is off

---

app/src/main/java/com/keylesspalace/tusky/view/ClickableSpanTextView.kt

Fixes https://github.com/tuskyapp/Tusky/issues/3596

Force a layout pass to ensure spans are measured correctly

---

app/src/main/res/layout/item_poll.xml

https://github.com/tuskyapp/Tusky/pull/3459 did not cover the case where it is a not-yet-voted multiple choice poll

allow multiline polls (this time for real)

---

app/src/main/java/com/keylesspalace/tusky/adapter/FollowRequestViewHolder.kt
app/src/main/java/com/keylesspalace/tusky/components/accountlist/AccountListActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/accountlist/AccountListFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/accountlist/adapter/FollowRequestsAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/notifications/FollowViewHolder.kt
app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsPagingAdapter.kt
app/src/main/res/layout/activity_account_list.xml
app/src/main/res/layout/item_follow.xml
app/src/main/res/layout/item_follow_request.xml

Also fixes a bug where FollowRequestViewHolder would not show the bio if it has been previously bound to an account without bio.

make links in bios of follow request and follow notifications work

---

app/src/main/java/com/keylesspalace/tusky/components/filters/EditFilterActivity.kt
app/src/main/res/layout/activity_edit_filter.xml

Add delete button to edit filter activity

---

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java
app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt
app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt

make sure the active account is always correctly saved to database

---

app/src/main/java/com/keylesspalace/tusky/worker/WorkerFactory.kt

When NotificationWorker was moved from `...components.notifications` to `...worker`, installing Tusky with this change doesn't remove any future periodic jobs queued under the old class name.
So when `Class.forName()` is called the old class name is not found, and the exception is thrown.
Handle this the same way `androidx.work.WorkerFactory` does -- catch the exception, log it, and return null.
Fixes #3740

Catch missing classes in WorkerFactory

---

app/build.gradle
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationEntity.kt
app/src/main/java/com/keylesspalace/tusky/db/Converters.kt
app/src/main/java/com/keylesspalace/tusky/entity/DeletedStatus.kt
app/src/main/java/com/keylesspalace/tusky/entity/Status.kt
build.gradle
gradle/libs.versions.toml

- Add ksp plugin
- Switch room to use ksp instead of kapt
- `ArrayList` -> `List` in a few places to fix errors about unbound generics

Migrate "room" from "kapt" to "ksp"

---

app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt

Display the list's title in the array adapter

---

app/src/main/res/values/strings.xml

improve logout message

---

.github/workflows/ci.yml

Create an action that lints, tests, and builds the green debug variant.

Experiment with linting and testing using Github actions

---

app/build.gradle
gradle/libs.versions.toml

Migrate Glide compiler to KSP

---

app/src/main/java/com/keylesspalace/tusky/components/trending/viewmodel/TrendingViewModel.kt

fix crash in trending when there are no trends

---

gradle.properties

Follow up #3528.
https://docs.gradle.org/8.1/userguide/upgrading_version_8.html#configuration_caching_options_renamed

Use org.gradle.configuration-cache flag

---

app/schemas/com.keylesspalace.tusky.db.AppDatabase/52.json
app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/accountlist/AccountListActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/accountlist/AccountListFragment.kt
app/src/main/java/com/keylesspalace/tusky/db/AccountEntity.kt
app/src/main/java/com/keylesspalace/tusky/db/AccountManager.kt
app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java

Small improvement to the behavior on bad/disconnected networks
closes https://github.com/tuskyapp/Tusky/issues/3773

cache locked state of connected accounts

---

app/src/main/java/com/keylesspalace/tusky/components/filters/FiltersActivity.kt

Fixes #3839, https://github.com/tuskyapp/Tusky/issues/3525

Always update the filter display, even when the list is empty

---

app/build.gradle

Add a task to regenerate the lint baseline.

Add `newLintBaseline` task

---

app/src/main/java/com/keylesspalace/tusky/TabData.kt
app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt

TabData: added "Bookmarks" conditional to "createTabDataFromId" function
TabPreferenceActivity: added "Bookmarks" to "updateAvailableTabs" function
Fixes #2368

Adding "bookmarks" tab to timeline

---

app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt
app/src/main/java/com/keylesspalace/tusky/view/BackgroundMessageView.kt
app/src/main/res/values/strings.xml

3530: Provide a help text on the empty conversations view

---

app/src/main/java/com/keylesspalace/tusky/StatusListActivity.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
app/src/main/res/values/strings.xml

Fixes #3891 (the first two observerations; the rest is either ok or has another issue)

3891 better hashtag filtering

---

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/FocusDialog.kt
app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt
app/src/main/java/com/keylesspalace/tusky/view/MediaPreviewImageView.kt
gradle/libs.versions.toml

They added some nullability annotations to their Java code, which is nice but requires some changes in our Kotlin code.
closes #3975

upgrade glide to 4.16.0

---

app/src/main/res/values-es/strings.xml

Fix some typos and translations, hope it helps 👍🏻

Update Spanish translations

---

doc/PaymentPolicy.md

Document copied from CryptPad as approved by the team in the 2023-09-25 meeting.

Payment Policy Document

---

app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt

Ugh, I didn't notice that #3480 was affected by the notification fragment rollback

Fix build after logical conflict

---

app/src/main/AndroidManifest.xml

#3570: Also provide a "direct" back with the hardware button

---

app/src/main/java/com/keylesspalace/tusky/appstore/Events.kt
app/src/main/java/com/keylesspalace/tusky/components/filters/EditFilterActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt

Refresh timelines when filters are added/edited/removed

---

app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt
app/src/main/res/layout/item_announcement.xml

Close #3967 
- Displayed the date of each announcement.
- Date is placed in the lower left corner of the Announcement
- Supported date format internationalization using getBestDateTimePattern
<image src="https://github.com/tuskyapp/Tusky/assets/62137820/7c124183-1a13-4cae-8667-ff82ca99b60c" width="500"/>
I am not good at English so I use machine translation a bit. So, you may find my writing style a little strange...

Displayed the date of each announcement.

---

app/src/main/java/com/keylesspalace/tusky/BaseActivity.java
app/src/main/java/com/keylesspalace/tusky/TuskyApplication.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/preference/PreferencesFragment.kt
app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt
app/src/main/java/com/keylesspalace/tusky/util/ThemeUtils.kt

closes #4060 
Also I noticed that we had the theme defaults twice in the code so I refactored a bit so only one are still in there.

fix theme preference defaults

---

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt

closes https://github.com/tuskyapp/Tusky/issues/1271
before:
after:

make blockquotes pretty

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt

I tried to ind out why the imageview was cleared here but to no avail. Removing it also doesn't seems to have unwanted sideeffects 🤷

fix images in ViewImageFragment disappearing when switching apps

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt

fix image scaling after swipe down gesture ended in ViewImageFragment

---

app/lint-baseline.xml

The xml was malformed (probably because of some merge) so lint just did not check anything

fix broken lint-baseline.xml

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationsFragment.kt

Saw an ANR (app not responding) error being reported in the Play console and then found this. Sorry but `runBlocking` in production code is an absolute no go.

fix ANR caused by direct message badge

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java

closes https://github.com/tuskyapp/Tusky/issues/3096

show post language in metadata

---

app/src/main/java/com/keylesspalace/tusky/TabPreferenceActivity.kt

fix check that ensures only one bookmark tab is added

---

.github/ISSUE_TEMPLATE/1.bug_report.yml
.github/ISSUE_TEMPLATE/2.feature_request.yml
.github/ISSUE_TEMPLATE/config.yml
ISSUE_TEMPLATE.md

inspired by https://github.com/mastodon/mastodon/tree/main/.github/ISSUE_TEMPLATE

new issue templates

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt

fix boost/reply filters not working correctly in home timelines

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeAutoCompleteAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt
app/src/main/java/com/keylesspalace/tusky/components/login/LoginWebViewActivity.kt
app/src/main/java/com/keylesspalace/tusky/util/Either.kt
app/src/main/java/com/keylesspalace/tusky/util/Resource.kt
app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.kt
app/src/main/java/com/keylesspalace/tusky/viewdata/TrendingViewData.kt
app/src/main/java/com/keylesspalace/tusky/viewmodel/AccountsInListViewModel.kt

There is no non-abstract field in them, we can just fall back to interfaces.

Convert some sealed classes to interfaces

---

app/src/main/java/com/keylesspalace/tusky/entity/Translation.kt
app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.kt

The docs are wrong https://github.com/mastodon/documentation/pull/1423 🙄

fix translating polls and spoilers

---

app/build.gradle
app/lint-baseline.xml

add the correct information to regenerate the lint baseline file

---

settings.gradle

https://docs.gradle.com/enterprise/gradle-plugin/legacy/#develocity_migration

Migrate to develocity plugin

---

app/src/main/java/com/keylesspalace/tusky/components/login/LoginWebViewViewModel.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt

show rules of the correct instance on the auth screen

---

.github/workflows/populate-gradle-build-cache.yml

upgrade to gradle/actions/wrapper-validation@v3 in the other workflow as well 🙄

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
gradle/libs.versions.toml

https://developer.android.com/jetpack/androidx/releases/activity#1.9.0

upgrade androidx-activity to 1.9.0

---

app/src/main/java/com/keylesspalace/tusky/components/preference/AccountPreferencesFragment.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt

It is the last place where we used a Call 🥳

refactor accountUpdateSource from Call to coroutine

---

app/src/main/java/com/keylesspalace/tusky/util/GlideExtensions.kt
app/src/main/java/com/keylesspalace/tusky/util/ShareShortcutHelper.kt

[v25.1] fix crash when glide fails to load avatar in ShareShortcutHelper

---

app/src/main/java/com/keylesspalace/tusky/entity/Translation.kt

see https://github.com/tuskyapp/Tusky/pull/4307#issuecomment-2093827027

add default value to Translation.mediaAttachments to fix translation on some servers

---

app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt

Fix bot badge in accounts in list fragment

---

app/src/main/java/com/keylesspalace/tusky/AboutActivity.kt
app/src/main/java/com/keylesspalace/tusky/ViewMediaActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/account/AccountActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/search/fragments/SearchStatusesFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.kt
app/src/main/java/com/keylesspalace/tusky/interfaces/HashtagActionListener.kt
app/src/main/java/com/keylesspalace/tusky/util/ActivityExtensions.kt
app/src/main/res/values/strings.xml

Add click and longpress handler to the followed hashtags view
#4459

Followed hashtags view improvements

---

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.kt

remove unused import

---

app/schemas/com.keylesspalace.tusky.db.AppDatabase/62.json

should have been added in #4496

add database schema v62

---

app/src/main/java/com/keylesspalace/tusky/components/compose/MediaPreviewAdapter.kt

Found this crash in the Google Play reports:
```
Exception java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds (Preconditions.java:64)
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex (Preconditions.java:70)
at jdk.internal.util.Preconditions.checkIndex (Preconditions.java:266)
at java.util.Objects.checkIndex (Objects.java:359)
at java.util.ArrayList.get (ArrayList.java:434)
at java.util.Collections$UnmodifiableList.get (Collections.java:1394)
at com.keylesspalace.tusky.components.compose.MediaPreviewAdapter.onMediaClick (MediaPreviewAdapter.java:45)
at com.keylesspalace.tusky.components.compose.MediaPreviewAdapter.access$onMediaClick (MediaPreviewAdapter.java:32)
at …
```

improve MediaPreviewAdapter / fix IndexOutOfBoundsException

---

app/src/main/res/layout/activity_filters.xml

Missed that in https://github.com/tuskyapp/Tusky/pull/4486

add bottom padding to FiltersActivity RecyclerView

---

app/src/main/AndroidManifest.xml

exclude compose activity from recents

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt

re: https://infosec.exchange/@webhat/112745609655586468
Boost were not correctly handled here, probably because they are only on profile timelines which I rarely check. This makes sure likes and boosts get correctly set to posts even when they are boosts.

fix updating boosts in network timeline

---

app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt
app/src/main/res/layout/fragment_view_video.xml

Fixes issue where alt text positioning covers video controller
Also adds scroll view for more responsive scrolling
closes #4165

Fixes issue where alt text positioning covers video controller

---

app/src/main/java/com/keylesspalace/tusky/fragment/SFragment.kt
app/src/main/res/menu/status_more_for_user.xml

This allows user to translate own post
Closes #4645

This allows user to translate own post

---

app/src/main/java/com/keylesspalace/tusky/util/StatusParsingHelper.kt

closes https://github.com/tuskyapp/Tusky/issues/4663

remove extra newlines on some PIxelfed posts

---

app/lint-baseline.xml
app/src/main/java/com/keylesspalace/tusky/BaseActivity.java
app/src/main/java/com/keylesspalace/tusky/StatusListActivity.kt
app/src/main/java/com/keylesspalace/tusky/TabData.kt
app/src/main/java/com/keylesspalace/tusky/adapter/PlaceholderViewHolder.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeAutoCompleteAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt
app/src/main/java/com/keylesspalace/tusky/components/compose/view/ComposeScheduleView.kt
app/src/main/java/com/keylesspalace/tusky/components/drafts/DraftHelper.kt
app/src/main/java/com/keylesspalace/tusky/components/login/LoginActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchHashtagsAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/systemnotifications/NotificationFetcher.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/CachedTimelineViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/NetworkTimelineViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/viewmodel/TimelineViewModel.kt
app/src/main/java/com/keylesspalace/tusky/components/trending/TrendingTagViewHolder.kt
app/src/main/java/com/keylesspalace/tusky/fragment/ViewImageFragment.kt
app/src/main/java/com/keylesspalace/tusky/fragment/ViewVideoFragment.kt
app/src/main/java/com/keylesspalace/tusky/network/FilterModel.kt
app/src/main/java/com/keylesspalace/tusky/util/NumberUtils.kt
app/src/main/java/com/keylesspalace/tusky/util/StatusViewHelper.kt
app/src/main/res/values-hu/strings.xml
app/src/main/res/values/donottranslate.xml

Mostly "StringFormatTrivial" which I think is new, but it makes totally sense to fix

fix new warnings, regenerate lint-baseline.xml

---

.github/workflows/deploy-release.yml
.github/workflows/deploy-test.yml

Re: https://github.com/tuskyapp/Tusky/pull/4682#issuecomment-2402485451
Ok that was quick.
According to the error message, that should fix the problem.
https://github.com/tuskyapp/Tusky/actions/runs/11256946411/job/31300028953

add checkout step to deploy pipelines

---

.github/workflows/deploy-release.yml
.github/workflows/deploy-test.yml

this should fix the problem where the secrets are not available in the workflow https://github.com/tuskyapp/Tusky/actions/runs/11276192946/job/31362570493

add environment to workflows

---

app/src/main/java/com/keylesspalace/tusky/appstore/Events.kt
app/src/main/java/com/keylesspalace/tusky/entity/ScheduledStatus.kt
app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt
app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt

don't spam endless posts when trying to schedule on GoToSocial

---

app/src/main/res/values/strings.xml

https://chaos.social/@bess@toot.cat/113602001349352104

change text from "Always show sensitive content" to "Always show sensitive media"

---

app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
app/src/main/res/layout/activity_compose.xml

Regression from the Material 3 redesign

show the warning icon again when there is media without description

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java

closes https://github.com/tuskyapp/Tusky/issues/4838

hide trailing hashtags when post is collapsed

---

app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt

Mastodon "normalizes" tag text for latin characters when storing tag names, so the hashtag object it sends for `#Über` has the name `uber`. With the new trailing hashtag bar, this was causing nonascii hashtags from the post content to be duplicated with their normalized versions, e.g. `#Über #uber`.
This change ensures that we're always comparing normalized tag names.

Fix comparison of nonnormalized latin tags

---

app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusDetailedViewHolder.java
app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java
app/src/main/java/com/keylesspalace/tusky/components/notifications/StatusNotificationViewHolder.kt
app/src/main/java/com/keylesspalace/tusky/components/notifications/StatusViewHolder.kt
app/src/main/java/com/keylesspalace/tusky/components/search/adapter/SearchStatusesAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelinePagingAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineTypeMappers.kt
app/src/main/java/com/keylesspalace/tusky/components/viewthread/ThreadAdapter.kt
app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadViewModel.kt
app/src/main/java/com/keylesspalace/tusky/db/dao/TimelineDao.kt
app/src/main/java/com/keylesspalace/tusky/db/entity/HomeTimelineEntity.kt
app/src/main/java/com/keylesspalace/tusky/entity/Status.kt
app/src/main/java/com/keylesspalace/tusky/viewdata/StatusViewData.kt
app/src/main/res/drawable/ic_reply_all_18dp.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/keylesspalace/tusky/components/timeline/TimelineFaker.kt

Earlier PR: https://github.com/tuskyapp/Tusky/pull/3778
Fixes: https://github.com/tuskyapp/Tusky/issues/3771

3771: Add "display replied to" functionality

---

app/src/main/java/com/keylesspalace/tusky/components/conversation/ConversationViewHolder.java

regression from https://github.com/tuskyapp/Tusky/pull/4909

fix conversation tab not having any content

---

app/src/main/res/layout-land/item_trending_cell.xml
app/src/main/res/layout/item_trending_cell.xml

fix trending tag ellipsized too soon

---

app/src/main/java/com/keylesspalace/tusky/components/notifications/requests/details/NotificationRequestDetailsActivity.kt
app/src/main/res/layout/activity_notification_request_details.xml

handle bottom insets in NotificationRequestDetailsActivity

---

app/src/main/res/values/donottranslate.xml

Adjust mute duration values to indefinite, 1 hour, 6 hours, 1 day, 7 days, 30 days and 180 days.
Fixes #4914

Adjust mute duration values (issue #4914)

---

app/src/main/java/com/keylesspalace/tusky/ListsActivity.kt

fixes https://github.com/tuskyapp/Tusky/issues/4934

don't reset the reply policy when updating a list

---

fastlane/metadata/android/en-US/changelogs/131.txt

So it can be translated while the beta runs

update short changelog for Release 131

---

app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt
app/src/main/java/com/keylesspalace/tusky/db/DraftsAlert.kt

- makes sure there is only ever one dialog shown at a time
- also shows the dialog in the thread view
closes https://github.com/tuskyapp/Tusky/issues/4982

fix draft alert showing

---

app/src/main/java/com/keylesspalace/tusky/di/NetworkModule.kt
app/src/main/java/com/keylesspalace/tusky/entity/PreviewCard.kt
app/src/main/java/com/keylesspalace/tusky/json/GuardedAdapter.kt
app/src/test/java/com/keylesspalace/tusky/json/GuardedAdapterTest.kt

fix loading posts with invalid `published_at` in preview card

---

app/src/main/java/com/keylesspalace/tusky/components/compose/dialog/CaptionDialog.kt
app/src/main/res/values/strings.xml

as discussed in https://github.com/tuskyapp/Tusky/pull/4942
Suggestions for a better text welcome.

add additional dialog to prevent accidentally dismissing the caption dialog

---

app/src/main/java/com/keylesspalace/tusky/db/DatabaseCleaner.kt
app/src/main/java/com/keylesspalace/tusky/db/dao/NotificationPolicyDao.kt

delete NotificationPolicy cache on logout

---

app/src/main/java/com/keylesspalace/tusky/MainActivity.kt
app/src/main/java/com/keylesspalace/tusky/components/viewthread/ViewThreadFragment.kt
app/src/main/res/layout/activity_main.xml

fix bottom app bar and thread view in edge-to-edge mode

---

app/src/main/java/com/keylesspalace/tusky/TuskyApplication.kt
app/src/main/java/com/keylesspalace/tusky/settings/SettingsConstants.kt

remove duplicate notification channel

---

fastlane/metadata/android/de/changelogs/127.txt
fastlane/metadata/android/de/changelogs/131.txt

Translations update from [Weblate](https://weblate.tusky.app) for [Tusky/Tusky description](https://weblate.tusky.app/projects/tusky/tusky-app/).
Current translation status:

Metadata translations update from Weblate (automated)

---

app/src/main/java/com/keylesspalace/tusky/components/account/media/AccountMediaFragment.kt

see https://github.com/tuskyapp/Tusky/issues/5002#issuecomment-2781122748

fix AccountMediaFragment insets

---

app/src/main/res/layout/activity_filters.xml

fix toolbar overlap in FiltersActivity on Android 15

---

app/build.gradle
app/proguard-rules.pro

We wouldn't want to ship unnecessary stuff, would we
apk size 20.788.307 ->  20.768.841 bytes 🤪

update shrinker rules and packaging excludes

---

app/src/main/res/layout/activity_about.xml

fix AboutActivity layout while loading instance data

---

app/src/main/res/layout/item_conversation.xml
app/src/main/res/layout/item_status.xml
app/src/main/res/layout/item_status_detailed.xml
app/src/main/res/values/strings.xml

improve poll voting button layout

---

app/src/main/java/com/keylesspalace/tusky/components/timeline/TimelineFragment.kt

closes https://github.com/tuskyapp/Tusky/issues/5098

fix fav button animation in timelines

---

app/src/main/java/com/keylesspalace/tusky/util/AttachmentHelper.kt

speculative fix for https://github.com/tuskyapp/Tusky/issues/5113

fix crash when attachment has no size information

---

app/src/main/java/com/keylesspalace/tusky/view/ConfirmationBottomSheet.kt

https://social.coop/@flancian/114479204308663104

fix confirm favorite default
